### ISSUE TITLE
UDO display [sf#12]

### ISSUE THREAD

**Issue by mantaraya36** [CsoundQt/CsoundQt#141]
**Reported by joachimheintz on 2010-03-09 08:08 UTC**
Wishes while working with UDOs:
1. syntax highlight like usual opcodes
2. if possible with input/output arguments at the bottom of the main window
3. and autocompletion (well this is luxus ...)

**Comment by boonier** [comment]
Bump!

**Comment by gesellkammer** [comment]
Syntax highlighting for UDOs is implemented as 0.9.8.
Input/Output arguments at the bottom, parsing xin/xout still to come
Autocompletion is already working
Will close this and open an issue only for syntax hint in the statusbar/tooltip
