### ISSUE TITLE
Add optional grid and auto-align in widget editor [sf#41]

### ISSUE THREAD

**Issue by mantaraya36** [CsoundQt/CsoundQt#170]
**Reported by dave_seidel on 2010-09-04 20:22 UTC**
I would find it much easier to make a panel with multiple widgets look good if I could turn on the display of a grid an an alignment aid, and if the widget editor was able to auto-align.

**Comment by mantaraya36** [comment]
**Commented by mantaraya36 on 2010-09-04 21:01 UTC**
There are many aligning features in the right click menu, but you are right a grid would be handy.

**Comment by gesellkammer** [comment]
A grid is implemented in 0.9.8 when dragging a widget via the keyboard
