### ISSUE TITLE
In the manual window ctrl-f for finding things [sf#42]

### ISSUE THREAD

**Issue by mantaraya36** [CsoundQt/CsoundQt#171]
**Reported by aparaatti on 2010-09-17 17:18 UTC**
Would be great to have some sort of search ability there

**Comment by mantaraya36** [comment]
**Updated by aparaatti on 2010-09-17 17:24 UTC**
- **summary**: In the help window ctrl-f for finding things --> In the manual window ctrl-f for finding things

**Comment by gesellkammer** [comment]
Fixed in 0.9.8
