### ISSUE TITLE
Remember previous position of widget edit window [sf#50]

### ISSUE THREAD

**Issue by mantaraya36** [CsoundQt/CsoundQt#179]
**Reported by loucohen on 2012-05-10 19:52 UTC**
When double-clicking a widget, the widget edit window appears and hides
most of the widget window/panel. I must move the edit window to the side so
that I can refer to the widgets already there in order to decide on details
I want to edit. If I close the edit window and then double click another
widget to edit, the window repositions itself in the center of the widget
window/panel. In other words, csoundQT does not remember where I moved the
widget edit window. So I must move it every time i open it. Please cause csoundQT to remember
the most recent position of this window so that editing of a series of widgets is more convenient.

**Comment by gesellkammer** [comment]
Where a new window is opened depends on the platform / window manager.
