### ISSUE TITLE
Widget for creating dynamic envelopes. [sf#55]

### ISSUE THREAD

**Issue by mantaraya36** [CsoundQt/CsoundQt#184]
**Reported by *anonymous on 2012-12-27 19:31 UTC**
Hi :) 

I would love to be able to create advanced envelopes in QuteCsound via the Widgets, and then be able to controll them via a midi controller.
It seems to me that there is no way to visually create envelopes, othern than using sliders.
I would like to be able to draw an envelope of any size I want, is it possible to do already with the existing widgets or would you concider implementing something like this?

Thank you for the software :)

**Comment by mantaraya36** [comment]
**Commented by nobody on 2012-12-27 19:54 UTC**
loopseg could be used I think.
http://www.csounds.com/manual/html/loopseg.html

**Comment by gesellkammer** [comment]
This is possible via "Show Table Editor"
