### ISSUE TITLE
Should ship a .desktop file

### ISSUE THREAD

**Issue by fsateler** [CsoundQt/CsoundQt#195]
This is what modern desktop environments on linux use to populate the application menus. Here is a template that at least makes it show on my system:

```
[Desktop Entry]
Comment=IDE for csound
Encoding=UTF-8
Exec=csoundqt %F
Icon=qtcs
MimeType=text/x-csound-csd
Name=CsoundQt
NoDisplay=false
StartupNotify=true
Terminal=0
TerminalOptions=
Type=Application
```

For the icon, it is necessary to install the icons in `/usr/share/icons` according to the resolution subdir.

**Comment by fsateler** [comment]
Some more improvements:

```
Categories=AudioVideo;Audio;
GenericName=IDE for csound
```

The GenericName is what the DEs actually show (it appears the Comment is unused). The categories are used by menus that split by categories (kde does this, gnome apparently doesn't).

**Comment by fsateler** [comment]
There is a tool `desktop-file-validate`. Using it and fixing warning yields:

```ini
[Desktop Entry]
Exec=csoundqt %F
Icon=qtcs
MimeType=text/x-csound-csd;
Name=CsoundQt
NoDisplay=false
StartupNotify=true
Terminal=false
Type=Application
Categories=AudioVideo;Audio;
GenericName=IDE for csound
```

**Comment by tarmoj** [comment]
Yes, sure it ia be good to add, thanks! Works for me, too (opensSuse). I will see how it is best to add to the qmake configuration for install.

**Comment by tarmoj** [comment]
Now added to git. Gets installed with 'make install' to $HOME/.local/share/applications

**Comment by fsateler** [comment]
@tarmoj thanks! Is the path overridable? I would like to use the `make install` for the debian builds, but I can't ship a file in $HOME in a package...

**Comment by tarmoj** [comment]
Hi,

I think so too, that the installation should be system wide. For now you 
cannot specify the path as a qmake parameter, but you can edit the 
qcs.pro file. Have a look at lines 156-157

unix {
	INSTALL_DIR=~ # HOME, later use /usr/local and others for 
icosns, dekstop file etc
	SHARE_DIR=~/.local/share # /usr/share for system install

#etc

If you change INSTALL_DIR to /usr/local or /usr and SHARE_DIR to 
/usr/share it should work.

Can you try? Please run make uninstall first to remove the local 
installation.

Also I don't know how to do about the mime-types folder where the 
add_csound_ mimetypes.sh script installs files to home folder. You should 
probably edit that too. Well, I don't know much about pacakging...

Let know, how it goes and how you suggest to organise in the source code.

Best!
tarmo

On Monday 15 February 2016 18:56:02 Felipe Sateler wrote:
> @tarmoj thanks! Is the path overridable? I would like to use the `make
> install` for the debian builds, but I can't ship a file in $HOME in a
> package...
> 
> ---
> Reply to this email directly or view it on GitHub:
> 
https://github.com/CsoundQt/CsoundQt/issues/195#issuecomment-184489
932

**Comment by fsateler** [comment]
On 16 February 2016 at 04:34, tarmoj <notifications@github.com> wrote:

> Hi,
>
> I think so too, that the installation should be system wide. For now you
> cannot specify the path as a qmake parameter, but you can edit the
> qcs.pro file. Have a look at lines 156-157
>
> unix {
> INSTALL_DIR=~ # HOME, later use /usr/local and others for
> icosns, dekstop file etc
> SHARE_DIR=~/.local/share # /usr/share for system install
>
> #etc
>
> If you change INSTALL_DIR to /usr/local or /usr and SHARE_DIR to
> /usr/share it should work.
>
> Can you try? Please run make uninstall first to remove the local
> installation.
>

I will try this. I think qmake generates makefiles that respect the DESTDIR
environment variable, so it can be tested without local install via `make
install DESTDIR=/tmp/qcs-test`.

I am no expert in qmake, but I think it should have a concept of PREFIX
(the root directory to which stuff will be installed). Then all other
install directories are made relative to this prefix.


>
> Also I don't know how to do about the mime-types folder where the
> add_csound_ mimetypes.sh script installs files to home folder. You should
> probably edit that too. Well, I don't know much about pacakging...
>

Those I think go in /usr/share/mime-types or something like that. Will
investigate.


>
> Let know, how it goes and how you suggest to organise in the source code.
>

I now realize I am not currently using the make install target for the
debian package. I will see if I can make use of the target to simplify
things. I'll report back once I have done so.



-- 

Saludos,
Felipe Sateler

**Comment by tarmoj** [comment]
I  changed now the pathes in qcs.pro and add_csound_mimetypes.sh for system wide installation (to /usr/local/bin and /usr/share). Works nicely for me.
