### ISSUE TITLE
Make the cursor stay when doing EvalSection

### ISSUE THREAD

**Issue by hlolli** [CsoundQt/CsoundQt#196]
When doing ctrl+shift+w the cursor tends to move away from the place where the command was executed. It's not important, but can improve the speed of re-evaluation. (I by the way am not using the newest git version of csoundqt so Im sorry if this has already been fixed).

**Comment by tarmoj** [comment]
Hi,
Can you explain once again - do you mean Evaluate section? Like evaluating
the whole instrument?
At my case  the whole instrument gets selected and to get out of it, you
need to click somewhere. I did not try - is it problem with long
instruments, that get scrolled down? Or did you mean Evaluate selection? I
noticed, indeed, the cursor moves one row down after evaluation...

Did you have any luck with building with Qt5?

Tarmo
29.01.2016 12:51 kirjutas kuupäeval "Hlöðver Sigurðsson" <
notifications@github.com>:

**Comment by hlolli** [comment]
Yes evaluating the whole instrument (eval section),

is the pipeline symbol | is the cursor then the current behaviour is like this:

instr x
some stuff
that does not |
matter
endin

--> ctrl+shift+w -->
|instr x
some stuff
that does not
matter
endin

(and it's also all selected which is a behaviour I question but wouldn't mind if other users find this useful).

About getting my CsoundQt to work with Qt5, I think I need to replace the new library files. But since Im finishing this article relying heavily on CsoundQt, Im just going to do that after the weekend, Im sure this is just a small bug which I sent you the other day. And about this cursor behaviour, it's also obviously not an urgent fix, but something to keep in mind for future releases.

**Comment by tarmoj** [comment]
Hi, I think I fixed it. Now when you press EvalueateSection, the instrument or block gets selected and evaluated. Then you need to press to an ARROW key (otherwise the selection gets overwritten anyway) and the cursor position is restored where it was. Hope it works for you!
