### ISSUE TITLE
header files missing for html5 option

### ISSUE THREAD

**Issue by dsp1986** [CsoundQt/CsoundQt#197]
the following files are missing from src/
`client_handler_qt.h` and `cefclient_qt.h`
how can I get them?

**Comment by dsp1986** [comment]
since they don't get included in their respective .cpp files I tried commenting these files in src/src.pri
unfortunately compiling doesn't work this way. 
I am really excited to use html5 as csound frontend.

**Comment by tarmoj** [comment]
Thanks for reporting! I forwarded it to Michael, who has written the html5
part of code.
Which operating system are you on?
Tarmo
13.02.2016 19:24 kirjutas kuupäeval "dsp1986" <notifications@github.com>:

**Comment by dsp1986** [comment]
Debian 8 (stable)
thank you!

**Comment by tarmoj** [comment]
CEF build is dropped, QtWebengine/QtWebkit used instread (branch qhtml)
