### ISSUE TITLE
unable to build on 10.11

### ISSUE THREAD

**Issue by ukelady** [CsoundQt/CsoundQt#199]
Hi! I was trying to build CsoundQt as the one come with csound can't be opened on OS 10.11

However, I got a bunch of warning and error message saying "symbol(s) not found for architecture x86_64". Should I change some config settings?

ignoring file build/doubles/obj/moc_qutesheet.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_qutesheet.old: warning: 
ignoring file build/doubles/obj/moc_basedocument.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_basedocument.old: warning: ld: warning: 
ignoring file build/doubles/obj/moc_baseview.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_baseview.oignoring file build/doubles/obj/moc_appwizard.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_appwizard.old: warning: 

ignoring file build/doubles/obj/moc_appdetailspage.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_appdetailspage.old: warning: 
ignoring file build/doubles/obj/moc_pluginspage.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_pluginspage.old: warning: ld: warning: 
ignoring file build/doubles/obj/moc_additionalfilespage.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_additionalfilespage.oignoring file build/doubles/obj/moc_scoreeditor.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_scoreeditor.old: warning: 

ignoring file build/doubles/obj/moc_filebeditor.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_filebeditor.old: warning: 
ignoring file build/doubles/obj/moc_midihandler.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_midihandler.old: warning: ld: warning: ld: warning: 
ignoring file build/doubles/obj/moc_midilearndialog.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_midilearndialog.oignoring file build/doubles/obj/moc_debugpanel.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_debugpanel.oignoring file build/doubles/obj/moc_livecodeeditor.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_livecodeeditor.o

ld: warning: ignoring file build/doubles/obj/moc_newbreakpointdialog.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_newbreakpointdialog.o
ld: warning: ignoring file build/doubles/obj/moc_csoundhtmlview.o, file was built for i386 which is not the architecture being linked (x86_64): build/doubles/obj/moc_csoundhtmlview.o
Undefined symbols for architecture x86_64:
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/CsoundQt-d-cs6.app/Contents/MacOS/CsoundQt-d-cs6] Error 1

**Comment by tarmoj** [comment]
Hi,

Thanks, it does not seem so much as a bug report than subject for discussion 
in the mailing list. If you are not already, please join the mailing list,
https://lists.sourceforge.net/lists/listinfo/qutecsound-users

Then descirbe more in detail what you did, how did you get the source, did you 
use QtCreator or command line for building etc

Please have a look for the buildin instructions here:
https://github.com/CsoundQt/CsoundQt/blob/master/BUILDING.md
and wiki:
https://github.com/CsoundQt/CsoundQt/wiki

Best!
tarmo
