### ISSUE TITLE
default path for csound manual

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#204]
if csoundqt is installed via the windows and mac installer, the path for the csound manual is known.

this default path should be used for csoundqt to look for the manual. (currently the path must be set in Configure > Environment, at least for the windows build.)

**Comment by tarmoj** [comment]
Fixed. If htmldir is not set, CoundQt looks for manual from where it could be installed (Linux, Windows, OSX) and shows the manual.
Commit: https://github.com/CsoundQt/CsoundQt/commit/9f199f2f80a5fbeb6c87f42671264afe80f8ae70
