### ISSUE TITLE
The Floss Examples, Iain McCurdy Examples, Stria Synth examples missing from menu

### ISSUE THREAD

**Issue by tarmoj** [CsoundQt/CsoundQt#206]
Output in console:

Warning: Could not find FLOSS Manual Examples.
Warning: Could not find McCurdy Collection.
Warning: Could not find Stria Synth files.

Have a look at the code and find the examples :)

**Comment by joachimheintz** [comment]
hi tarmo -

which build are you referring to?  on my linux build (with qtcreator), 
these examples are there.  i will look later on the osx 10.10 build we 
did some weeks ago.

	j

**Comment by joambi** [comment]
Hi,

in osx 10.10 there are in  /src/example
but not in the  path for the build?
I have to copy that in the bundles….
LG

Johannes
—
—
Zürcher Hochschule der Künste
Zurich University of the Arts
—
Johannes Schütt
Wiss. Mitarbeiter Institute for Computer Music and Sound Technology
—
Pfingstweidstrasse 96, Postfach, 8031 Zürich
Telefon +41 43 446 51 72, Mobile +41 79 786 12 49
johannes.schuett@zhdk.ch<mailto:johannes.schuett@zhdk.ch>
—
www.zhdk.ch<http://www.zhdk.ch>, http://www.icst.net
—

Am 13.03.2016 um 11:35 schrieb joachimheintz <notifications@github.com<mailto:notifications@github.com>>:

hi tarmo -

which build are you referring to? on my linux build (with qtcreator),
these examples are there. i will look later on the osx 10.10 build we
did some weeks ago.

j

**Comment by joachimheintz** [comment]
ok - i checked the osx 10.10 version we have built some weeks ago, and indeed the floss etc examples are missing.

**Comment by tarmoj** [comment]
They are not also int Github repo. How big are they? If not too big, could
you push them? Or there are other considerations why not to include them in
source?
If you push, please to the develop branch.
Tamo
13.03.2016 14:22 kirjutas kuupäeval "joachimheintz" <
notifications@github.com>:

**Comment by joachimheintz** [comment]
no, they are there:
https://github.com/CsoundQt/CsoundQt/tree/develop/src/Examples

it is just another location than the other examples.  this has always 
been this way.  the reason is that andrés scripted it in the way we can 
add automatically, without manually doing each step.

i think the problem must be a wrong path when including the examples. 
should not be very difficult to find and fix.

   joachim

**Comment by tarmoj** [comment]
Oh, right,
There are ./examples and ./src/Examples.
I will figure out how it is coded and how to fix for non usual cases.
Thanks!
Tarmo
13.03.2016 16:55 kirjutas kuupäeval "joachimheintz" <
notifications@github.com>:
