### ISSUE TITLE
MidiKeyboard

### ISSUE THREAD

**Issue by joambi** [CsoundQt/CsoundQt#207]
after <macdeployqt> the MidiKeyboard  is empty.
Console tells:
QObject::connect: No such signal FileBEditor::textChanged()
QObject::connect:  (sender name:   'FileBEditor')
QObject::connect: No such signal FileBEditor::textChanged()
QObject::connect:  (sender name:   'FileBEditor')
QObject::connect: No such slot DocumentPage::evaluate(QString)
CsoundQt::openMidiOutPort opened port  0
qrc:/QML/VirtualKeyboard.qml:2:1: module "QtQuick.Layouts" is not installed
qrc:/QML/VirtualKeyboard.qml:1:1: module "QtQuick" is not installed
qrc:/QML/VirtualKeyboard.qml:2:1: module "QtQuick.Layouts" is not installed
qrc:/QML/VirtualKeyboard.qml:1:1: module "QtQuick" is not installed
QObject::connect: Cannot connect (null)::genNote(QVariant, QVariant, QVariant, QVariant) to CsoundQt::virtualMidiIn(QVariant, QVariant, QVariant, QVariant)
QObject::connect: Cannot connect (null)::newCCvalue(int,int,int) to CsoundQt::virtualCCIn(int, int, int)

The path to QML is: ~/src/CsoundQt/bin/CsoundQt-d-cs6.app/Contents/Resources/QML

before deployment everything looks ok.

**Comment by tarmoj** [comment]
Hi,

Thanks, the useful part of the info is:

qrc:/QML/VirtualKeyboard.qml:2:1: module "QtQuick.Layouts" is not installed
qrc:/QML/VirtualKeyboard.qml:1:1: module "QtQuick" is not installed
qrc:/QML/VirtualKeyboard.qml:2:1: module "QtQuick.Layouts" is not installed
qrc:/QML/VirtualKeyboard.qml:1:1: module "QtQuick" is not installed

The qml and qtquick part is quite new and probably not added to the
bundleing script. Can you figure out how to add these modules/libraries to
bundle?
O guess they should be usend in CsoundQt 0.9.0 If you examine the osx
CsoundQt installer from sourceforge, perhaps this gives a clue.

Tarmo
13.03.2016 19:08 kirjutas kuupäeval "Johannes Schütt" <
notifications@github.com>:

**Comment by joambi** [comment]
hi,

I think the issue „MidiKeybord“ is fixed!

best

Johannes
—
—
Zürcher Hochschule der Künste
Zurich University of the Arts
—
Johannes Schütt
Wiss. Mitarbeiter Institute for Computer Music and Sound Technology
—
Pfingstweidstrasse 96, Postfach, 8031 Zürich
Telefon +41 43 446 51 72, Mobile +41 79 786 12 49
johannes.schuett@zhdk.ch<mailto:johannes.schuett@zhdk.ch>
—
www.zhdk.ch<http://www.zhdk.ch>, http://www.icst.net
—

Am 13.03.2016 um 18:25 schrieb tarmoj <notifications@github.com<mailto:notifications@github.com>>:

Hi,

Thanks, the useful part of the info is:

qrc:/QML/VirtualKeyboard.qml:2:1: module "QtQuick.Layouts" is not installed
qrc:/QML/VirtualKeyboard.qml:1:1: module "QtQuick" is not installed
qrc:/QML/VirtualKeyboard.qml:2:1: module "QtQuick.Layouts" is not installed
qrc:/QML/VirtualKeyboard.qml:1:1: module "QtQuick" is not installed

The qml and qtquick part is quite new and probably not added to the
bundleing script. Can you figure out how to add these modules/libraries to
bundle?
O guess they should be usend in CsoundQt 0.9.0 If you examine the osx
CsoundQt installer from sourceforge, perhaps this gives a clue.

Tarmo
13.03.2016 19:08 kirjutas kuupäeval "Johannes Schütt" <
notifications@github.com<mailto:notifications@github.com>>:

**Comment by tarmoj** [comment]
Thanks!
T
14.03.2016 14:34 kirjutas kuupäeval "Johannes Schütt" <
notifications@github.com>:
