### ISSUE TITLE
HTML View for Linux

### ISSUE THREAD

**Issue by gogins** [CsoundQt/CsoundQt#212]
Create a build option for the HTML5 features on Linux. This will require that the Chromium Embedded Framework be installed on Linux.

Then make sure it works!

Someone who looks at this when it is done should be able to do the same for OS X.

**Comment by gogins** [comment]
I have installed the Chromium Embedded Framework on Ubuntu 14.04 and got most things to build with a few fixes, but when linking CsoundQt I still get this error:

g++ -Wl,-O1 -Wl,-rpath,/opt/Qt5.7.0/5.7/gcc_64/lib -o bin/CsoundQt-d-cs6 build/doubles/obj/about.o build/doubles/obj/configdialog.o build/doubles/obj/configlists.o build/doubles/obj/console.o build/doubles/obj/csoundengine.o build/doubles/obj/csoundoptions.o build/doubles/obj/curve.o build/doubles/obj/dockhelp.o build/doubles/obj/documentpage.o build/doubles/obj/documentview.o build/doubles/obj/dotgenerator.o build/doubles/obj/eventsheet.o build/doubles/obj/findreplace.o build/doubles/obj/framewidget.o build/doubles/obj/graphicwindow.o build/doubles/obj/highlighter.o build/doubles/obj/inspector.o build/doubles/obj/keyboardshortcuts.o build/doubles/obj/liveeventcontrol.o build/doubles/obj/liveeventframe.o build/doubles/obj/main.o build/doubles/obj/node.o build/doubles/obj/opentryparser.o build/doubles/obj/options.o build/doubles/obj/qutebutton.o build/doubles/obj/qutecheckbox.o build/doubles/obj/qutecombobox.o build/doubles/obj/quteconsole.o build/doubles/obj/qutecsound.o build/doubles/obj/qutedummy.o build/doubles/obj/qutegraph.o build/doubles/obj/quteknob.o build/doubles/obj/qutemeter.o build/doubles/obj/qutescope.o build/doubles/obj/quteslider.o build/doubles/obj/qutespinbox.o build/doubles/obj/qutetext.o build/doubles/obj/qutewidget.o build/doubles/obj/texteditor.o build/doubles/obj/utilitiesdialog.o build/doubles/obj/widgetlayout.o build/doubles/obj/widgetpanel.o build/doubles/obj/widgetpreset.o build/doubles/obj/qutesheet.o build/doubles/obj/basedocument.o build/doubles/obj/baseview.o build/doubles/obj/appwizard.o build/doubles/obj/appdetailspage.o build/doubles/obj/pluginspage.o build/doubles/obj/additionalfilespage.o build/doubles/obj/scoreeditor.o build/doubles/obj/filebeditor.o build/doubles/obj/midihandler.o build/doubles/obj/midilearndialog.o build/doubles/obj/debugpanel.o build/doubles/obj/livecodeeditor.o build/doubles/obj/newbreakpointdialog.o build/doubles/obj/cefclient.o build/doubles/obj/cefclient_qt.o build/doubles/obj/client_app.o build/doubles/obj/client_app_delegates.o build/doubles/obj/client_binding.o build/doubles/obj/client_handler.o build/doubles/obj/client_handler_qt.o build/doubles/obj/client_renderer.o build/doubles/obj/client_transfer.o build/doubles/obj/message_event.o build/doubles/obj/qcefwebview.o build/doubles/obj/csoundhtmlview.o build/doubles/obj/qrc_application.o build/doubles/obj/qrc_pythonscripts.o build/doubles/obj/qrc_icons.o build/doubles/obj/qrc_qml_resources.o build/doubles/obj/moc_about.o build/doubles/obj/moc_configdialog.o build/doubles/obj/moc_console.o build/doubles/obj/moc_csoundengine.o build/doubles/obj/moc_dockhelp.o build/doubles/obj/moc_documentpage.o build/doubles/obj/moc_documentview.o build/doubles/obj/moc_eventsheet.o build/doubles/obj/moc_findreplace.o build/doubles/obj/moc_framewidget.o build/doubles/obj/moc_graphicwindow.o build/doubles/obj/moc_highlighter.o build/doubles/obj/moc_inspector.o build/doubles/obj/moc_keyboardshortcuts.o build/doubles/obj/moc_liveeventcontrol.o build/doubles/obj/moc_liveeventframe.o build/doubles/obj/moc_qutebutton.o build/doubles/obj/moc_qutecheckbox.o build/doubles/obj/moc_qutecombobox.o build/doubles/obj/moc_quteconsole.o build/doubles/obj/moc_qutecsound.o build/doubles/obj/moc_qutedummy.o build/doubles/obj/moc_qutegraph.o build/doubles/obj/moc_quteknob.o build/doubles/obj/moc_qutemeter.o build/doubles/obj/moc_qutescope.o build/doubles/obj/moc_quteslider.o build/doubles/obj/moc_qutespinbox.o build/doubles/obj/moc_qutetext.o build/doubles/obj/moc_qutewidget.o build/doubles/obj/moc_texteditor.o build/doubles/obj/moc_utilitiesdialog.o build/doubles/obj/moc_widgetlayout.o build/doubles/obj/moc_widgetpanel.o build/doubles/obj/moc_qutesheet.o build/doubles/obj/moc_basedocument.o build/doubles/obj/moc_baseview.o build/doubles/obj/moc_appwizard.o build/doubles/obj/moc_appdetailspage.o build/doubles/obj/moc_pluginspage.o build/doubles/obj/moc_additionalfilespage.o build/doubles/obj/moc_scoreeditor.o build/doubles/obj/moc_filebeditor.o build/doubles/obj/moc_midihandler.o build/doubles/obj/moc_midilearndialog.o build/doubles/obj/moc_debugpanel.o build/doubles/obj/moc_livecodeeditor.o build/doubles/obj/moc_newbreakpointdialog.o build/doubles/obj/moc_qcefwebview.o build/doubles/obj/moc_csoundhtmlview.o   /home/mkg/cef_binary_3.2704.1432.g60b3718_linux64/libcef_dll_wrapper/libcef_dll_wrapper.a /home/mkg/cef_binary_3.2704.1432.g60b3718_linux64/Release/libcef.so -L/usr/local/lib -lcsound64 -lcsnd6 -L/opt/Qt5.7.0/5.7/gcc_64/lib -lQt5PrintSupport -L/usr/lib64 -lQt5QuickWidgets -lQt5Widgets -lQt5Quick -lQt5Gui -lQt5Concurrent -lQt5Qml -lQt5Network -lQt5Xml -lQt5Core -lpthread -lGL 
build/doubles/obj/client_handler.o: In function `ClientHandler::DoClose(CefRefPtr<CefBrowser>)':
client_handler.cpp:(.text+0x14c3): undefined reference to `base::Lock::CheckUnheldAndMark()'
client_handler.cpp:(.text+0x16a2): undefined reference to `base::Lock::AssertAcquired() const'
client_handler.cpp:(.text+0x16af): undefined reference to `base::Lock::CheckHeldAndUnmark()'
build/doubles/obj/client_handler.o: In function `ClientHandler::OnAfterCreated(CefRefPtr<CefBrowser>)':
client_handler.cpp:(.text+0x1b31): undefined reference to `base::Lock::CheckUnheldAndMark()'
client_handler.cpp:(.text+0x1b6d): undefined reference to `base::Lock::AssertAcquired() const'
client_handler.cpp:(.text+0x1b79): undefined reference to `base::Lock::CheckHeldAndUnmark()'
build/doubles/obj/client_handler.o: In function `ClientHandler::ClientHandler()':
client_handler.cpp:(.text+0x2bf4): undefined reference to `base::Lock::Lock()'
client_handler.cpp:(.text+0x2c08): undefined reference to `base::Lock::Lock()'
client_handler.cpp:(.text+0x2d61): undefined reference to `base::Lock::~Lock()'
client_handler.cpp:(.text+0x2d6b): undefined reference to `base::Lock::~Lock()'
build/doubles/obj/client_handler.o: In function `ClientHandler::ClientHandler()':
client_handler.cpp:(.text+0x3009): undefined reference to `base::Lock::Lock()'
client_handler.cpp:(.text+0x3018): undefined reference to `base::Lock::Lock()'
client_handler.cpp:(.text+0x316f): undefined reference to `base::Lock::~Lock()'
client_handler.cpp:(.text+0x3178): undefined reference to `base::Lock::~Lock()'
build/doubles/obj/client_handler.o: In function `ClientHandler::~ClientHandler()':
client_handler.cpp:(.text+0x332f): undefined reference to `base::Lock::~Lock()'
client_handler.cpp:(.text+0x333b): undefined reference to `base::Lock::~Lock()'
build/doubles/obj/client_handler.o: In function `ClientHandler::~ClientHandler()':
client_handler.cpp:(.text+0x355f): undefined reference to `base::Lock::~Lock()'
build/doubles/obj/client_handler.o:client_handler.cpp:(.text+0x356b): more undefined references to `base::Lock::~Lock()' follow
build/doubles/obj/client_handler.o: In function `base::AutoLock::~AutoLock()':
client_handler.cpp:(.text._ZN4base8AutoLockD2Ev[_ZN4base8AutoLockD5Ev]+0x8): undefined reference to `base::Lock::AssertAcquired() const'
client_handler.cpp:(.text._ZN4base8AutoLockD2Ev[_ZN4base8AutoLockD5Ev]+0x13): undefined reference to `base::Lock::CheckHeldAndUnmark()'
collect2: error: ld returned 1 exit status
make: *** [bin/CsoundQt-d-cs6] Error 1

**Comment by gogins** [comment]
Defining NDEBUG fixes the undefined base::Lock and related errors. CsoundQt now builds with HTML5 on Linux.

**Comment by gogins** [comment]
HTML View does not run on Linux with this error:

[0624/122423:ERROR:context.cc(265)] Not implemented reached in bool CefContext::Initialize(const CefMainArgs &, const CefSettings &, CefRefPtr<CefApp>, void *)multi_threaded_message_loop is not supported.

**Comment by gogins** [comment]
Commented out the multi_threaded_message_loop=true except for WIN32. Now it hangs while starting up, no splash screen is visible. This may be because on Linux I #define CEF_USE_SANDBOX, or it may be the process or thread model, or something else.

**Comment by gogins** [comment]
This may be relevant:

// The Chromium sandbox requires that there only be a single thread during
  // initialization. Therefore initialize GTK after CEF.
  gtk_init(&argc, &argv_copy);

**Comment by gogins** [comment]
I may not have set up the sandbox correctly. I am trying again with the latest CEF binary.

**Comment by gogins** [comment]
I copied all CEF resources into csound/bin, built CsoundQt with shadow build in csound/ so we get csound/bin/CsoundQt-d-cs6, and added csound/bin to LD_LIBRARY_PATH. CsoundQt is now running but not displaying the browser. There appears to be an issue with CEF and Qt, see http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=13938&start=20. Or it may be a related issue.

**Comment by tarmoj** [comment]
Michael,
I am working on a Qt-only based solution to use html5 (on QtWebengine). I
will write longer tomorrow, but it looks promising. A small test and demo
application is almost ready, will be happy to discuss it soon.
Tarmo

18.09.2016 22:38 kirjutas kuupäeval "Michael Gogins" <
notifications@github.com>:

**Comment by gogins** [comment]
I will be very happy if you get this to work!

However, I am quite concerned about the interoperability of Csound pieces
using HTML5 and JavaScript across CsoundQt, Csound for Android, csound.node
(which is what runs in NW.js apps), and Csound for PNaCl. These already are
more different than they should be. I would like to request you, if
possible, to support the same Csound API functions in JavaScript that are
currently implemented in client_app.cpp, along with the addition of
compileCsdText. These are similar to the ones in Csound for Android and
csound.node, but not quite the same as Csound for PNaCl.

For more information, please look at my shared spreadsheet at
https://docs.google.com/spreadsheets/d/1C9RqnV5Tlxag5xnMNP1VXO_W-_XirB5BIidASWvhJ9E/edit?usp=drive_web.
The Objective column lists what I think of as a minimal usable JavaScript
API for Csound. Please comment.

Good luck, and I'm looking forward to learning more.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
I'm unassigning myself pending consideration of tarmoj''s work.

**Comment by gogins** [comment]
The WebEngine version now works (at least for csd files) on all platforms, as far as I know. I am closing this issue.

**Comment by gogins** [comment]
The behavior of CsoundQt when playing pieces contained entirely in HTML files is not consistent. It works at times, but not usually. I have improved the behavior a bit by requiring csoundStart() be called for HTML performances just as it is required for performances in other languages. More work is required to get this option of HTML pieces working in CsoundQt to be reliable.

**Comment by gogins** [comment]
I am adding an option: csound.perform(bool perform_indefinitely = false). If true, this option causes the performance thread to run indefinitely, or until it stopped by calling csound.stop().

**Comment by gogins** [comment]
Solved. I had to set up queues for score events and score text to feed them into the csoundPerformKsmps thread. I actually had had the same issue and the same solution in csound.node and forgot about it...

This introduces a dependency on boost except when using Microsoft C++.

**Comment by tarmoj** [comment]
Great that it works! 

This is one of my January plans to see if there is any possibilities to avoid boost or 
other external depencies and use Qt signals and slots (or similar) instead. Maybe 
there is a way to use also the existing CsounEngine class inside CsondHtmlWrapper 
-  would be perhaps more consistent with other code and more easy to maintain. 
Perhaps.

Thanks a lot in every case!
tarmo

**Comment by joachimheintz** [comment]
yes i think avoiding more dependencies is an important factor.
best -
	joachim

**Comment by gogins** [comment]
I'll get rid of boost and protect the queue another way.

By the way, when we get together, are you OK with Mexican food? I know a
quiet place that's not too far from your hotel.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
I have replaced the boost queue with MoodyCamel's ConcurrentQueue, a header
file only library that I have added to the CsoundQt sources in the qthtml
branch. Seems to work fine so there are no additional external dependencies.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by joachimheintz** [comment]
excellent — thanks mike!
	joachim

**Comment by gogins** [comment]
Closing this as we have moved to WebEngine in Qt.
