### ISSUE TITLE
csoundqt has no built-in recording for windows

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#215]
in a workshop i see that for the windows version (0.9.1) the built-in recording does not work.
the error message is:
  "This version of CsoundQt was not built with recording support"

**Comment by gogins** [comment]
I have fixed the build configuration for mingw64. It now is:

CONFIG *= html5
CONFIG *= perfThread_build
CONFIG *= rtmidi
CONFIG *= record_support
CONFIG *= debugger

**Comment by joachimheintz** [comment]
thanks mike; looking forward to the next release then.

**Comment by gogins** [comment]
I also had to re-arrange things in qcs.pro. But it works now.
