### ISSUE TITLE
self-completion in live event sheet

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#220]
it would be good to have the self-completion of instrument names in the live event sheet.

also, i would prefer if i could close the LE Controller and just leave the LE Sheet in use open.

**Comment by tarmoj** [comment]
'Keep Sheets in use opn' solved. Now the behaviour is that "Live events" toggle button opens LE controller and any active LE sheets; Close on LE controller or unchecking the toggle button closes only the controller window. There is now also a "Close All" button on LE Controller.

Not going to implement word completion for instrument names this time though... (much work for small convenience)
