### ISSUE TITLE
[0.9.3-beta] "Run in Term" leaves hidden command-line terminals open (Windows 7&10, x64)

### ISSUE THREAD

**Issue by n0holmes** [CsoundQt/CsoundQt#225]
This happens on both Windows 7 and Windows 10 for me (both 64-bit versions).

When I hit the "Run in Term" button for any CSD, no terminal/console appears; but I do hear audio, and I can see a csound.exe process in the task manager; therefore, Csound appears to be running correctly. Unfortunately, even after the score reaches its end and csound.exe terminates, the hidden "cmd.exe" process for the terminal stays open indefinitely, and can only be closed by killing it through the task manager.

So, of course, using "Run in Term" multiple times results in multiple invisible cmd.exe processes hanging around in memory, if you aren't paying attention!

Actually, on that topic, _is_ the command-line console window supposed to be hidden in the first place? It didn't used to be for me, with previous versions of CsoundQT. As it is, there doesn't appear to be obvious way to halt playback prematurely anymore, since I can't ctrl-C in the console now.

**Comment by tarmoj** [comment]
Thanks for the repory!
I will try to ckeck ot when I get to a Windows machine.
Tarmo

05.01.2017 15:18 kirjutas kuupäeval "n0holmes" <notifications@github.com>:

**Comment by tarmoj** [comment]
Hi, after very long break I got to it and can confirm -  also for me it works this way with the installed CsoundQt version. But curiously, when I build CsoundQt myself (with msys2 and mingw64) -  the terminal windows are shown as expected. So it can problem with the MS Visual Studio build that is normally shipped with the installer.  We must check with Michael before next release comes out.

**Comment by gogins** [comment]
I have fixed this by using std::system to run the existing terminal command line in a std::thread.
