### ISSUE TITLE
Improve the display of waveforms in graph widget [enhancement]

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#233]
I'm not referring to the f-tables, but when the graph is used in conjunction with `display` opcode, the waveform doesn't appear to render properly.

Maybe I'm using it incorrectly, but to scope arbitrary signals (i.e. not standard outputs), the only way I've found is to use `display` and graph. Is this the case?

thanks

p.s. I couldn't add the enhancement label for some reason!

**Comment by tarmoj** [comment]
Hi, I tried with the display example from manual but I am not sure how it should look actually. Can you provide an example or perhaps some screenshots or hints what do compare it to?

**Comment by boonier** [comment]
![image](https://cloud.githubusercontent.com/assets/6206789/25154450/a2be0c34-2488-11e7-9126-ba7924b4c42f.png)

![image](https://cloud.githubusercontent.com/assets/6206789/25154499/ce74905a-2488-11e7-9ce1-2c1d71b9d84d.png)

I'd imagine the wave to not be filled (my preference) but mainly there appears to be a drawing problem with the horizontal line going across it, like some DC offset. Should the peaks of the sine wave be reaching the upper/lower limits of the widget at amplitude 1?

Also it seems quite expensive to redraw this window on my machine.

CHeers!

**Comment by boonier** [comment]
Hi @tarmoj don't suppose there has been any development on this?

Also would it be better to use the oscilloscope for the display opcode? or using the chnset name. Perhaps I am misunderstanding the internal workings

Thanks

**Comment by tarmoj** [comment]
Thanks for reminding!

I had a look at the code and look back then but everything seemed normal to
me on Linux then, but I will have closer look.
Probably not nearest future, but CsoundQt 0.9.5 aiming release in November
could have it solved. I will keep you posted.

Tarmo

28.09.2017 15:07 kirjutas kuupäeval "Si Mills" <notifications@github.com>:

**Comment by boonier** [comment]
Great thanks!

**Comment by boonier** [comment]
@tarmoj just out of interest, how do you quickly scope signals, say a- or k-rate signals to see what they are doing? Do you pipe them to a spare channel on the oscilloscope widget?
thanks

**Comment by tarmoj** [comment]
Yes, I would use the scope widget, see Example->WIdgets->Scope widget. Not done for k-singal nor experimented with named channel of Scope widget ( Andrés Cabrera is the author of the software)  but since you are on it -  would you care to explore it and write a small wiki article to

https://github.com/CsoundQt/CsoundQt/wiki
or
http://csoundqt.github.io/pages/widgets.html


Thanks!
tarmo

**Comment by Velthuijs** [comment]
@boonier 
My apologies for asking this offtopic thing, but how did you get CsoundQt to have such a tight resolution on your Mac?

Sincerely

**Comment by boonier** [comment]
@Velthuijs I believe that may be a little app called Retinizr on macOS I use. Essentially it just upscales the font resolution by changing the app plist I think, but images remain the same. Not too many images to upscale so it wouldn’t be too much of a job to make them nice and crisp also.

**Comment by Velthuijs** [comment]
@Si Mills<mailto:notifications@github.com>

Thanks a lot! :)

**Comment by boonier** [comment]
@Velthuijs no probs :)

**Comment by gesellkammer** [comment]
Fixed in branch "newlook"
