### ISSUE TITLE
Seg fault crashes CsoundQT with Macro

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#235]
Hi there

Not sure if this is a csound core issue, or due to CsoundQT, but I thought I'd post here..

Just installed latest CSQT 0.9.4 and CS 6.09 on OSX 10.10.5 (from 6.08)

When running the define_args.csd example (from the document Orchestra > Macros > $NAME, in terminal from CsoundQT, otherwise it
crashes the ide) I'm getting a seg fault:

```
defining argument `OSCMACRO``VOLUME as...#5000#
defining argument `OSCMACRO``FREQ as...#440#
defining argument `OSCMACRO``TABLE
csound command: Segmentation fault
```

I first noticed this when my own macros didn't work, so I tried the example
and sure enough, it failed too.

Is this something you can replicate? is there some weird misread character because afaics it all looks perfectly fine.

thanks

**Comment by joachimheintz** [comment]
hi -

i would like to test this on linux.  where is the define_args.csd?

best -
	joachim

**Comment by boonier** [comment]
It's Manual > Syntax of the Orchestra > Macros > $NAME

2nd example

**Comment by tarmoj** [comment]
Hi, yes, the same here.

When you run Csound in terminal and see "Segmentation fault" there it means, it is a problem in Csound. Would you care to write to the the mailing list and/or file an issue? I close this here.

https://github.com/csound/csound/issues

Thank you!

tarmo

**Comment by boonier** [comment]
Sure no probs 😉
