### ISSUE TITLE
CsoundQT crashes on Run

### ISSUE THREAD

**Issue by tmavuk** [CsoundQt/CsoundQt#238]
Hi, 

I'm trying to run Csound 6.08.1 on my Windows 10 but whenever I try to Run CsoundQT crashes. Same thing happens when I try to change the I/O devices. As soon as I hit either of the little boxes with "..." I get a crash. The same issue happens with 6.08.0 and 6.07 as well. The interesting part is when I Run in Term QT runs with no problems. 

I tried 6.09.0 but with that release I get an error saying python27.dll is missing and I can't even get it to open.

I'm a newbie, I'd appreciate it if someone can help or guide me through this. Thank you.

Best,

Turgut

**Comment by tarmoj** [comment]
Hi,

I am very sorry to hear!

It seems like some kind of libary conflict problem, CsoundQt 0.9.3  from 
Csound 6.08 should work, the one in 6.09 installer lacks some dll files, this 
is being fixed and I belive Michael should publish the ne installer very soon.

I guess the best bet is to wait for that, or you can try do dowload a test 
build from: https://github.com/CsoundQt/CsoundQt/releases/tag/0.9.4

Just unzip it and run CsoundQt-d-cs6.exe from there.  It is a test build, but 
maybe works.

tarmo

**Comment by gogins** [comment]
I have fixed (I think) the problem of the missing DLLs. The Csound
developers are waiting on a few other issues. It should be published soon.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tmavuk** [comment]
Thank you for your responses Mika and Tarmo. Everything is working fine with the release in Tarmo's link.

**Comment by teepsos** [comment]
The same thing with csound 6.12.0... anyone ?
