### ISSUE TITLE
Add group widget and or ability to make visible/hidden

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#243]
Not sure if this is already possible in the api, but it would be useful for making tabs or pages of widgets.

**Comment by tarmoj** [comment]
Hi, there are different things in your title and  comment:
group widget -  can you explain what do you mean by that?
make widgets visible/hidden - you can do that if you use CsoundQt built with PythonQt support (like  OSX default binary) -  try
```
q.setWidgetProperty("channelOfTheWidget", "QCS_visible",0) 
q.setWidgetProperty("channelOfTheWidget", "QCS_visible",1)

```
See more about the q object: https://csoundqt.github.io/pages/python.html


Implementing tabs and several widget layouts can be complex in the code, but I keep it in mind.

Once again, using PythonQt you can create your independent interface using all the goodies if Qt like TabView etc etc -  of course it requires some python skills from users side...

See "Creating Own GUIs with PythonQt" on the same page linked above..

**Comment by boonier** [comment]
Ahh good to know thanks. I should read the docs a bit more thoroughly. Looks like it's all there for the making. Sorry yeah title is a bit confusing. I was thinking of a container widget but sounds like TabView is the way forward.

cheers

**Comment by tarmoj** [comment]
Feel free always  to ask any  questions in the CsoundQt mailing list - it is always iteresting to others as well and please share your solution when you get it done!
tarmo
