### ISSUE TITLE
CsoundQt 0.9.4 crashes when opening in Mac OS X Lion 10.7.5

### ISSUE THREAD

**Issue by transmogrify** [CsoundQt/CsoundQt#244]
Csound v6.09.1 package downloaded from here: http://csound.github.io/download.html
The Package, along with CsoundLib64.framework, includes CsoundQT 0.9.4 
When opening CsoundQt 0.9.4, the application crashes. 

Below is the report: 

Process:         launchd [571]
Path:            /Applications/CsoundQt-d-py-cs6.app/Contents/MacOS/CsoundQt-d-py-cs6
Identifier:      launchd
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [136]

Date/Time:       2017-08-22 13:21:28.843 +0100
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          13345104 sec
Crashes Since Last Report:           -13
Per-App Crashes Since Last Report:   13
Anonymous UUID:                      A551E924-8D15-417B-BF5A-3C88006F2685

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 2

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1151
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro8,2, BootROM MBP81.0047.B27, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 1.69f3
Graphics: AMD Radeon HD 6750M, AMD Radeon HD 6750M, PCIe, 512 MB
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In, 512 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1333 MHz, 0x859B, 0x43543130323436344246313333392E433136
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1333 MHz, 0x859B, 0x43543130323436344246313333392E433136
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (5.106.198.19.22)
Bluetooth: Version 4.0.8f17, 2 service, 18 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: ST9500325ASG, 500.11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS23NR
USB Device: hub_device, 0x0424  (SMSC), 0x2513, 0xfa100000 / 3
USB Device: USB 2.0 Hub, 0x1a40  (TERMINUS TECHNOLOGY INC.), 0x0101, 0xfa130000 / 6
USB Device: USB Optical Mouse, 0x192f  (Avago Technologies, Pte.), 0x0916, 0xfa133000 / 8
USB Device: Hard Drive, 0x054c  (Sony Corporation), 0x05bf, 0xfa131000 / 9
USB Device: BRCM2070 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0xfa110000 / 5
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x821a, 0xfa113000 / 7
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0253, 0xfa120000 / 4
USB Device: FaceTime HD Camera (Built-in), apple_vendor_id, 0x8509, 0xfa200000 / 2
USB Device: hub_device, 0x0424  (SMSC), 0x2513, 0xfd100000 / 2
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0xfd110000 / 3

**Comment by tarmoj** [comment]
Thanks for the report and sorry to hear about the crash!

Unfortunately it does not provide any helping information so I could guess 
what is the reason...

I am afraid there is some mismatch in the binary code (built with toolchain on 
OSX 10.12.4) and your system -  10.7.5 -  that is much older. As much I 
understand Apple is not taking much care to make changes backward 
compatible...

I guess your best bet is to build CsoundQt yourself -  it is not that hard, 
see
https://github.com/CsoundQt/CsoundQt/wiki/Building-CsoundQt-for-OSX-with-QtCreator (somewhat outdated)
 or stick to CsoundQt 0.9.3 if that works for you. You can download it 
separately from
https://github.com/CsoundQt/CsoundQt/releases/tag/0.9.3

Hope it helps!https://github.com/CsoundQt/CsoundQt/releases/tag/0.9.3
tarmo
