### ISSUE TITLE
Enhancement: Add output limiter

### ISSUE THREAD

**Issue by armandogonzalezsosto** [CsoundQt/CsoundQt#245]
Greetings, 

My name is Armando Gonzalez Sosto and I'm the tutor for Dr. Boulanger's programming classes at Berklee College of Music. 

I'm unsure if a similar solution to this problem already exists, but I still wanted to proceed with the suggestion.

I'd like to suggest the addition of an audio limiter that's built into the output of Csound QT that can be enabled and disabled from the settings menu.

For many beginning Csound students, dealing with amplitude tends to be an area of confusion. To prevent users from harming their hearing and/or equipment during experimentation, it would be useful to have a built-in brickwall limiter that prevents dangerous levels from coming through. I also believe this would be useful not only for beginners, but also for experienced users who are working with more volatile instruments. 

To maintain consistency with the legacy of Csound, I believe it should be an additional option that users can simply disable if they're not interested in using it. However, for interested users, this could be a very useful enhancement. 

Thank you very much, 

Armando Gonzalez Sosto

**Comment by tarmoj** [comment]
Thank you!

I think it is a very sane and necessary proposal. I remember discussion about 
something similar once in Csound mailing list.

So far CsoundQt interferes to Csound audio production in no way but maybe this 
case could be an exception.

I will ask from the Csound developers first if it should be perhaps implemented 
in the core Csound but if not, I will work on it to realize it in CsoundQt -as 
time permits.

greetings,
tarmo
