### ISSUE TITLE
Tab close icon missing

### ISSUE THREAD

**Issue by armandogonzalezsosto** [CsoundQt/CsoundQt#246]
Hello, 

I'm reporting an issue I've been noticing lately. 

The "close tab" symbol is missing in QT. The functionality is still there - tabs get closed when the left side of the tab gets clicked, and if you hover over it you'll still see a "close tab" suggestion, but the X itself is missing. This can lead to some confusion.

I'm running QT on macOS Sierra (10.12.5) on a MacBook Pro  (Retina, 13-inch, Late 2013). I've seen this issue happening on other people's computers as well, but I can't provide specs for their machines other than they were post 10.10 Mac OS computers.

Hopefully the screen shots will be useful in explaining the situation.

Thanks! 

Armando Gonzalez Sosto

<img width="177" alt="screen shot 2017-10-01 at 6 02 23 pm" src="https://user-images.githubusercontent.com/29617987/31059587-b58e73e0-a6d2-11e7-88b3-1657a15da177.png">
 

<img width="177" alt="screen shot 2017-10-01 at 5 58 08 pm" src="https://user-images.githubusercontent.com/29617987/31059552-22583a2a-a6d2-11e7-8126-6d8d2951acd3.png">

**Comment by tarmoj** [comment]
Thanks for the report! I can confirm it on MaxOs, did not find the cause yet. Do you remember it was OK with some older version?

Tarmo

**Comment by armandogonzalezsosto** [comment]
Sure! Thanks for the reply! 

I have been using QT for about a year or so, and the X used to be there. Honestly, I'm not sure exactly when it disappeared, but I'm inclined to say it's a pretty recent issue. I'm sorry, but I can't really confirm with precision as to when it started to disappear.

**Comment by tarmoj** [comment]
Hi,

seems that it is caused by Qt 5.9.0 on MacOS that is used to build the last 
version (works on other platform though) -  I will check maybe there is an 
update or there is other way to solve. It is not a crucial thing but I would 
definitely would like to get it right.

Greetings,
tarmo

**Comment by tarmoj** [comment]
I have investigated and it is a small regression in Qt 5.9.0 indeed
https://bugreports.qt.io/browse/QTBUG-61092
v5.9.1 did not fix the problem, it will be all right again in 5.10 (the snaphot is already out but too early to use that for release build).
Qt 5.8.0 had other stability issues on some older OSX systems, so we cannot go back to 5.8. 
For now it stays just an "known issue" and we must live with that for a while.
Thanks for reporting again!

tarmo

**Comment by tarmoj** [comment]
In fact I think I found a workaround -  I disabled stylesheet for MacOS (there were not so many definitions afer all) and the close buttons are back. I could not see that anything else had changed.

Please see if it works for you (and if I made the package right):
http://tarmo.uuu.ee/varia/failid/cs/CsoundQt/CsoundQt-0.9.4.2.dmg

tarmo

**Comment by armandogonzalezsosto** [comment]
It worked! The X is back, and everything's working fine on my computer.

Thanks for everything!

-Armando

**Comment by armandogonzalezsosto** [comment]
Screenshot: 

<img width="198" alt="screen shot 2017-10-05 at 4 19 26 pm" src="https://user-images.githubusercontent.com/29617987/31250652-7e8193b8-a9e9-11e7-8931-3a36a3f88d20.png">
