### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Reaper10** [CsoundQt/CsoundQt#250]
This mite a stupid question but i just found your software ,i wanted to make syths. Can you save a synth as lv2, vst or as a standalone software?

**Comment by tarmoj** [comment]
Hi, Cabbage is a great software for that (create plugins from Csound).
http://cabbageaudio.com/

You can start working and making the prototype in CsoundQt -  there is option to turn most of your CsoundQt widgets into Cabbage format (Edit->Update/Insert CabbageText)

tarmo
