### ISSUE TITLE
Cannot copy&paste from the CsoundQt

### ISSUE THREAD

**Issue by CFSO6459** [CsoundQt/CsoundQt#253]
For some reason, the cut/copy from the CsoundQt seems unable to write into system's clipboard. No matter I use keyboard shortcut (Ctrl+X or Ctrl+C) or use right click menu.
i.e. If I cut some code from CsoundQt, the selected code is deleted, but I will not be able to paste them.

Is this designed to be so? Or this is a bug?

Thank you for replying.

**Comment by tarmoj** [comment]
Hi,
this is fixed in CsoundQt 0.9.5. Please report if still appears to be problem.
tarmo
