### ISSUE TITLE
Low resolution interface on MacOs with Retina display

### ISSUE THREAD

**Issue by Velthuijs** [CsoundQt/CsoundQt#255]
CsoundQt opens up in a low resolution, making the interface very pixely. Unfortunately it's not possible to change the low resolution option in 'get info' as it's greyed out. I think this has something to do with the Retina display. I'm running Os 10.13.2 and have tried older builds of CsoundQt without any difference.
<img width="1440" alt="screen shot 2017-12-30 at 15 09 12" src="https://user-images.githubusercontent.com/34962179/34454817-89d8d7da-ed73-11e7-8098-a2aa7199a153.png">

**Comment by stefkeB** [comment]
Check [http://retinizer.mikelpr.com](http://retinizer.mikelpr.com) for a small utility which can enforce this with some applications. It worked for me for CSoundQt.

**Comment by tarmoj** [comment]
Hi would you try this version:
https://github.com/CsoundQt/CsoundQt/releases/tag/0.9.6-beta3
It should enable support for HDPI screens.
tarmo
