### ISSUE TITLE
Packaging for Arch Linux

### ISSUE THREAD

**Issue by dvzrv** [CsoundQt/CsoundQt#258]
Hi!

I'm currently moving csound and some dependencies to the [community] repository in Arch Linux.
Packaging csound and its docs went okay so far ([with minor glitches](https://github.com/csound/csound/issues/907#issuecomment-360790117)).

As another step I'd like to add csoundqt as a package ([already available in the AUR](https://aur.archlinux.org/packages/csoundqt/) as an optdepends to csound).
However, I have to say - and excuse my wording - it is horrible to package in every way.

* There is no proper make system in place moving files to the appropriate places.
* It is seemingly impossible to use system-wide installed dependencies (e.g. [rtmidi](https://www.archlinux.org/packages/?q=rtmidi), [pythonqt](https://aur.archlinux.org/packages/pythonqt/)). Local sources should be included in this repository!
* It is unclear judging from the [BUILDING.md](https://github.com/CsoundQt/CsoundQt/blob/develop/BUILDING.md), what could be a system-wide dependency and what needs to be copied locally... This should be more clearly specified.
* Some scripts take care of some moving of some files (e.g. mime-types) ... but not all...
* Paths for scripts and examples are not easily settable (only by sed'ing source code!)

This creates an environment, that makes it very painful to package this software.
I hereby suggest to use a make system (or extend the existing one massively), that is taking care of the above things, externalizes variables more comfortably and more easily integrates dependencies (either as a system-wide install or as a local source by e.g. using a submodule), as otherwise packagers spent half a day patching and trying to understand how to do this... (and eventually end up not providing this software as a package, because they give up).

However, I didn't give up and [packaged csoundqt](https://www.archlinux.org/packages/?q=csoundqt). If you want to get a grasp on why it's so painful, have a look at the [build script](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/csoundqt).

**Comment by tarmoj** [comment]
Hi,

Thanks a lot for working on  the package! I have no knowledge nor
experience on creating Linux packages. Felipe Sateler preapares (or has
prepared) debian pacakages and has reported it was quite easy for him. One
trick that perhaps you did not know -  if you run (sudo) make install in
build directory, it should eveything necessary (binary, creates link,
examples, creates mime types and desktop icon). Can you find Felipes
contacts from the list or would you like me to connect you to share
experience?

Anyway, this was a quick answer, I am definitely willing to work on it to
make the packaging easier. Can you give even more exact suggestions what do
you need to package easier? The ready-made installers on the main distros
are very welcome!

Let's be in touch!

tarmo

2018-01-26 11:28 GMT-05:00 David Runge <notifications@github.com>:

**Comment by fsateler** [comment]
@dvzrv you might want to take inspiration from the debian build scripts:

https://sources.debian.org/src/csoundqt/0.9.4-1/debian/rules/
https://sources.debian.org/src/csoundqt/0.9.4-1/debian/patches/
https://sources.debian.org/src/csoundqt/0.9.4-1/debian/ for all files

CsoundQT uses qmake as its build system, which although not my favorite, does allow overriding as options many things.

It appears to me you are reinventing the make install target, which does support DESTDIR, and installs many things for you.

I don't build PythonQt support, because last time I checked it was not available in debian (and I won't commit to maintaining it). This might have changed though, I haven't checked

**Comment by dvzrv** [comment]
@fsateler Thanks for the insight!
I updated my [build script](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/csoundqt) accordingly, but still had to fumble a little with the additional use of SHARE_DIR, and INSTALL_DIR (which was not so straight forward).
This looks much cleaner now.
Initially I assumed the make install was broken, because my packaging predecessor had abandoned it for a manual install. 
@tarmoj: Too much packaging that day. My apologies, if that came across as rude!

However, there are still some minor issues to tackle, I believe. If you have a look at the `prepare()` function in my PKGBUILD, you'll see quite a few modifications:

* the desktop file should be chmod 644 (and probably lowercase)
* it's usually good style to name the icon the same way as the application (i.e. `csoundqt.svg`)
* the application icon should go to `$SHARE_DIR/icons/hicolor/scalable/apps`, if using hicolor-icon-theme
* the example location directory (at least according to Arch's packaging standards) should be below `/usr/share/csoundqt/Examples`, because the package is called csoundqt. Currently the examples are installed to `/usr/share/qutecsound/Examples` though and this is also reflected in the source code!
* the predefined location for the csound reference manual seems to be `/usr/share/doc/csound-doc/html`. However, I might package the doc alongside csound, in which case it will be below `/usr/share/doc/csound/html`. An easier way to set this would be great!

Additionally: Would it be possible to use the rtmidi libraries, instead of in-tree sources?

**Comment by fsateler** [comment]
> Additionally: Would it be possible to use the rtmidi libraries, instead of in-tree sources?

+1 to this. I think I have rtmidi disabled in the debian package due to this.

**Comment by joachimheintz** [comment]
+1 (so immensely important for the widgets-midi communication)

**Comment by gogins** [comment]
You can simply add a copy of RtMidi sources to the CsoundQt sources. Might
save a lot of trouble. I don't think this code changes that often.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tarmoj** [comment]
Hi,

Thanks a lot for the suggestions, I will get closer to it when I can take
more time to CsoundQt (hopefully in coming weeks).

For RtMidi, I think the reason why Andrés preferred to have the source code
downloaded, easliy found and built, is that rtmidi does not exist as a
prebuilt library on many systems (including Windows, MacOS and mny Linux
distros), thus introducing another external dependency would be a problem
on those systems.  Also downloading the source and building it together
wiht CsoundQt is quite easy, as also Michael said, that I find it quite
reasonable, too.

Nevertheless, if this is the reason that debian package is without rtmidi
support, I will try to find a way how the build system could choose between
those two options whether  the library of rtmidi is found  or not. Should
be doable in the qmake project files.

PythonQt is more problematic -  it is sometimes tricky to build and often
many steps behind the Qt development, this is probably the reason why it is
not available as a package on many systems. I personally like and use
PythonQt possibilities a lot and if there were a way to include it also in
prebuilt pacakges, would be great. Let's think about it.

When I get to work on it, I will definitely ask about your about different
matters.

greetings,
tarmo

2018-01-30 16:49 GMT-05:00 Michael Gogins <notifications@github.com>:

**Comment by dvzrv** [comment]
There's one other thing, that I forgot about in my last comment:

During make (in the `build()` function) I explicitely have to prefix `SHARE_DIR` and `INSTALL_DIR` with the `$pkgdir` variable (that's the location, where the package contents get put together in a overlay filesystem).
It should only be something like `/usr/share` and `/usr` (respectively).
However, using `DESTDIR` for make install (in the `package()` function) should be enough!

Looking at it, I'd opt for complety removing the requirement for `SHARE_DIR` and `INSTALL_DIR` and implicating that from `DESTDIR`!

**Comment by tarmoj** [comment]
Hi,

I finally got back to works with CsoundQt again and according to your several suggestions, David I made several improvements, hopefully they help to make packageing (and maybe building) easier:

- renamed CsoundQt.desktop to csoundqt.desktop
- use desktop-file-install to install the desktop file (install sections in  qcs.pro) when you do make install. That sets also the csoundqt.desktop permissions to 644
- fixed creating link `csounqt` to correct binary (so in install dir  csoundqt -> CsoundQt->CsoundQt-d-html-cs6-debug or whatever is installed) -  this enables to have several versions installed, just change the link to use correct one.
- icons is installed now to: `$SHARE_DIR/icons/hicolor/scalable/apps`, renamed icon to _csoundqt.svg_ ( or copied to other name, too)
- changed  installed examples dir from_ qutecsound_ to _csoundqt_, fixed also code for checking that in the code. That is more logical, indeed.
- added conditions to find rtmidi from system - it checks if _/usr/include/rtmidi_ or _/usr/local/include/rtmidi_ exist (ie if it is installed by the user or package management -  both rtmidi and rtmidi-dev pacakges must be installed in the latte case!) sets config option `system_rtmidi` that omits compiling rtmidi from sources and sets correct include path and linked library.

What concerns  `SHARE_DIR` and `INSTALL_DIR` -  they are useful and give actually more flexibility -  you can use them with qmake to install your binary and shared data wherever you need. They  cannot be replaced with `DESTDIR` since in qmake that is the folder wher Makefile is generated, not the installation path of `make install`. So, if you want to install CsoundQt in your home folder use just

```
qmake qcs.pro INSTALL_DIR=~ SHARE_DIR=~/.local/share
```

I believe you can use it easily also in your pacakging scripts.

Commited these changes to develop branch.

David, Felipe, please try it out and let know if things are clearer and work as expected!

Thanks!
tarmo

**Comment by tarmoj** [comment]
And, David:

You said that you might package Csound docs to _/usr/share/doc/csound/html_ . If it is so, please let me know and I will add this to possible search path in the code.

t

**Comment by dvzrv** [comment]
@tarmoj thanks so much, this has improved *a lot*!

I'm currently building 0.9.6-rc1 and only run into the following issue (a typo), when using system rtmidi:
[A wrong path is provided to the build system](https://github.com/CsoundQt/CsoundQt/blob/develop/config.pri#L131-L135). It should read `/usr/include/rtmidi` there.

**Comment by dvzrv** [comment]
Another problem, that I'm seeing: The final executable is symlinked using an absolute path:

```
-rwxr-xr-x root/root   6416384 2019-07-07 10:23 usr/bin/CsoundQt-d-cs6
lrwxrwxrwx root/root         0 2019-07-07 10:23 usr/bin/csoundqt -> /build/csoundqt/pkg/csoundqt/usr/bin/CsoundQt-d-cs6
```

Whereas before, this was done relatively:

```
-rwxr-xr-x 1 root root    5.7M Jun  3  2018 CsoundQt-d-cs6
lrwxrwxrwx 1 root root      14 Jun  3  2018 csoundqt -> CsoundQt-d-cs6
```

As you can imagine, the former doesn't work, as it is linking to a long gone build directory, that is only available during package building.

Maybe it would be a good idea to drop the symlink altogether, and only provide `csoundqt` as the executable? Is there any reason, not to do so?

**Comment by hlolli** [comment]
There were some rtmidi path issues I faced when making nix derivation, I guess you could use the same patch on archlinux as I used here https://github.com/NixOS/nixpkgs/blob/db66867b9de99eacafe71558fe1cf9a1c41e12ab/pkgs/applications/audio/csound/csound-qt/default.nix

**Comment by tarmoj** [comment]
Hi, David!

Thanks for feedback and the notes!

I corrected the lines in config.pri and changed the target install rule to:

target.path = $$INSTALL_DIR/bin
target.files = $$OUT_PWD/$$DESTDIR/$$TARGET
target.commands = ln -sf $$target.path/$$TARGET $$target.path/csoundqt

I would stick to the link -  if you build yourself there might be several
different binaries (one with, one without pythonqt for example) and I think
it is good to have different name for those where you can read out what is
include.

My Makefile reads now:

install_target: first FORCE
@test -d $(INSTALL_ROOT)/usr/local/bin || mkdir -p
$(INSTALL_ROOT)/usr/local/bin
ln -sf /usr/local/bin/CsoundQt-d-html-cs6 /usr/local/bin/csoundqt
-$(QINSTALL_PROGRAM)
/home/tarmo/src/qutecsound/build-qcs-Qt5_desktop-Release/bin/CsoundQt-d-html-cs6
$(INSTALL_ROOT)/usr/local/bin/CsoundQt-d-html-cs6

Look correct to me, does it work on your system?

Thanks!
tarmo


Kontakt David Runge (<notifications@github.com>) kirjutas kuupäeval P, 7.
juuli 2019 kell 11:56:

**Comment by dvzrv** [comment]
@hlolli thanks! [I chose to just sed those wrong paths](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/csoundqt#n25).

@tarmoj you could just go for `target.commands = ln -sf $$TARGET $$target.path/csoundqt` to achieve a simple relative `csoundqt -> CsoundQt-d-cs6` symlink ([that's what I'm using locally](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/csoundqt#n42)).

**Comment by tarmoj** [comment]
Hi,

I wrote it this way, this creates relative link:

target.commands = cd $$INSTALL_DIR/bin; ln -sf $$TARGET csoundqt

Does this achieve what you need?

tarmo

Kontakt David Runge (<notifications@github.com>) kirjutas kuupäeval P, 7.
juuli 2019 kell 14:35:

**Comment by dvzrv** [comment]
On 2019-07-07 06:12:36 (-0700), Tarmo Johannes wrote:
> I wrote it this way, this creates relative link:
> 
> target.commands = cd $$INSTALL_DIR/bin; ln -sf $$TARGET csoundqt

Yes, this also works! Thanks! :)

**Comment by tarmoj** [comment]
Hi,

I made some changes to qcs.pro to try to make possible building and packaging on FreeBSD.

Would you please try if it did not break anything for you?

Thanks!
tarmo
