### ISSUE TITLE
Examples contain errors

### ISSUE THREAD

**Issue by jpffitch** [CsoundQt/CsoundQt#260]
04A13_hsboscil.csd

Definitely has a extraneous \ in the long line 15

03B01_Variable_types.csd  is broken with newline in a "..." string
twice

Where is the amdbisonic include files?
#include "ambisonics2D_udos.txt"
#include "ambisonics_utilities.txt" ;opcodes Absorb and Doppler

**Comment by joachimheintz** [comment]
thanks; i fixed these and others.
