### ISSUE TITLE
Strange re-evaluate issue with metro

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#262]
I don't know if this is a more general Csound issue or Csound QT, but metro() doesn't respond to changes when I do re-evaluate section:

instr 1
  kcnt init 0
  if metro(12) == 1 then ;changing the metro rate has not effect
    printks2 "ping: %d\n", kcnt
    kcnt += 1
  endif
endin

whereas if I create a global var and use that to see the metro rate value, it works fine:

gkrate init 2 ; changing this and re-evaluating selection works
instr 2
	kcnt init 0
	if metro:k(gkrate) == 1 then
		printks2 "ping: %d\n", kcnt
		kcnt += 1
	endif
endin

Is this fundamental to the way metro works when instantiated?

**Comment by tarmoj** [comment]
this is definitely a CsoundQt issue. Also I believe it is all fine at the Csound side as your second example works. Form first example it is not clear how you start your instrument. Do you know that you cannot recompile already running istruments (or there is no change), the change takes into effect when you next time start the instrument again. Using a global value this way is best solution.

**Comment by tarmoj** [comment]
I meant definitely NOT a CsoundQt issue...

**Comment by boonier** [comment]
I started the inst from the score, i 1 0 1000

ah ok good to know - that aligns with other times that I've had this issue, when actually it makes sense that you cannot change a running instrument, without stopping it and restarting, or using a global variable. 

thanks for clarifying
