### ISSUE TITLE
String channels

### ISSUE THREAD

**Issue by Djack13** [CsoundQt/CsoundQt#263]
Hello,

When using string channels and chnset opcodes, the last letter of the string is not displayed.

chn_S "text", 2

instr 1
	chnset  "", "text"  ----> print garbage data
	turnoff
endin

instr 2
	chnset  "Hello", "text"  ----> print Hell
	turnoff
endin
</CsInstruments>
<CsScore>

I am using CsoundQt 0.9.5 and csound 6.11 compiled on linux Mint 18.3

[String_Channels.csd.txt](https://github.com/CsoundQt/CsoundQt/files/1958946/String_Channels.csd.txt)

**Comment by joachimheintz** [comment]
i get the same result as you.

**Comment by tarmoj** [comment]
Hi,

Thanks a lot for the report! 

I can reproduce now, too. 

First I tried with Csound 6.10, that I had in the machine -  it worked correctly, then rebuilt 
Csound to latest from Csound-git develop branch, and after restarting CsoundQt I get 
similar result. 

Strangely running chnset and chnget in pairs in terminal works correctly.

like

chnset  "Hello", "text"  ;----> print Hell
S1 chnget "text"
printf "Hello: %s\n", 1, S1 ; prints "Hello: Hello" in terminal


I will  invetigate.

tarmo

**Comment by tarmoj** [comment]
It was a small bug in Csound code. I reported it to Csound developers and now it is fixed (Csound git develop branch 30.04).

**Comment by Djack13** [comment]
Tank you :)
