### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by vncntmchlk** [CsoundQt/CsoundQt#264]
When i run this code in CsoundQt:

```
schedule 1,0,-1 
instr 1 
ain noise 0.1,0
abut buthp ain*0.1,1000
endin
```

i get this error message:

> error:  Unable to find opcode entry for 'buthp' with matching argument types:
Found: a buthp cc
       abut buthp 0.1 ...

without multplying ain by 0.1 it works fine, also if i change if back to multiplying ain by 0.1 after it worked once, the bug no longer appears. Running csound in terminal also works without the error.

CsoundQt Version 0.9.6-beta2
Csound version 6.12 beta
On Ubuntu 18.04.

I am getting this kind of error on multiple opcodes when i do multiplication on an input. Can anyone replicate this error? I can't find the cause...

**Comment by hlolli** [comment]
Strange, I don't get this, what commit of Csound are you using? There was some major git history cleanup recently and many bugs introduced that have been fixed lately.

**Comment by hlolli** [comment]
Ok when I look at it, it could be a CsoundQt bug, can you run this file from the terminal and tell if you get the same result?

**Comment by vncntmchlk** [comment]
It seems to be a CsoundQt bug, when i run in the terminal there is no error.

**Comment by tarmoj** [comment]
Hm,

CsoundQt does not interfere to Csound syntax or error messages in any way.
I guess you built CsoundQt yourself? Can you try to clean and rebuild?
Perhaps some part is linked against older Csound version and creates the
problem.

I will test later myself, too.

Tarmo

E, 1. oktoober 2018 16:44 vncntmchlk <notifications@github.com> kirjutas:

**Comment by vncntmchlk** [comment]
Hello Tarmo, yes i built CsoundQt with the qtcreator. Do i need to take other steps to clean besides `make clean` in the CsoundQt directory?

**Comment by tarmoj** [comment]
Hi,

I tested myself and for me your code works correctly (CsoundQt 0.9.6-beta, 
Csound built from develop branch today), so I belive it should work.

If you use QtCreator, Build->Rebuild should be enought but more likely it is 
Csound build taht may have leftovers. Do you build also Csound? I suggest (in 
Csound build directoru):

make clean
make
sudo make unintall
sudo make install

and the rebuild CsoundQt.

Hope it helps!

tarmo

**Comment by joachimheintz** [comment]
as for csound, like hlödver i strongly recommend you to make a fresh 
clone because of the git confusion due to vst policy and following wrong 
pushed:

	git clone https://github.com/csound/csound.git csound

(the build descriptions at 
https://github.com/csound/csound/blob/develop/BUILD.md still work very 
well for me.)

if i have any trouble with the develop version, i find it very useful to 
just execute

	git checkout master

and then rebuild csound. (and vice versa 'git checkout develop' when i 
want to go back.)

ciao -
	jaochim

**Comment by vncntmchlk** [comment]
I did the complete removal and rebuilding of csound and CsoundQt and now it works fine. Thanks for all the help!
