### ISSUE TITLE
CsoundQt Mac OS Mojave doesn't run

### ISSUE THREAD

**Issue by Mattia541993** [CsoundQt/CsoundQt#265]
Hi all, I installed MacOs Mojave (since first beta versions) and since then CSoundQt doesn't respond when I double click on its icon. I've waited even for a long time, but without results and I had to kill its process manually.. Did someone has experienced the same issue?

Thank you very much,
Best regards
Mattia

**Comment by tarmoj** [comment]
Hi,

Can easily be that Apple has changed something in the OS API that is not 
backwards compatible. I have not heard complaints from other users though.
Anyway, If I have chance to upgrade my virtual Mac fro building, I will do a 
new build.

For any case for more information: I guess Csound works when you run it from 
terminal? Can you read something useful from crash reports (like a missing 
library or similar)?

tarmo

**Comment by Mattia541993** [comment]
Hi! Thanks for your answer :) Yes, from command line it works well and it compiles csd files. In the meanwhile I tried Cabbage (http://cabbageaudio.com) to develop in csound and it runs. Where I can find a log or report of what's missing?

Thank you,
Mattia

**Comment by oskarvonephesos** [comment]
Hi! I'm having the same issue. included below is an excerpt from the crash-report (I terminated the process after a couple minutes of it being unresponsive). unfortunately, I really don't know enough about csoundqt to draw any meaningful conclusions from it. (also, the machine I'm running it on is a 2017 macbook pro and I re-installed both csound and csoundqt after this issue first occurred)
all the best, richard

Process:         CsoundQt-d-py-cs6 [718]
UUID:            1A3770E9-A5D0-38D5-B000-AF0016A17D21
Path:            /private/var/folders/*/CsoundQt-d-py-cs6.app/Contents/MacOS/CsoundQt-d-py-cs6
Architecture:    x86_64
Parent:          launchd [1]
UID:             501
Footprint:       39.04 MB
Start time:      2019-01-05 11:06:16 +0100
End time:        2019-01-05 11:06:20 +0100
Num samples:     41 (1-41)
CPU Time:        0.003s (4.6M cycles, 835.8K instructions, 5.53c/i)
Note:            Translocated
Note:            Unresponsive for 139 seconds before sampling
Note:            1 idle work queue thread omitted

  Thread 0x2fb8             DispatchQueue 1           41 samples (1-41)         priority 46 (base 46)     cpu time <0.001s (76.8K cycles, 17.6K instructions, 4.36c/i)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [173], IO tier 0>
  41  start + 1 (libdyld.dylib + 94341) [0x7fff766f2085] 1-41
    41  main + 4698 (CsoundQt-d-py-cs6 + 677946) [0x10b2ab83a] 1-41
      41  CsoundQt::CsoundQt(QStringList) + 5060 (CsoundQt-d-py-cs6 + 789604) [0x10b2c6c64] 1-41
        41  CsoundQt::newFile() + 216 (CsoundQt-d-py-cs6 + 948152) [0x10b2ed7b8] 1-41
          41  DocumentPage::loadTextString(QString&) + 15 (CsoundQt-d-py-cs6 + 279919) [0x10b24a56f] 1-41
            41  DocumentPage::setTextString(QString&) + 11243 (CsoundQt-d-py-cs6 + 291211) [0x10b24d18b] 1-41
              41  BaseView::setFullText(QString, bool) + 7075 (CsoundQt-d-py-cs6 + 1823443) [0x10b3c32d3] 1-41
                41  ??? (<8FB24A8E-AC58-3612-AEC6-72D3B964E5D3> + 1426333) [0x10d9c739d] 1-41
                  41  ??? (<8FB24A8E-AC58-3612-AEC6-72D3B964E5D3> + 1431140) [0x10d9c8664] 1-41
                    41  ??? (<8FB24A8E-AC58-3612-AEC6-72D3B964E5D3> + 1234391) [0x10d9985d7] 1-41
                      41  ??? (<8FB24A8E-AC58-3612-AEC6-72D3B964E5D3> + 3483602) [0x10dbbd7d2] 1-41
                        41  ??? (<C86FCFF4-F490-3737-B424-560D065A5703> + 2220369) [0x10df8e151] 1-41
                          41  ??? (<8FB24A8E-AC58-3612-AEC6-72D3B964E5D3> + 1526694) [0x10d9dfba6] 1-41
                            41  ??? (<8FB24A8E-AC58-3612-AEC6-72D3B964E5D3> + 1527048) [0x10d9dfd08] 1-41
                              41  Highlighter::highlightBlock(QString const&) + 62 (CsoundQt-d-py-cs6 + 597150) [0x10b297c9e] 1-41
                                41  Highlighter::highlightCsoundBlock(QString const&) + 1706 (CsoundQt-d-py-cs6 + 599258) [0x10b2984da] 1-41
                                  41  Highlighter::findOpcode(QString, int, int) + 142 (CsoundQt-d-py-cs6 + 604638) [0x10b2999de] 1-41
                                    41  ??? [0xffff] 1-41
                                      41  ??? (<821F7E14-5708-349B-9B22-AB01213C2FDB> + 29473) [0x10b887321] 1-41
                                        41  exit + 55 (libsystem_c.dylib + 381406) [0x7fff7679b1de] 1-41
                                          41  __cxa_finalize_ranges + 351 (libsystem_c.dylib + 380658) [0x7fff7679aef2] 1-41
                                            41  ??? (<C86FCFF4-F490-3737-B424-560D065A5703> + 167782) [0x10dd98f66] 1-41
                                              41  ??? (<C86FCFF4-F490-3737-B424-560D065A5703> + 166366) [0x10dd989de] 1-41
                                                41  ??? (<C86FCFF4-F490-3737-B424-560D065A5703> + 166216) [0x10dd98948] 1-41
                                                  41  ??? (<C86FCFF4-F490-3737-B424-560D065A5703> + 179122) [0x10dd9bbb2] 1-41
                                                    41  ??? (<C86FCFF4-F490-3737-B424-560D065A5703> + 179467) [0x10dd9bd0b] 1-41
                                                      41  __psynch_cvwait + 10 (libsystem_kernel.dylib + 16818) [0x7fff7682e1b2] 1-41
                                                       *41  psynch_cvcontinue + 0 (pthread + 19278) [0xffffff7f82a68b4e] 1-41

**Comment by tarmoj** [comment]
Hi!

Thanks for the report. I cannot read anything enligtening out from the error 
messages...

I upgraded my development (virtual) machine to MacOs Mojave and rebuilt 
CsoundQt with newes Qt and uploaded the build to:
http://tarmo.uuu.ee/varia/failid/cs/CsoundQt/CsoundQt-Mojave-0.9.6-beta2.dmg

This is currently without PythonQt support. I managed to build new version of 
PythonQt but some things have changed and pacakging it into CsoundQt.app takes 
some more work.

Also -  this build of CsoundQt looks terrible in Mojave dark theme. There is 
too many hardcoded colors in there so I probably must find a way how to force 
it use always the light, Aqua theme.

Please let know if it works better for you!

tarmo

**Comment by Mattia541993** [comment]
Hi! Thank you! It works perfectly (Mojave 10.14.2). And you're right! Colours are not the best, but it doesn't matter!!

**Comment by oskarvonephesos** [comment]
Hi, it doesn't work on my machine, though. I have updated to the version of OSX that Mattia is using and my version still refuses to open when I directly open a file. In total I got the app open correctly, once and that instance crashed when I tried to open a file from the drop-down. If you want I can send you another crash report

**Comment by oskarvonephesos** [comment]
hi!
thank you very, very much! Opening the binary from inside the package and resetting the settings seems to have done the trick. weirdly, before that the fonts in the preferences pop-up and the icon’s were all messed up, as well. go figure! now everything seems to be working fine.

thank you very much for your swift responses. all the best,

richard
