### ISSUE TITLE
qt debugger option

### ISSUE THREAD

**Issue by pablozoani** [CsoundQt/CsoundQt#272]
Hello Developers. This is my first post here. I would like to know if someone of you can upload a csound version with this debugger: https://csoundqt.github.io/debugger2.html 
Or point to me how to build qt  with that available in windows. Thanks

**Comment by tarmoj** [comment]
Hi,

Sorry for not answering.
I have never truly tried this myself. The gotcha is that you need also Csound built in  debug mode. One thing is that on Windows it is not available (and I don't on Windows myself), other problem is that Csound is a bit slower in debug mode and I prefer to have Csound always built in Release mode for realtime work.

Have you checked out csdebugger command line program that comes with Csound? Perhaps this is helpful?

tarmo

**Comment by gogins** [comment]
It is possible to build in release mode but with debugging information.
This is only a tiny bit slower than release mode without debugging
information. Unfortunately these standards for release packages on both
Windows and Linux do not permit debugging information in the executable
files.

Perhaps it is possible to produce a release build with debugging
information in separate files. The debugging information could then be in a
separate package. If this is possible than that is what Csound should do.

Regards,
Mike

**Comment by pablozoani** [comment]
Hi, your reply is highly appreciated.

I have tried the debugger included with the csound installer but didn't manage to advance through the breakpoints (are control periods actually, not breakpoints). So i can run it, choose a ksmp to evaluate and shot only once, then close the command window and reopen, choose another control period again, reopen again. Also i couldn't find any documentation.

The qt debugger seems to be great, non expert users can't make it work, it could be a great tool to learn/teach the internal flow of samples.

Regards.

Pablo



De: Michael Gogins
Enviado: martes 23 de abril 9:01
Asunto: Re: [CsoundQt/CsoundQt] qt debugger option (#272)
Para: CsoundQt/CsoundQt
Cc: pablozoani, Author


It is possible to build in release mode but with debugging information.
This is only a tiny bit slower than release mode without debugging
information. Unfortunately these standards for release packages on both
Windows and Linux do not permit debugging information in the executable
files.

Perhaps it is possible to produce a release build with debugging
information in separate files. The debugging information could then be in a
separate package. If this is possible than that is what Csound should do.

Regards,
Mike
