### ISSUE TITLE
Button setWidgetProperty latched not working as expected

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#274]
I'm experimenting with python and manipulating interfaces. I want to randomise a bunch of buttons in latch mode, in a loop. What is the correct property to do this? Is the value correct?

q.setWidgetProperty(step, 'QCS_latched', randint(0,1))

**Comment by boonier** [comment]
My bad, in needed to use q.setChannelValue with the channel name string. Rtfm man!

Sorry for noise.

**Comment by tarmoj** [comment]
Hi,
Good to hear, thanks for interest!
Tarmo

R, 14. juuni 2019 11:42 Si Mills <notifications@github.com> kirjutas:
