### ISSUE TITLE
Crash when playing .orc

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#275]
macOS 10.12.6. Just orchestra code, no other tags/sections

CsoundQT just freezes and I have to force quit

**Comment by tarmoj** [comment]
Hi,

Thanks for the report! Yes, I can reproduce it - when there is no score
file, it crashes. I will investigate.

tarmo

Kontakt Si Mills (<notifications@github.com>) kirjutas kuupäeval L, 15.
juuni 2019 kell 01:50:

**Comment by tarmoj** [comment]
Hi,

I fixed the crash in git. Thanks!
Now Csound reports an error when you start orc without sco file from
CsoundQt. I guess it would be nice to be able to run just the orc file
without score as scoreless csd? I will get to that tomorrow.

tarmo

Kontakt Tarmo Johannes (<trmjhnns@gmail.com>) kirjutas kuupäeval L, 15.
juuni 2019 kell 19:42:

**Comment by tarmoj** [comment]
I implemented now opening an orc file without score file. Works like scoreless csd.
Committed to git, I plan to make publish binaries  (release candidate of 0.9.6) next week.
Tarmo

**Comment by boonier** [comment]
Sweet! thanks. Quick one, with a scoreless csd, do the <CsScore> tags still need to be present? Seems that csound starts and stops running immediately.
