### ISSUE TITLE
Init value #266

### ISSUE THREAD

**Issue by Djack13** [CsoundQt/CsoundQt#279]
Hello,
Problem is still there with CsoundQt 0.9.6 and Csound 6.13 just released.
Should I use csoundqt develop version?

**Comment by tarmoj** [comment]
Indeed, I get the problem also again. Although I am sure I tested it on another computer and it seemed to work. The strange thing is that when I debug and put a breakpoint in the end of CsoundQt class, stop there and then continue, it works as expected. I take time to think and investigate. This seems to be a nasty one...
tarmo

**Comment by tarmoj** [comment]
I wrote now another work-around that seems to work here. Please try (from git develop) branch.
The solution is to create from csd template a temporary file (before it was just empty page), run it, stop and close the tab. User does not see anything but this does the one necessary Start for the user.
I relly cannot guess what is the actual reason...

tarmo

**Comment by Djack13** [comment]
With 0.9.6-1 dev, it works :)
Thanks a lot
