### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by silvain** [CsoundQt/CsoundQt#281]
I am using CsoundQT on Ubuntu 18.04.
It does not display accented characters in my comments (as I speak French, I like writing it correctly...) in csd files.
It is not a big issue, as it does not affect the functioning of the software, but I suggest that Unicode characters should be recognised and displayed correctly.

**Comment by tarmoj** [comment]
Hi,

Thanks for the report! Accented and other unicode characters work for me on
openSuse 15.0, CsoundQt 0.9.6, Qt 5.9.4
Can you send a small test csd and a screenshot?

Also please check what font is set for editor in Configure -> Editor ->
Font and make sure it  supports the characters.

tarmo


Kontakt Silvain Dupertuis (<notifications@github.com>) kirjutas kuupäeval
E, 5. august 2019 kell 23:02:

**Comment by tarmoj** [comment]
No feedback. I am about to close the issue.

**Comment by tarmoj** [comment]
Closing old issue of no feedback.
