### ISSUE TITLE
GUI window issues

### ISSUE THREAD

**Issue by bernardgeyer** [CsoundQt/CsoundQt#282]
On MacOS X:

- When widgets are in an independent window, there are no scrollbars when the window content is bigger than the window.

- When widgets are NOT in an independent window, the scrollbars are visible, but of course the GUI disappears when selecting the Finder or another application.

- When switching tabs on the CsoundQt window, only the GUI window that belong to this tab is visible, even if "Allow simultaneous play" is selected. This is really annoying, when trying to build a program that needs multiple windows.

The best would of course be, that we can have multiple windows for each csound program;

**Comment by bernardgeyer** [comment]
I saw also that when I open .scd files by double-clicking on it, every widget window stay open, but when I click one time on a tab, only the widgets of this tab stay visible.

**Comment by tarmoj** [comment]
Thanks for the reports!
I will try to get to them soon.
Tarmo

K, 14. august 2019 14:04 bernard <notifications@github.com> kirjutas:

**Comment by tarmoj** [comment]
Hi,

Thanks for the report! I confirm that the scorllbars are not visible in widgets' separate window and I agree, they should. I will have look at it but cannot do it immediately.

I did not understand "every widget window stay open, but when I click one time on a tab, only the widgets of this tab stay visible.". I cannot reproduce it on Linux. Do you say that on starting CsoundQT this way several widget windows are visible? 

Having several widget's windows is not currently possible and I do not plan any substantial work with CsoundQt any more, just bug fixes.

If you use CsoundQt with PythonQt you have an option to write your own GUI, but it is not that easy there are some examples on: https://csoundqt.github.io/pages/python.html   -> Creating Own GUIs with PythonQt This requires some understabning of python and Qt widgets.  Probably you need to create a QtGui.QTabWidget and place the different controls there. This is some work and experimenting. 

Greetings,
tarmo

**Comment by bernardgeyer** [comment]
Having several widget's windows open is perfectly possible, at least on Mac OS X, with the following configuration settings:
General: allow simultaneous play - selected
Widgets: Show Widgets on Play - selected
Widgets: Widgets are an independent window  - selected
Editor/Remember open files from previous sessions  - unselected

I am very glad for this and hope it will stay in the future!

I wanted to make a kind of standalone multi-window application with CsoundQt, and it is perfectly possible with a simple shell script, for example the following, using some examples .csd files:

```
#! /bin/bash
open /Applications/CsoundQt-d-py-cs6.app
open /Applications/CsoundQt-d-py-cs6.app/Contents/Resources/McCurdy\ Collection/SoundGenerators/vco2.csd
open /Applications/CsoundQt-d-py-cs6.app/Contents/Resources/McCurdy\ Collection/SoundGenerators/gbuzz.csd
open /Applications/CsoundQt-d-py-cs6.app/Contents/Resources/McCurdy\ Collection/SoundGenerators/WhiteNoisePinkNoise.csd
```
I can even start one csound file from another:
```
instr 3
ires system_i 1, {{
open /Applications/CsoundQt-d-py-cs6.app/Contents/Resources/McCurdy\ Collection/SoundGenerators/vco2.csd
}}
turnoff
endin
```

and I communicate between them with OSC.
The widgets of all windows can also respond to midi messages.

**Comment by tarmoj** [comment]
Very interesting, I did not know!
Thanks for sharing!
Tarmo

R, 16. august 2019 17:53 bernard <notifications@github.com> kirjutas:
