### ISSUE TITLE
CsoundQT GUI don't accept MIDI when multiple midi devices are used

### ISSUE THREAD

**Issue by bernardgeyer** [CsoundQt/CsoundQt#283]
The MIDI feature of CsoundQT GUI is really fantastic, but it works only when a midi input device is selected on CsoundQT Configuration.

Sometimes it is useful to use more than one device, for example a keyboard and a midi controller, or more than one player on stage, but unfortunately, MIDI is not recognised by the GUI when "Use Csound midi modules" is selected instead.

**Comment by tarmoj** [comment]
Hi, 
There are several ways how to direct  MIDI devices into one virtual devie or send through MIDI through. There is an example about Linux, I believe MacOS should have something similar:

https://github.com/CsoundQt/CsoundQt/wiki/Use-multiple-MIDI-devices-(Linux)

Also I think it is possible to set CsoundQt use rtmidi but in CsoundOptions in csd set other device too (like -Ma), I think I have done it in the past but forgot the details.

tarmo

tarmo
