### ISSUE TITLE
The toolbar theme disappears sometimes after some setting modifications

### ISSUE THREAD

**Issue by bernardgeyer** [CsoundQt/CsoundQt#284]
On MacOS X
After that, even switching the theme and restarting CsoundQt does not help.
The last time it happened for me was after changing the interface language
The only way that helps is to go to the Help menu and to call "reset preferences".

**Comment by tarmoj** [comment]
This a nasty and well hidden probelm on MacOS that sometimes the preferences file gets messed up. I have never been able to find out the cause. If it happens again, please send me the preferences file
$HOME/Library/Preferences/com.csound.qutecsound.plist
and describe in which situation it happened and maybe you can guess what might have caused the problem.

So far resetting the preferences is unfortunately the best what you can do - you are right.

tarmo

**Comment by bernardgeyer** [comment]
I just installed csoundQt on Windows, and the problems are exactly the same.

**Comment by tarmoj** [comment]
Can you suggest a situation or sequence of actions how to reproduce it to debug?
tarmo

**Comment by joachimheintz** [comment]
i think it is not necessary to reset the preferences.  go to 
Configure>General and look at "Theme (requires restart)".  most probably 
you will find a blank space in the popup menu.  choose "boring" and 
restart csoundqt.
