### ISSUE TITLE
broken Csound link 404

### ISSUE THREAD

**Issue by xenophoria** [CsoundQt/CsoundQt#287]
> To build CsoundQt, you must have installed **Csound** first

broken Csound link 404

**Comment by tarmoj** [comment]
Thanks for the report!

Would have been helpfult to hint where is the brogen link. Did you mean 
https://github.com/CsoundQt/CsoundQt/blob/master/BUILDING.md ?

This is fixed now, thanks.

tarmo

**Comment by xenophoria** [comment]
Thanks Tarmo, I highlighted Csound but it would have been more helpful if I made it a link. Greg
