### ISSUE TITLE
int CsoundEngine::play has a path which does not return anything

### ISSUE THREAD

**Issue by fpesari** [CsoundQt/CsoundQt#288]
This function has an integer return type, so it should always return an integer value. But if when called the "else" path is not taken, it never returns any value.

This is a very serious bug because RPM actually refuses to build such a package.

**Comment by tarmoj** [comment]
Thanks for the report!

I fixed this and some other warnings and pushed the changes to develop
branch. Do you build from master? Should I cherry pick this commit to there?

Tarmo

L, 28. detsember 2019 11:05 Fabio Pesari <notifications@github.com>
kirjutas:

**Comment by fpesari** [comment]
I use the point release for [this package](https://build.opensuse.org/package/show/home:geekositalia:daw/CsoundQt) for openSUSE. No need to cherry pick the commit, I will make a patch from `develop` :smile_cat:

**Comment by tarmoj** [comment]
Oh, I am on openSuse myself, I did not know somebody is packaging that!
Let know if there are any problems.
tarmo
