### ISSUE TITLE
macOS: window panes dimensions still not recalled on restart

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#292]
Small nitpick, but the dimensions of the panes aren't were I left them on quit, so I have to readjust every time I restart. Particularly the Inspector panel fills 50% of total window width.

CsoundQT 0.9.7
macOS Mojave 10.14.6

Thanks

**Comment by tarmoj** [comment]
Hi!

Thanks for the report! I will check when I get to a MacOS machine.


tarmo

Kontakt Si Mills (<notifications@github.com>) kirjutas kuupäeval E, 27.
jaanuar 2020 kell 13:24:

**Comment by boonier** [comment]
No problem thanks

**Comment by gesellkammer** [comment]
Just tested this in macOS 10.14 and it seems to work fine. Closing
