### ISSUE TITLE
macOS mojave font rendering looking really poor

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#293]
![image](https://user-images.githubusercontent.com/6206789/73218048-09281680-4151-11ea-8d58-e4660e1f5b93.png)

It is a recognised issue on Mojave that on non retina displays Apple have done a number and changed the font smoothing algorithm. 

https://www.howtogeek.com/358596/how-to-fix-blurry-fonts-on-macos-mojave-with-subpixel-antialiasing/

Is CsoundQT now only targeting Retina (HiDPI) displays? Pd seems to be rendering fine however:

![image](https://user-images.githubusercontent.com/6206789/73217967-e138b300-4150-11ea-8e93-833d5f1a7fa5.png)

**Comment by boonier** [comment]
p.s. sorry I wasn't around to flag this in beta!

**Comment by boonier** [comment]
I should add this is on a 27" display (non-retina) displaying at a resolution of 2560x1440

Interestingly on the current display I'm using now (plugged into my laptop also running Mojave) the UI looks fine. 1080p (1920×1080).

**Comment by boonier** [comment]
OK this is strange. All seems ok now in the 27" iMac. 

I reset the font smoothing settings to default

`defaults write -g CGFontRenderingFontSmoothingDisabled -bool YES`

and restarted. 

![image](https://user-images.githubusercontent.com/6206789/73297336-4cdb5880-4203-11ea-8a7f-4404241057e5.png)

I'll keep an eye on it but thankfully I didn't drag you into it too much!

**Comment by tarmoj** [comment]
Thanks! I am glad it seems to work for you!
Tarmo

T, 28. jaanuar 2020 21:21 Si Mills <notifications@github.com> kirjutas:

**Comment by tarmoj** [comment]
Closing.
