### ISSUE TITLE
Csound error on macOS Lion

### ISSUE THREAD

**Issue by gianare** [CsoundQt/CsoundQt#298]
Hi all guys, i hope someone can help me 'cause i need this help for university study. I
have already tried to check something on internet but i can't find nothing can help me. The problem is this:
i begin with installation of Csound from their site https://csound.com/download.html
after that, i have to installate 2 component: Csound.pkg and QTsound.dmg; the Csound.pkg has no problem to install it but QT has some problems, so i have downloaded another version of QTSound that can play on my Mac.
Now, if i render the audio, i can listen the exported file from my score, but in my QTsound console i can't see the result and i can't run and/or listen nothing from qtsound until i render the score. Thanks for your attention, and for help (i hope)
#Csound #macOS #QTsound #bug #error #console #help wanted

**Comment by joachimheintz** [comment]
hmm -- there is no error in the output console:
"0 errors in performance"

from your description i have no idea why you don't hear any sound.
perhaps look at Configure > Run, and see whether the buffer size is ok, 
and whether the RT Audio Module is selected correctly.

here are descriptions:
https://csoundqt.github.io/pages/configuring-csoundqt.html
https://csoundqt.github.io/pages/tips-and-tricks.html

best -
     joachim

**Comment by tarmoj** [comment]
Hi,

Please write quetsions rather to the mailing-list, it is not exactly a bug report, the issue tracker is usually for
https://sourceforge.net/projects/qutecsound/lists/qutecsound-users (https://link.getmailspring.com/link/336433D5-138D-437A-8FEE-4785F50AA3F4@getmailspring.com/0?redirect=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fqutecsound%2Flists%2Fqutecsound-users&recipient=cmVwbHkrQUIyVUVVM1VYNlBQUVNSVzREUFM3NkY0TzU1TUZFVkJOSEhDRkc2NFRNQHJlcGx5LmdpdGh1Yi5jb20%3D)

Although the Csound output seems somewhat cryptic, it actually gives you information:
red does not mean error here, it is just to bring out - the overall amplitude (that looks good) and 0 samples out of range means that everything is all right.
"writing N blocks of shorts to test.aiff" means that your output DOES go to file. Please check your audio output options Configure -> Realtime Audio and use Examples->Useful->IO test to figure out how it works.
There is also pretty good documentation on:
https://csoundqt.github.io/pages/documentation.html (https://link.getmailspring.com/link/336433D5-138D-437A-8FEE-4785F50AA3F4@getmailspring.com/1?redirect=https%3A%2F%2Fcsoundqt.github.io%2Fpages%2Fdocumentation.html&recipient=cmVwbHkrQUIyVUVVM1VYNlBQUVNSVzREUFM3NkY0TzU1TUZFVkJOSEhDRkc2NFRNQHJlcGx5LmdpdGh1Yi5jb20%3D)
Greetings,
tarmo

**Comment by gianare** [comment]
Thank u @joachimheintz and @tarmoj , i will write to the correct mailing list. I thought that the audio preferences (like buffer size or sr) was the same for run and for render so i couldn't understand why the rendering file is ok but at the moment that i run i have not some response. I will try to follow your tips, really thanks
