### ISSUE TITLE
Start/Resume and Pause Buttons (in Xanadu - and maybe elsewhere

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#306]
When you press the Start/Resume Button in Xanadu, it starts
When you press Pause, it pauses
BUT
When you press Resume (to continue) it does NOT
INSTEAD 
When you press Pause again it continues

You might want to look into this, or rename the buttons - Start  and Pause/Resume

**Comment by gesellkammer** [comment]
This has nothing to do with csoundqt, the csd file is wrong.

**Comment by csounder** [comment]
But, it is an example that is distributed with CsoundQt and that, from the CsoundQt widgets, is not working correctly, who will fix the .csd prior to the next distribution?

**Comment by csounder** [comment]
The widget labels need to be changed - to Start and then Pause/Resume

**Comment by tarmoj** [comment]
Hi,

Makes sense, now fixed in git (develop branch).

Thanks for reporting!

tarmo



Kontakt csounder (<notifications@github.com>) kirjutas kuupäeval T, 19. mai
2020 kell 22:05:

**Comment by csounder** [comment]
Wonderful - thanks!
