### ISSUE TITLE
Start/Resume text cut off in the Button

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#307]
Not a huge bug, but an issue on the Macintosh that has always made the app look a little less professional.  It might be because of the default font that the Mac is using and the size being wrong.  But... On the Mac, there are a number of Widgets that have the text in their button chopped off a bit.  And this is after I reset preferences and restart or after I install the latest version.

**Comment by csounder** [comment]
This might be fixed in 0.9.8 rc1-1 as the text is smaller and the words are not cut off.  In 0.9.7 it is an issue.

**Comment by gesellkammer** [comment]
Please don't post any issues referring to 0.9.7.

**Comment by csounder** [comment]
But 0.9.7 "is" the version distributed with Csound in the .dmg files and
so, all my students will be using 0.9.7 as will many other MacUsers.

*Dr. Richard Boulanger*

Berklee College of Music

rboulanger@berklee.edu

**Comment by gesellkammer** [comment]
Well, then any fix will not reach them because the next version (0.9.8) will be distributed with the next release of csound. Instead they can download the latest version and find a plethora of fixes to this and other issues. 
But do report if you find any bugs with 0.9.8!

**Comment by tarmoj** [comment]
Hi,

I jump in here -  all bug reports are always welcome! Of course, we
developers have freedom to ignore them ;) But still - any effort to take
the care to open an issue can help to make the program better.

Taking care of the examples is a huge task and I have not had time for
that. Joachim has done a lot of work for it but still help would be more
than welcome!
Another thing is that CsoundQt is cross platform -  a label may look good
on one OS and not on another.

Csounder, do you have access to different machines (even if it is Mac and
Windows), would you care to go through the examples, make corrections to
the csd-s, save them and and send me back to trmjhnns@gmail.com

Thanks!
tarmo


Kontakt Eduardo Moguillansky (<notifications@github.com>) kirjutas
kuupäeval T, 19. mai 2020 kell 22:03:
