### ISSUE TITLE
Audio Input not working by default

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#309]
i am using the current develop version (0.9.8.rc3) on linux. 
on all audio modules (jack, pulse, alsa) i have to insert "adc" manually to get the realtime audio input to work. (output works allright.)
i suggest to set "adc" and "dac" as default in configure>run.

**Comment by tarmoj** [comment]
Hi,

I think it came from the function ConfigDialog::onRtModuleComboBoxChanged that reset the input/output LineEdit. I wrote a small fix and pushed to developt that seems to solve this problem:

void ConfigDialog::onRtModuleComboBoxChanged(/*int index*/) {
	RtInputLineEdit->setText("adc"); // was ""
	RtOutputLineEdit->setText("dac"); // was ""
}

Eduardo, please review if it make sense and does not break anything.

tarmo

**Comment by joachimheintz** [comment]
hi -

i have pulled and rebuilt.  first i saw no difference: blank boxes, 
output working but input not working.  but after the first selection of 
"adc" it stays for the rest of the choices, too.  so much better.

thanks -
	joachim

**Comment by gesellkammer** [comment]
Tarmo's code change did not fix this because the callback was not being fired at all. Joachim's "so much better" is a classic case of code placebo...
Anyway, this is fixed in git now.
