### ISSUE TITLE
Examples->Synths->Mono Synth "cannot compile orchestra"

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#310]
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using blocking interface
error: syntax error, unexpected T_IDENT  (token "kchan") from file /private/var/folders/ct/lr8kxfhd2zz_vmskl_h41rl00000gn/T/csound-tmpUuaOXJfp.csd (1)
 line 33:
>>>kstatus kchan <<<
Unexpected untyped word kstatus when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

**Comment by gesellkammer** [comment]
fixed
