### ISSUE TITLE
Examples->Synths->Sruti-Drone Box "error in instr 3" warning: divide by 0 - no sound

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#311]
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using blocking interface
defining argument `BOCT``B as...#gkbase#
defining argument `BOCT``O as...#k8ve1#
defining argument `BOCT``B as...#gkbase#
defining argument `BOCT``O as...#k8ve2#
defining argument `BOCT``B as...#gkbase#
defining argument `BOCT``O as...#k8ve3#
defining argument `BOCT``B as...#gkbase#
defining argument `BOCT``O as...#k8ve4#
Elapsed time at end of orchestra compile: real: 0.006s, CPU: 0.006s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.006s, CPU: 0.006s
midi channel 1 using instr 3
midi channel 2 using instr 3
midi channel 3 using instr 3
midi channel 4 using instr 4
midi channel 5 using instr 5
midi channel 6 using instr 3
midi channel 7 using instr 3
midi channel 8 using instr 3
midi channel 9 using instr 3
midi channel 10 using instr 3
midi channel 11 using instr 3
midi channel 12 using instr 3
midi channel 13 using instr 3
midi channel 14 using instr 3
midi channel 15 using instr 3
midi channel 16 using instr 3
midi channel 17 using instr 3
midi channel 18 using instr 3
midi channel 19 using instr 3
midi channel 20 using instr 3
midi channel 21 using instr 3
midi channel 22 using instr 3
midi channel 23 using instr 3
midi channel 24 using instr 3
midi channel 25 using instr 3
midi channel 26 using instr 3
midi channel 27 using instr 3
midi channel 28 using instr 3
midi channel 29 using instr 3
midi channel 30 using instr 3
midi channel 31 using instr 3
midi channel 32 using instr 3
midi channel 33 using instr 3
midi channel 34 using instr 3
midi channel 35 using instr 3
midi channel 36 using instr 3
midi channel 37 using instr 3
midi channel 38 using instr 3
midi channel 39 using instr 3
midi channel 40 using instr 3
midi channel 41 using instr 3
midi channel 42 using instr 3
midi channel 43 using instr 3
midi channel 44 using instr 3
midi channel 45 using instr 3
midi channel 46 using instr 3
midi channel 47 using instr 3
midi channel 48 using instr 3
midi channel 49 using instr 3
midi channel 50 using instr 3
midi channel 51 using instr 3
midi channel 52 using instr 3
midi channel 53 using instr 3
midi channel 54 using instr 3
midi channel 55 using instr 3
midi channel 56 using instr 3
midi channel 57 using instr 3
midi channel 58 using instr 3
midi channel 59 using instr 3
midi channel 60 using instr 3
midi channel 61 using instr 3
midi channel 62 using instr 3
midi channel 63 using instr 3
midi channel 64 using instr 3
0dBFS level = 1.0
ftable 1:
ftable 2:
ftable 3:
ftable 4:
ftable 5:
ftable 6:
ftable 7:
ftable 8:
ftable 9:
ftable 10:
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Feb 12 2010 09:42:54)
   0: dac0 (Built-in Output [Core Audio])
   1: dac1 (Soundflower (2ch) [Core Audio])
   2: dac2 (Soundflower (64ch) [Core Audio])
   3: dac3 (Modulince [Core Audio])
   4: dac4 (AirBeamTV  [Core Audio])
PortAudio: selected output device 'Built-in Output'
writing 2048 sample blks of 64-bit floats to dac0
SECTION 1:
new alloc for instr 98:
new MIDI alloc for instr 3:
INIT ERROR in instr 3 line 239: table not found in poscil
 from file /private/var/folders/ct/lr8kxfhd2zz_vmskl_h41rl00000gn/T/csound-tmpKZZJvSNN.csd (1)
a1	poscil3.a	kenv	kfreq	itbl	0	
		   T  0.000 - note deleted. instr 3 had 1 init errors
INIT ERROR in instr 3 line 239: table not found in poscil
 from file /private/var/folders/ct/lr8kxfhd2zz_vmskl_h41rl00000gn/T/csound-tmpKZZJvSNN.csd (1)
a1	poscil3.a	kenv	kfreq	itbl	0	
		   T  0.000 - note deleted. instr 3 had 1 init errors
  rtevent:	   T  0.743 TT  0.743 M:  0.00000  0.00000
WARNING: Division by zero
WARNING: Division by zero

**Comment by gesellkammer** [comment]
This is an error of the example author. Thanks for reporting.

**Comment by DaveSeidel** [comment]
So far, I cannot reproduce this. I note that I don't get this statement in my console output: `new MIDI alloc for instr 3` -- this seems odd since the example does not use MIDI. I am testing in Win10 using CsoundQT 0.97 and Csound 6.14.

**Comment by DaveSeidel** [comment]
I did notice that I was initializing a could of gk variables to 0, so it's possible that they are not being set to sane values at runtime. This PR initializes them to usabl values.

https://github.com/CsoundQt/CsoundQt/pull/321

**Comment by DaveSeidel** [comment]
@csounder have you tried this in the new version?

**Comment by csounder** [comment]
Seems to be related to the portaudio issue on the Mac - even with the
latest version.

I just tried it with portaudio selected and audio input selected and it
gave me the Warning Divide by 0 error and then crashed the app
- It also reported that I was starting MIDI instrument 3 - when I played my
MIDI keyboard.

When I switch to CoreAudio
When I switch OFF the audio input
When I turn OFF the MIDI

It runs fine


*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

Professional Writing and Technology Division

*Berklee College of Music*


skype: radiobaton

facebook: https://www.facebook.com/richard.boulanger.58

about: http://www.boulangerlabs.com/#about

about: http://www.csounds.com/community/developers/dr-richard-boulanger/

music:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/


Boulanger Labs - http://boulangerlabs.com

The Csound Book - http://mitpress.mit.edu/books/csound-book

The Audio Programming Book -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by DaveSeidel** [comment]
Thanks, Richard. Since it's pretty clearly a platform issue, I don't think there's any more I can do here (I don't have a Mac).

**Comment by csounder** [comment]
I would not have thought to change my IO to CoreAudio (I usually leave
things on PortAudio and PortMIDI).
- I am very happy to have found a way to make it work, and I might start
recommending that my students (all MacUsers) switch over their CsoundQt
to PortAudio.
- I will keep you posted when the PortAudio situation gets resolved.  And
hopefully that will fix it for all Audio Libraries/Drivers on the Mac.

Take care

-R

*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

Professional Writing and Technology Division

*Berklee College of Music*


skype: radiobaton

facebook: https://www.facebook.com/richard.boulanger.58

about: http://www.boulangerlabs.com/#about

about: http://www.csounds.com/community/developers/dr-richard-boulanger/

music:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/


Boulanger Labs - http://boulangerlabs.com

The Csound Book - http://mitpress.mit.edu/books/csound-book

The Audio Programming Book -
http://mitpress.mit.edu/books/audio-programming-book
