### ISSUE TITLE
Examples->Synths->String Phaser no sound level, no bugs reported in console, strange ifreq in console

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#312]
instr 1:  ifreq = 674557.350
  rtevent:	   T  3.019 TT  3.019 M:  0.00000  0.00000
  rtevent:	   T  3.529 TT  3.529 M:  0.00000  0.00000
  midiKeyCps:      pfield:   4  value: 195
  midiVelocity:    pfield:   5  value:  55
instr 1:  ifreq = 674557.350
  rtevent:	   T  3.994 TT  3.994 M:  0.00000  0.00000
  rtevent:	   T  7.036 TT  7.036 M:  0.00000  0.00000
  midiKeyCps:      pfield:   4  value: 195
  midiVelocity:    pfield:   5  value:  82
instr 1:  ifreq = 674557.350
  rtevent:	   T  7.129 TT  7.129 M:  0.00000  0.00000
  rtevent:	   T  7.338 TT  7.338 M:  0.00000  0.00000
  midiKeyCps:      pfield:   4  value: 195
  midiVelocity:    pfield:   5  value:  73
instr 1:  ifreq = 674557.350
  rtevent:	   T  7.430 TT  7.430 M:  0.00000  0.00000
  rtevent:	   T  7.593 TT  7.593 M:  0.00000  0.00000
  midiKeyCps:      pfield:   4  value: 195
  midiVelocity:    pfield:   5  value:  66
instr 1:  ifreq = 674557.350
  rtevent:	   T  7.668 TT  7.668 M:  0.00000  0.00000
  rtevent:	   T  7.802 TT  7.802 M:  0.00000  0.00000
  midiKeyCps:      pfield:   4  value: 195
  midiVelocity:    pfield:   5  value:  67
instr 1:  ifreq = 674557.350
  rtevent:	   T  7.889 TT  7.889 M:  0.00000  0.00000

**Comment by gesellkammer** [comment]
This is a programing error by the example author. Could you please provide a PR with a fix? (look at --midi-key-cps) Thanks!
