### ISSUE TITLE
Examples->Synths->Scanned Synthesis Sandbox "Cannot open file (circular...

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#313]
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
Cannot open file (circularstring-128) subfile

**Comment by gesellkammer** [comment]
Please, :pray:, include the basic things: platform, csound version, csoundqt version, console output. 
Regarding this particular issue: if you are using csoundqt <= 0.9.7, this has been fixed.

**Comment by csounder** [comment]
Only use the latest CsoundQt 0.9.8 rc1-1 as you requested.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tarmoj** [comment]
Hi,

I cannot reproduce it with current build from develop on Linux, will try
later on MacOS.

tarmo

Kontakt csounder (<notifications@github.com>) kirjutas kuupäeval L, 6.
juuni 2020 kell 12:32:

> Only use the latest CsoundQt 0.9.8 rc1-1 as you requested.
>
> Dr. Richard Boulanger
> Professor
> Electronic Production and Design
> Berklee College of Music
>
> > On Jun 6, 2020, at 1:48 AM, Eduardo Moguillansky <

**Comment by csounder** [comment]
I am on MacOS

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by csounder** [comment]
System Info:


macOS Mojave 10.14.6

macOS Catalina 10.15.0


CsoundQt-v0.9.8-rc1-1


Html Doc Directory:
/Library/Frameworks/CsoundLib64.framework/Resources/Manual

Favorite dir: /Users/rboulanger/Desktop/csFavorite

Python Executable: python

Csound Executable: csound



*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

Professional Writing and Technology Division

*Berklee College of Music*


skype: radiobaton

facebook: https://www.facebook.com/richard.boulanger.58

about: http://www.boulangerlabs.com/#about

about: http://www.csounds.com/community/developers/dr-richard-boulanger/

music:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/


Boulanger Labs - http://boulangerlabs.com

The Csound Book - http://mitpress.mit.edu/books/csound-book

The Audio Programming Book -
http://mitpress.mit.edu/books/audio-programming-book
