### ISSUE TITLE
which version of csound and what is the full path to csound

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#314]
Not sure, this could be a CsoundQt thing or it could just be a Csound thing, and I just might not know the correct flag.

For some reason, when I run an Example .csd in:

System Info:

macOS Mojave 10.14.6
macOS Catalina 10.15.0

CsoundQt-v0.9.8-rc1-1

Html Doc Directory: /Library/Frameworks/CsoundLib64.framework/Resources/Manual
Favorite dir: /Users/rboulanger/Desktop/csFavorite
Python Executable: python
Csound Executable: csound

...  the console no longer shows the version of Csound that is running and so, I can't report anything else but that I am using the version of csound that is specified in the Environment tab: Csound Executable csound and Python Executable python

I am also excited by the fact that Steven Yi has shown me (and my students) a simple way to build Csound from the latest sources with HomeBrew on the Mac, and this has allowed me personally to collaborate with John ffitch on the development of a new set of opcodes, but this also means that there are several versions of Csound installed on my MacBook Pro (as I am sure there are several version installed on many of your developer systems.

And so, I am looking for a command-line option that I can use, from whatever CsoundQt I am running that will display in the console the version of Csound being used to render the .csd and maybe another command-line flag that will show the complete path to the python that might be used or the csound that is being used or the utilities that are being used.
When I run from the terminal, I am told which csound is being used, and this is the latest that I have downloaded with HomeBrew to use with my John ffitch development work, but this is "not" the one that I am using with CsoundQt (I don't think)
I tried the --version flag but it does not display the version of Csound in the consoleandI do not know if there are --full-path flags for csound, python, utilities, etc.
perhaps verbose will show this in the console, I will try that, but if there are flags that I am missing I would love some advice.

THANKS
-dB

**Comment by tarmoj** [comment]
Hi,

You should see the Csound version from menu Help -> About something like:
"Using Csound version: ... "

or if you start a csd with the "Run in Term" button.
Indeed, the console output does not show the Csound version, as it is a minor thing, I would leave it like that.
Might easily be that if you build Csound with homebrew and have several Csounds installed, CsoundQt uses the libraries from the usual locations. You are able to set the path of csound from CsoundQt Configure -> Environment that will be used for "Run in Term" AND you should be able to associate CsoundQt with install_name_tool something like:
install_name_tool -change <location of standard Csound farmaework>/Versions/6.0/CsoundLib64 <location of wanted Csound farmaework>/Versions/6.0/CsoundLib64 <your CsoundQt>.app/Contents/MacOS/<your csoundqt binary there>
It can be tricky though.
Use otool -L r CsoundQt>.app/Contents/MacOS/<your csoundqt binary there> to see where it linked by default.
tarmo

**Comment by csounder** [comment]
Tarmo,

There seems to be no menu. Help->about

but

There is the about CsoundQt dialog box that appears under the app name:
CsoundQt-d-html-cs6

and in the dialog box, among other things, it says the following:

Version 0.9.8-rc1
Released under the LGPLv2 or GPLv3

Using Csound version:6140 Precision:double (64-bit)
Html5 support based on QtWebEngine


Is this what you mean?


...but it does not say the date of the release of that version (if it would
matter when submitting issue reports?)

**Comment by tarmoj** [comment]
Hi,

Mostly this is enough, CsoundQt does not depend on Csound version that
heavily, as long you don't go too far, they should work well together. If
it the case, Run in Term helps.


tarmo


Kontakt csounder (<notifications@github.com>) kirjutas kuupäeval L, 6.
juuni 2020 kell 20:47:

**Comment by gesellkammer** [comment]
CsoundQt mirrors csound's stdout in its console, stderr is left unchanged, which means that if CsoundQt is run from the command line its stderr can be read there. The version number as reported by csound itself can be queried in the about dialog.
