### ISSUE TITLE
Default Path to Terminal.app not correct on MacOS Catalina (posibly wrong on Mojave too)

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#315]
Maybe a "bug" to report:  Note:  I am on my Catalina MacBook now 10.15.5 and I could not get the run in term button to work, so...- i reset preferences for CsoundQt-v0.9.8-rc1-1- i restarted CsoundQt-v0.9.8-rc1-1- i opened examples Floss Manual Basics 01 - aliasing- i run it (yes)- i render it (yes)- i run in term (nothing happens)- i look in configure externals and find this default: /Applications/Utilities/Terminal.app
- i use the ... button to browse and find my terminal app and is substitutes: /System/Applications/Utilities/Terminal.app
and then- i run in terminal (yes!)
and it tells me in the console that I am using the same version as my students - for teaching (yes)
--Csound version 6.14 (double samples) Jan 26 2020
and when i run csound in the terminal from the command-line to do my dev work with John ffitch, I am running the latest dev version that has yet to be released and has his new opcodes in it.

macOS Catalina 10.15.5
CsoundQt-v0.9.8-rc1-1
Html Doc Directory: /Library/Frameworks/CsoundLib64.framework/Resources/ManualFavorite dir: /Users/rboulanger/Desktop/csFavoritePython Executable: pythonCsound Executable: csound

From Run in Terminal:
--Csound version 6.14 (double samples) Jan 26 2020

**Comment by tarmoj** [comment]
Thanks for the heads up!

Is it so that ealriler  /Applications/Utilities/Terminal.app was the
correct path and with Cataline it is changed to:
/System/Applications/Utilities/Terminal.app ?

I think for now it is better to keep the older one since there are many
users on somewhat older systems but it is very good to know!

tarmo

Kontakt csounder (<notifications@github.com>) kirjutas kuupäeval L, 6.
juuni 2020 kell 20:22:

**Comment by gesellkammer** [comment]
Maybe it would be possible to at least fire a dialog within CsoundQt warning the user that the path does not exist?

**Comment by tarmoj** [comment]
Yes, would be nice. I have to find how to check the operating system
information from Qt code.
On a quick search there is QOperatingSystemVersion but that is from Qt 5.9
and we have to support Qt at least from Qt 5.5 (for AppImage build). From
other hand -  since it is MacOS specific, the build on Mac will be anyway
with newer Qt so it is possible to have in in the #ifdef Q_OS_MAC section,
so no problem. Doable.

tarmo

tarmo


Kontakt Eduardo Moguillansky (<notifications@github.com>) kirjutas
kuupäeval L, 6. juuni 2020 kell 20:46:

**Comment by csounder** [comment]
Yes,  I am on Mojave now, and I can confirm that the older path is perfect
on earlier macOS operating systems, but on the latest Catalina 10.15.5
there is a new path to the Terminal,
(and possibly to other installed utilities too perhaps?)



*Dr. Richard Boulanger*

**Comment by csounder** [comment]
I can also confirm the following - when I Run or Render a .csd from
CsoundQt-v0.9.8-rc1-1
it uses the "installed" from the Mac installer release version of Csound
from Jan 2020,
but when I Run in Terminal the same .csd from CsoundQt-v0.9.8-rc1-1 it uses
my latest Brewed build from the sources.

It would be nice if, by default, the CsoundQt version also printed out, in
the console, the version of Csound that it is using when running and
rendering (as does the version in the terminal)
it does tell the user which libsndfile is being used.port audio is being
used (PortAudio V19.6.0-devel, revision
396fe4b6699ae929d3a685b3ef8a7e97396139a4)

This is the version shown when I run in terminal (above is, the PortAudio
version that is being used when I "Run")

--Csound version 6.14 (double samples) Jun  6 2020

[commit: 672a1625d721d0e1cc8a382f20cc29ec151abb82]

libsndfile-1.0.28


*Dr. Richard Boulanger*

*Professor of Electronic Production and Design*

Professional Writing and Technology Division

*Berklee College of Music*


skype: radiobaton

facebook: https://www.facebook.com/richard.boulanger.58

about: http://www.boulangerlabs.com/#about

about: http://www.csounds.com/community/developers/dr-richard-boulanger/

music:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/


Boulanger Labs - http://boulangerlabs.com

The Csound Book - http://mitpress.mit.edu/books/csound-book

The Audio Programming Book -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by csounder** [comment]
Curious, because Joachim Heintz told me that he was running CsoundQt rc2,
because he had built from that latest sources.
I am wondering...  (and hoping too)

Is there a way to brew install csoundqt or brew install --HEAD csoundqt

Is there a way to brew install the Csound Manual?

*Dr. Richard Boulanger*

**Comment by joachimheintz** [comment]
yes this is the way apple makes (substantial) changes ...
we struggled in Mojave with any RT Audio Module, and at the end, only 
Jack OSX was working reliably.
and now, in Catalina, everything is working again (fortunately!).
not a nice job for developers ...

**Comment by joachimheintz** [comment]
i don't know about a brew install, but what you certainly can do is to 
build CsoundQt with QtCreator.  we don't have the best descriptions for 
it, but:
https://github.com/CsoundQt/CsoundQt/wiki/Building-CsoundQt-for-OSX-with-QtCreator

improvements or even a blank new version are welcome.  in my experience, 
building CsoundQt is much more of a hassle than building Csound.  but as 
always: once it is set up, you simply push a button and get the most 
recent version ...

**Comment by csounder** [comment]
I will try to follow those instructions later this week for CsoundQt and let you know how it goes.

Before RT Audio begins, there is still that 5 second delay if one selects an audio input. Thanks Apple


Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tarmoj** [comment]
Hi, Richard, 

I have to think a bit if there is a good way to find correct path automiatically.  Meanwhile can you check the defined default locations (int types.h) -  where are these on Catalina?

#ifdef Q_OS_MAC
#define DEFAULT_HTML_DIR "/Library/Frameworks/CsoundLib64.framework/Resources/Manual"
#define DEFAULT_TERM_EXECUTABLE "/Applications/Utilities/Terminal.app"
#define DEFAULT_BROWSER_EXECUTABLE "/Applications/Firefox.app"
#define DEFAULT_WAVEEDITOR_EXECUTABLE "/Applications/Audacity.app"
#define DEFAULT_WAVEPLAYER_EXECUTABLE "/Applications/QuickTime Player.app"
#define DEFAULT_PDFVIEWER_EXECUTABLE "/Applications/Preview.app"
#define DEFAULT_DOT_EXECUTABLE "/usr/local/bin/dot"
#define DEFAULT_LOG_FILE ""
#define DEFAULT_SCRIPT_DIR qApp->applicationDirPath() + "/../Resources/Scripts"
#endif

If I look at the code, if the terminal app is not found, it should give you a warning and ask to check the path in Cinfigure->Environment already.

tarmo

**Comment by tarmoj** [comment]
Fixed for v0.9.8.2 (partly in v0.9.8.1)
