### ISSUE TITLE
Examples->Miscellaneous->Auto Tuner - syntax error

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#317]
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
error: syntax error, unexpected '*', expecting NEWLINE  (token "*") from file /private/var/folders/_k/2q5495095d53gw9b674tdxdc0000gq/T/csound-tmpcTKnLjdF.csd (1)
 line 187:
>>>aout+aout2+aout3)* <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

**Comment by joachimheintz** [comment]
fixed
