### ISSUE TITLE
Problem in opening a .csd file from a folder with Farsi name

### ISSUE THREAD

**Issue by amin-khoshsabk** [CsoundQt/CsoundQt#323]
Dear Developers of CsoundQt,

I am from Iran and I have lots of folders in my laptop that have Persian (Farsi) names. I noticed that CsoundQt can not open .csd files that are located in such folders. 

Thanks and with best regards,
Amin Khoshsabk

**Comment by gesellkammer** [comment]
Thanks for reporting. I Can't reproduce here with: `/home/user/سند/foo.csd` loads correctly. The problem is probably somewhere else regarding locale settings, etc. But of course, if you have problems, the pragmatic advice is to succumb to the imperialist powers of the west and limit yourself to the latin characters and left-to-right writing systems.

**Comment by amin-khoshsabk** [comment]
Thanks for answering. Yes I succumbed at first day I faced this problem =))
You said it might be a local problem but I just have this issue with Csound not other programs. Thanks anyway.

**Comment by joachimheintz** [comment]
i remember some crashes in csoundqt for a student using chinese 
characters.  so i am wondering whether there is something in the sources 
we can adjust?

**Comment by tarmoj** [comment]
Hi,

Can you send a compressed folder with a csd file, both with farsi names for
testing?

Thanks for the report!
tarmo

Kontakt joachimheintz (<notifications@github.com>) kirjutas kuupäeval K,
17. juuni 2020 kell 15:25:

**Comment by amin-khoshsabk** [comment]
Hi,
Dear Tarmo Johannes,

Yes, I will attach the compressed folder you asked for.
During testing this issue I realized that I can open the .csd file (both
with farsi name and located in farsi folder) via the File menu in CsoundQt.
But I can not open it by dubble clicking on the .csd file. It was strange!

Thanks,
Amin

**Comment by tarmoj** [comment]
Hi,

I could not find the attachment, maybe you can send a link? I tried to
rename a csd file of mine to  csd.تست  (copied from somewhere, no idea,
what it means...) , the csd ending was added to the left side as supposed
and it was opened as expected when I double clicked on it.

tarmo

Kontakt amin-khoshsabk (<notifications@github.com>) kirjutas kuupäeval N,
18. juuni 2020 kell 00:12:

**Comment by amin-khoshsabk** [comment]
Oh, it's strange!! it exists in my mail. Anyway I uploaded it in wetransfer.

here is the link:
https://we.tl/t-7wjI7ezikB

Thanks

**Comment by amin-khoshsabk** [comment]
My operating system is Windows 8.1. Maybe it happens in Windows!

**Comment by tarmoj** [comment]
Well, yes, it opens on Linux.
When I get a chance to try on a Windows machine,  I will test.
The problem might be that if you doubleclick on the file in file manager,
it forwarded as command line argument, so  maybe windows converts it to
something else from UTF-8 encoding.

As note to myself, there might be relevant information on this:
https://stackoverflow.com/questions/4101864/windows-unicode-commandline-argv

tarmo

Kontakt amin-khoshsabk (<notifications@github.com>) kirjutas kuupäeval N,
18. juuni 2020 kell 12:25:
