### ISSUE TITLE
bug in the theme on windows with button pictures and icons

### ISSUE THREAD

**Issue by Parlazo** [CsoundQt/CsoundQt#324]
if i change any program language settings and save them,
then close csoundQT and reopen it,
then change back to english display language in the settings window,
all button pictures and icons do not appear any more, except of the htm5 button and icon

if i go to regedit >local user software csound gui< and delete the "theme" key all buttons and icons reappear
a other solution is to open regedit >local user software csound gui< and edit the "theme" key and enter as a value "boring" if it is probably empty... this will bring back the icons and pictures too
![button_and_icons_and_shortcuts_gone_after_save_language_settings](https://user-images.githubusercontent.com/66982240/85143859-97a94b80-b24a-11ea-9ec3-712de4104005.gif)

this is on windows 7 64 bit in 2020

a similar bug happens with the shortcuts ... after save application language options they are all lost while the binary key "shortcuts" does still appear in regedit... but when fixing the theme key to boring it does not fix the shortcuts... i have to set the shortcuts to default form csoundQT it self to get them back

maybe the best solution would be to avoid windows registry at all
in example applications as mod-plug give the choice at install to use registry or a file to store settings
or to disconnect application settings and theme settings and shortcut settings from each other
or to fix what ever is causing this strange behaviour 

thanks for looking into this

**Comment by Parlazo** [comment]
i think the bug has to do with a file qt_en.qm because it is only 1kb
i just can guess
csoundQT is using all pictures from within the code
once the language changes it will use language settings
and if set back to english it tries to use the language settings from the qt_en.qm file which is 1kb
and there are no button pictures or icons
so it uses a fallback display text from the application it self but does not fall back to the pictures and icons in the application it self and cant find any thing in the qt_en.qm file

just a guess

but strange if set back to an other language it then does not use the pictures and icons again until a full settings reset or regedit change from theme nothing/empty to theme boring

and once the theme pictures and icons got lost it also cant find its shortcut settings which still appear in the registry but do not get used by csoundQT... and i cant find a easy way to reactivate the shortcuts in the windows registry ... but the buttons and icons come back the theme is manually set to boring in the registry

**Comment by tarmoj** [comment]
Hi,

I cannot reproduce it on Windows 10  with freshly built CsoundQt 0.9.8 -  changing the language works as expected.
I suspect there is something wrong in the registry where the options are saved. Can you try to completely delete csound/qutecsound fodler with registry editor? (on my system it is under Computer\HKEY_CURRENT_USER\Software\csound\qutecsound\ ) 

the new build is up for testing on:
http://tarmo.uuu.ee/varia/failid/cs/CsoundQt/CsoundQt-0.9.8-Win64.zip

Greetings,
tarmo

**Comment by tarmoj** [comment]
Hi, 

Do you have any feedback? Is everything all right?
The latest windows build is:
https://github.com/CsoundQt/CsoundQt/releases/download/v0.9.8.1/CsoundQt-0.9.8.1-Win64.zip

tarmo
