### ISSUE TITLE
Widget, midi learn, note on/off

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#325]
Am I right that the midi learn function, for say a button, doesn't map to midi note messages, only CC data? 

I've rigged up a instr to handle the latched active state and adding removing an instrument. Is that the correct way regarding notes? (I could I guess just change the note to a cc on the controller, but I'mm curious)

cheers

**Comment by tarmoj** [comment]
Yes, you are correct, MIDI bindings work only via CC messages.
If you want to make something happen on noteon/off, you have to program it
in your Csound code.
Tarmo

L, 20. juuni 2020 01:36 Si Mills <notifications@github.com> kirjutas:

**Comment by boonier** [comment]
thanks for clarifying @tarmoj :)
