### ISSUE TITLE
Opening .orc forces you to save as .csd

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#326]
But it seems it does it anyway even if you hit Cancel. Can CsoundQT handle files other that aren't csds?

Also when opening a .udo file and not editing, then closing, it asks you to save as if the edit buffer has changed somehow.

on Mojave 10.6.4 / Version 0.9.8-rc3

**Comment by tarmoj** [comment]
Hi,

Thanks for the report!
Did you know that you can control orc/sco -> csd in in Configure->Editor->Behavior->"Automatically Join orc/sco files" ? Uncheck it and please try again.
I can reproduce the udo thing - udo file that is openened is marked as edited and CsoundQt asks it to be saved even though user does not do anything in the editor.

tarmo

**Comment by boonier** [comment]
>Did you know that you can control orc/sco -> csd in in Configure->Editor->Behavior->"Automatically Join orc/sco files" ? Uncheck it and please try again.

Oh right, huh, I didn't realise/think of that. It works for me. That would explain automatic creation of the .csd

cheers!

**Comment by tarmoj** [comment]
And there is a new build up there:
http://tarmo.uuu.ee/varia/failid/cs/CsoundQt/CsoundQt-0.9.8-MaOS.dmg
to test the UDO opending.

tarmo

Kontakt Si Mills (<notifications@github.com>) kirjutas kuupäeval N, 25.
juuni 2020 kell 10:31:

**Comment by boonier** [comment]
YEp that seems to be working great, 

thanks
