### ISSUE TITLE
Chose "recommend" in CsoundQt-rc3 Environment Configure Tab -  "no RT Audio Libraries Found..."

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#328]
Fresh install of Csound6.14.0-MacOS_x86_64 (from .dmg @ csound.com) on MacOS Catalina
Using CsoundQt0.9.8-rc3  (after reset and reboot)
Selecting "recommend" in the Environment Tab

dialog appears - "No real-time audio modules were found.
Make sure OPCODE6DIR64 is set properly in your systemor the configuration dialog."

also note that you are missing a space between system and or in the warning message, but I am thinking that your recommended setting should probably know where the RT audio is located - as... it did find the RT audio before choosing the recommended settings.

ALSO - Eduardo reported to me that these "path" settings are just for when one is running in the terminal.  Maybe it should say that somewhere or somewhen you are setting them?  Maybe it does - and if so, forgive this recommendation

**Comment by gesellkammer** [comment]
This is fixed in the git (recommend function has been disabled)
