### ISSUE TITLE
Inconsistent tagging

### ISSUE THREAD

**Issue by dvzrv** [CsoundQt/CsoundQt#329]
Hi! I package csoundqt for Arch Linux.

The recent release has changed the tagging scheme from `$major.$minor.$patch` `v$major.$minor.$patch`.
Was this intended?
I'm asking because automated tooling looks for the latest releases on upstreams and if you'd use a different scheme next time again it will order below this one.

**Comment by gesellkammer** [comment]
This was recommended as a tagging scheme and the change is intended.

**Comment by dvzrv** [comment]
Cool, thanks for the confirmation! :)
