### ISSUE TITLE
Feature request: ideas for tabs

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#330]
1. It would be great if you could rearrange tab order, much like in Chrome or Firefox to group related patches together.

2. Show an icon to display status of a tab i.e. is it playing.

3. With a lot of tabs open, it can get pretty confusing to see which tab is which - perhaps hovering over a tab could show a tooltip of the filename.

4. In addition to point 3, would it be possible to show the currently open tabs in the menu, say under "Tabs" or something. Or could be a panel to organise them maybe? 

5. Kind of related to point 1, but being able to create a new window so related tabs could live together and be stored in a session - maybe all tabs in the window could be started at same time using a command (providing the option is set in config perhaps).

All this is to say; loving the new 0.9.8 version and all its new features. Starting to feel really tight and stable. 

Thanks :)

**Comment by tarmoj** [comment]
Hi,

After very long time -  first I thought that this all requires too much work, on second thought I now made moving the tabs by drag and drop possible.  (now in git develop branch).
I will think about the other ideas.

Thanks!

tarmo

**Comment by tarmoj** [comment]
And I implemented proposition 2 -  added play/stop/pause/record icon for tabs. Indeed, it is helpful in some situations.

**Comment by tarmoj** [comment]
Other things I leave undone for now.

Thanks for the report and ideas, anyway!

tarmo
