### ISSUE TITLE
CSoundQt freezes with certain examples

### ISSUE THREAD

**Issue by marcoose777** [CsoundQt/CsoundQt#333]
I wish I could be more helpful, I've attached gdb to a running instance to try and get more information, but working through the FLOSS manual, and loading the examples I have found some (I can confirm the linrand and trirand sample code does this) cause the GUI to freeze/become unresponsive. Inserting GDB into the process just provided information about process forking, and very little concrete information. These samples work fines when <Run In Terminal>, you might consider disabling the unhelpful default setting of enabling Autoplay files when launched from file which actually translates to Autoplay file on load.. which makes troubleshooting very difficult.   

I've scratched around the 'crashing' scripts/the documentation and this e 'directive' in the {CsScore} section looks very suspicious: e 99999... It seems to be saying something like end when I've spent the day in the student bar, or the background entropy of the universe approaches 0. That doesn't explain why it is happy executing in the terminal, but not from the GUI front end.

**Comment by gesellkammer** [comment]
It escapes my understanding that someone is able to use gdb but does not care to put the basic information for an issue (os, csoundqt version, csound version, code, error produced, etc.)

So, I will close this and you try again.

**Comment by tarmoj** [comment]
Hi marcoose,

Thanks for the report!

The most helpful would be to know which examples exactly cause the crash? You said that "I can confirm the linrand and trirand sample code does this" but please help with naming concrete FLOSS manual example files to test the issue.

Thanks!
tarmo
