### ISSUE TITLE
Controller widget: changing  border color

### ISSUE THREAD

**Issue by bernardgeyer** [CsoundQt/CsoundQt#335]
Sorry, I forgot to repost this issue here before:

Concerning the Controller widget, I’m very glad that I can get rid of this awful black background!
However, there is still something that is missing : to change the border
color.
F.e. by using meters, it is not a good idea that the border of the
« overflow » square is red.

**Comment by tarmoj** [comment]
Hi,

Thanks for report!
I don't understand -  there is option for the border color version
0.9.8(.2-pre)  (See attachment)
Or what do you mean?

tarmo
[image: controlled-widget.png]

Kontakt bernard (<notifications@github.com>) kirjutas kuupäeval N, 13.
august 2020 kell 12:30:

**Comment by bernardgeyer** [comment]
Oh yes, sorry, it is now in the new version!

Eduardo Moguillansky asked me to add an issue on this and I forgot it. But it was done anyway, so this issue can be closed.
