### ISSUE TITLE
GUI button in event mode

### ISSUE THREAD

**Issue by bernardgeyer** [CsoundQt/CsoundQt#336]
in event mode, the event is sent when the button is released. It should send the event when the button is
pressed.

**Comment by tarmoj** [comment]
Hi,

Which version are you using? This has been fixed.
Last release:
https://github.com/CsoundQt/CsoundQt/releases/latest

Tarmo

tarmo

Kontakt bernard (<notifications@github.com>) kirjutas kuupäeval N, 13.
august 2020 kell 12:32:

**Comment by bernardgeyer** [comment]
Oh yes, sorry, it was corrected in the 0.9.8.1 version!
Eduardo Moguillansky asked me to add an issue on this and I forgot. But it was done anyway, so this issue can be closed.

I was expecting that all corrections will be listed in "Changes since 0.9.8"
but I understand that it is not easy.
