### ISSUE TITLE
0.9.8.1 extreme cpu on macOS

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#339]
Mojave 10.14.6
0.9.8.1 CsoundQT
6.15 Csound

```
...

<CsOptions>
--env:INCDIR+=../_Instr;../_UDOs;../_UDOs/csudo;../_ORC; -m0
</CsOptions>

<CsInstruments>
sr = 48000
ksmps = 64
nchnls = 2
0dbfs = 1

instr RainyNess
	afinl noise 1, 0.1
	out afinl, afinl
endin
schedule("RainyNess", 0, -1)
</CsInstruments>

...
```

CPU in Activity monitor is ~80% when running the above from CsoundQT
CPU in Activity monitor is ~0-2% when running the above in Terminal

![image](https://user-images.githubusercontent.com/6206789/92892596-cb8eaa00-f410-11ea-930b-c7e620b1976f.png)

![image](https://user-images.githubusercontent.com/6206789/92892652-d8ab9900-f410-11ea-971a-f680473e44bf.png)

**Comment by boonier** [comment]
also I have reset my preferences

cheers

**Comment by tarmoj** [comment]
Hi,

Thanks or the report!

Please do some more tests to guess the reason:

 -  try to change the audio module to null, then coreaudio
- does it happen with other csd-s as well?
- run the csd with Run in Terminal and send  the actual csound command
flags it is run with (first line in terminal)

tarmo


Kontakt Si Mills (<notifications@github.com>) kirjutas kuupäeval R, 11.
september 2020 kell 11:32:

**Comment by joachimheintz** [comment]
i would defintely recommend to upgrade to osx 10.15 (high sierra).
mojave had nasty audio issues which seem to be solved now.

	joachim

**Comment by joachimheintz** [comment]
(catalina, not high sierra)

**Comment by boonier** [comment]
@tarmoj will do now, thanks

@joachimheintz hmm I would, though I'm hesitant with other software (and hardware) I use that might not be bang up to date. I always seem to be about two operating systems behind anyway!

**Comment by boonier** [comment]
OK update, just for s**ts and giggles I pasted the whole offending code into a new file and ran again - the cpu was nominal.

The difference? I had a scope widget in the old offending file. Adding it back and the cpu shot up again. I played with the update rate - set to min 8 - and some difference was observed, but still pretty high for such a simple patch.

This is on a Macbook pro btw (retina).

**Comment by boonier** [comment]
@tarmoj I'm actually seeing rather large cpu spikes when interacting with the CsoundQT ui - stuff like scrolling the main code view. 

see this screencast https://www.dropbox.com/s/phj2rsbjmedftf2/cpu_csoundqt.mp4?dl=0
