### ISSUE TITLE
PythonQT: support for recording

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#340]
Is it possible to do something like `q.record(1)`?

For example, sometime I like to jam with different patches, but I would like to call `q.record(x)` or `q.recordAll()` to simultaneously record the output of individual files or all, respectively.

Is this supported?

cheers

**Comment by tarmoj** [comment]
Hi!

This is good idea. Not implemented yet but seems not too hard to add.
I will report when I will have chance to do it.

Thanks!
tarmo

**Comment by boonier** [comment]
Ah great! I wonder, would/could it be sample synchronous starting, or is that asking for too much with Python?

cheers

**Comment by tarmoj** [comment]
I am not sure if you can record several documents files in the same time (recordAll() is probably not possible). By hand it is stops recording of one tab when you click on the other, I think. If it were, the CsoundEngines live all in different threads, so it is probably not possible to synchornize them anyway.

Or what did you mean with "sample synchronous starting"?
t

**Comment by boonier** [comment]
Hmm I've managed to manually record two tabs simultaneously without issue (with the preference set), or maybe I'm misunderstanding you?

"sample synchronous starting" - actually thinking about it that's not going to happen across different threads is it :) different graphs and that. I was just thinking of being able to start and record a bunch of tabs so that they're 'sort of' in sync

**Comment by tarmoj** [comment]
Hi!

I am back to some CsoundQt work. I added PythonQt method `q.record([index])` thus
`q.record()`
starts recording of the current document and
`q.record(1) `
the second open document etc.

You have to use `q.stop([index])` to stop the recording (unless Csound is stopped from score anyway).

recordAll() seems too rare need fpr me, so I left it out. Anyone can use a small python loop to achieve that if really needed.

I hope to publish release candidate of CsoundQt 1.0.0 soon where it will be in.

Thanks for the idea!

tarmo
