### ISSUE TITLE
What's New in Csound 6.15.0 - missing from preface of manual

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#341]
Note that. "What's new in Csound 6.15.0" does appear in the online preface of the latest manual:
https://csound.com/docs/manual/PrefaceWhatsNew.html#:~:text=Release%20Notes%20for%20Csound%206.15,which%20has%20long%20been%20requested.&text=lufs%20opcode%20calculates%20a%20momentary,and%20short%2Dterm%20loudness%20meter.

But..

It does not appear in the 6.15 manual that is included with the latest CsoundQt

**Comment by tarmoj** [comment]
Hi!

Thanks for the report!
CsoundQt includes the Csound manual that is available at the pacakgind moment in the Csound MacOS bundle. CsoundQt does not access the online manual that may have been updated meanwhile. Although a bit old-fashioned, I think it is good that some software does not depend on being constantly online.
Yet, user can always  download necessary manual version to the computer and set its path from: 
Configure -> Environment -> Html doc directory  (not veruy clear name, I see now...)
And there is also  a menu entry Help->Download Csound Manual, that is directed to manual of  Csound 6.14.0, I see now too.

So a couple of things came out, that I will fix eventually (sorry, now it is hard to find time for CsoundQt... )

Thanks!
tarmo
