### ISSUE TITLE
Problem after installation : "The procedure entry point inflateValidate could not be located"

### ISSUE THREAD

**Issue by raphyduke** [CsoundQt/CsoundQt#342]
After installing Csound and CsoundQt I have this error message :  "The procedure entry point inflateValidate could not be located in the dynamic link library C:\ProgramFiles\Csound6_x64\plugins64\image.dll".
Whenever I try to run a file this same message occurs twice and without any sound.
Is there something wrong with my Windows 10 64bits or have I omitted a certain file ?
Thanks

**Comment by joachimheintz** [comment]
i assume it concerns the image opcode, which you prabably don't need.
does it work when you trash this image.dll?

**Comment by raphyduke** [comment]
The problem doesn't persist.
Thank you
