### ISSUE TITLE
CsoundQt crashes on run

### ISSUE THREAD

**Issue by nzfs** [CsoundQt/CsoundQt#348]
anytime i hit run, or i try to change the input or output in configuration or trying to test audio, csoundqt just crushes

**Comment by nzfs** [comment]
the problem seems to be with the audio configuration, since it don't crash with the RT audio module set to null, but i don't know what else to do.

**Comment by gesellkammer** [comment]
Please be more specific: version, os, csd, settings used, etc.

**Comment by nzfs** [comment]
csound 6.15.0 and csoundqt 0.9.8.1, i'm running windows 10. thanks

**Comment by gesellkammer** [comment]
We need following info: csd, settings (you can post a screenshot of your "Run" settings), sound setup, just all the information that you can provide. Also, run csoundqt in the terminal and paste the debugging information there

**Comment by joachimheintz** [comment]
perhaps this may help, too:
http://csoundqt.github.io/pages/tips-and-tricks.html
http://csoundqt.github.io/pages/configuring-csoundqt.html

**Comment by nzfs** [comment]
thank you. i've already looked through that pages and haven't found a solution. anytime a try to change any audio configuration it crashes
![image](https://user-images.githubusercontent.com/31911456/103031641-fd99c700-453c-11eb-921f-dc6357debb30.png)

for example, if i click the three dots to change de input device, it crashed. the same with the output. i try to test audio setup, it crashed. hit run, crashes. it's very frustrating.

running in terminal gives this:
![image](https://user-images.githubusercontent.com/31911456/103031812-59fce680-453d-11eb-93dd-b109add1acf2.png)

**Comment by joachimheintz** [comment]
looking at the terminal output, it seems strange that your csd did not 
throw any error, also also does not report any performance.

can you please try this:
1. go to Examples > Getting Started > Basics > Hello World
2. save this file on your desktop
3. press "Run in Terminal"
4. if it fails, post the terminal output here.
5. if it runs ok (you should hear a beep), try to press "run".

**Comment by nzfs** [comment]
saving the hello world example on desktop and running on terminal produces no sound: 
![image](https://user-images.githubusercontent.com/31911456/103034086-d7772580-4542-11eb-9fc1-25c413108402.png)

**Comment by joachimheintz** [comment]
yes, no sound and it does not really compile (it should run for 1 second).

all i see from it is that it seems to be a problem with your csound 
installation, not with your csoundqt installation.  it looks like csound 
is crashing (not compiling), not csoundqt.

you said it is working when you select "none" as RT Audio Module?  can 
you post the same output in this case?

**Comment by nzfs** [comment]
when rt audio is set to null, this is the output:
![image](https://user-images.githubusercontent.com/31911456/103036772-435c8c80-4549-11eb-94c6-96dd017e87fb.png)

**Comment by joachimheintz** [comment]
so this is the expected output, and i believe it shows that the problems 
has to do with your realtime audio settings.  i have no idea about 
windows, and i am wondering whether you should move this issue to the 
csound list, as i think it is csound related and not an issue with csoundqt.

perhaps it is worth to try cabbage, and see if it works?
