### ISSUE TITLE
Undocked Help window can not be re-docked

### ISSUE THREAD

**Issue by frmaurer99** [CsoundQt/CsoundQt#349]
I undocked the help window and pull it onto my 2nd monitor. Now I dont seem to be able to re-dock the window as there seems to be no title bar on the window to drag it back into the app window.

OS: Windows 10
![CSoundHelp](https://user-images.githubusercontent.com/74378290/103443240-244eb080-4c55-11eb-8a2e-d2a215372bcc.jpg)

**Comment by tarmoj** [comment]
Hi!

Thanks for the report! I cannot reproduce it on Linux, hope to try later on Windows when I will get a chance.
As a workaround you can try to set Configure -> Widgets are an independent window and restart and later re-check the option, if you need.
Or reset the settings Help-> Reset Preferences.

Best!
tarmo

**Comment by frmaurer99** [comment]
Resetting Preferences brought the |Help window back into the app window.
I'll probably wont bother un-docking it again.
Thanks
Frank

BTW Is there a way to increase the text size of the help window?
