### ISSUE TITLE
Feature Request: Add Eduardo's 'loristrck' analysis utility to the Utilities menu

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#356]
Please consider adding Eduardo's 'loristrck' analysis utility to the Utilities menu
- This is used in the beadsynt opcode example in the manual and would make it easier for users to explore this opcode and this analysis utility without needing to build it

Also worth noting that the man pages of besoc and beadsynt include most of the manpage info in the .csd file This is non-standard however, it was lucky that this additional bit of info was included in the beadsynt.csd example where it gives a clue on how to use the opcode to resynthesize user files and not just the man example - as seen below (the fine print!)

It's a great opcode family and I think with the analysis utility included, it would be used even more - by my students definitely!

‘This example uses the analysis file fox.mtx.wav which was produced with
loristrck_pack, see https://github.com/gesellkammer/loristrck'

**Comment by gesellkammer** [comment]
Thanks for the comment. Sorry, but loristrck depends on python and several external libraries (fftw, libsndfile). This makes it virtually impossible to package within an application like CsoundQt.
Nonetheless it is very easily installed via ``pip install loristrck`` (see https://github.com/gesellkammer/loristrck#osx-using-homebrew for install instructions for macos).

**Comment by csounder** [comment]
Thanks.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music
