### ISSUE TITLE
On MacOS 10.15.7 - Catalina - Record - xxx.wav or xxx.aif  is corrupted or not playable - latest Csound (6.16.1)

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#358]
Once can still use the 'Render to file' button to bounce audio from a .csd (in non-realtime), but, for some reason, using the red circle "Record" button, no longer produces a usable/readable/playable .wav or .aif file from a running .csd (Examples, Toots, Csound Book or  Csound Catalog).  It used to work great.  EG: Pick 'Examples->Synths->Pipe Synth',  "Save As" to Desktop, hit 'Record' - play a few notes, move a few sliders.  Stop.  'Pipe_Synth.csd-000.wav' written to Desktop.  Open in Audacity and Play audio.  But... not any more.  Hopefully an easy fix?

**Comment by gesellkammer** [comment]
Thanks for reporting.

Maybe the version you are using was built without recording support (it is in optional future which must be enabled when building). If you are able to build from source, do

```bash
qmake CONFIG+=record_support CONFIG+=rtmidi qcs.pro
```

for more information on building,see https://github.com/CsoundQt/CsoundQt/wiki/Building-CsoundQt-for-OSX-with-QtCreator

Otherwise you will need to wait for the next build.

**Comment by tarmoj** [comment]
Hi!

I can confirm this on Linux - Record works with Csound 6.15, but not Csound
6.16. Something must have changed in libcsnd6 library. I will investigate a
bit and ask in Csound developers' list later.

Thanks for the report!

Tarmo

N, 15. juuli 2021 11:37 Eduardo Moguillansky ***@***.***>
kirjutas:

**Comment by gesellkammer** [comment]
I can't confirm this, for me it works in linux with latest csound from git

**Comment by tarmoj** [comment]
Hi!

Thanks, Eduardo! My version of Csound was:
--Csound version 6.16 (double samples) Jun 12 2021

I then updated to newest version from git/develop:
--Csound version 6.17 (double samples) Jul 16 2021

No change. Then rebuilt CsoundQt and recording still does not work...
Interesting... Will investigate later.

tarmo




Kontakt Eduardo Moguillansky ***@***.***>) kirjutas
kuupäeval R, 16. juuli 2021 kell 12:51:

**Comment by csounder** [comment]
I am using Csound 6.16.1 with three versions of CsoundQt. .981, beta1 and beta2 and the record button|feature no longer works on M1 (Big Sur) and Intel (Catalina).  I think it is something in the latest Csound perhaps.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by tarmoj** [comment]
It was a porblem in the core Csound (libcsnd6 to be more exact), now fixed in:
https://github.com/csound/csound/releases/tag/6.16.2
With that version recording works again.
Thanks for the report!
tarmo

**Comment by csounder** [comment]
thanks so very much for fixing this and doing a 6.16.2 release.  My
students have a major project (competition) with Csound due on Tuesday and
they have to get it done in "6 hours".  That working record button was
pretty essential to helping them cross the finish line in time.

*- dB*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
