### ISSUE TITLE
system_i opcode and CsoundQt

### ISSUE THREAD

**Issue by tjingboem** [CsoundQt/CsoundQt#360]
why does the system_i opcode does not work in CsoundQt but only when one selects - Run in Terminal from CsoundQt?

Might it have something to do with the fact that CsoundQt puts files into a temporary directory - and maybe the system_i opcode does not have permission to write into that directory?

**Comment by tarmoj** [comment]
Hi,

This is interesting.
What is the command you want to run with system_i - so I can test?

Tarmo

T, 24. august 2021 13:20 Menno Knevel ***@***.***> kirjutas:

**Comment by tjingboem** [comment]
Hi Tarmo,
yes, i have added to all Analyze Utilities examples this system_i opcode.
They first analyze the soundfile in instrument 0, so these become available for use later in the csd.

An example might be the example for adsyn (hetro): https://csound.com/manual/adsyn.html
but for all Analyzing opcodes (except for PVANAL opcodes as i am still am working on them), this system_i opcode is used now.

Personally, i do not use CsoundQt at all, and all examples are developed in Visual Studio Code. This is in fact a terminal.
When an example works from the terminal, whether on a Mac, Linux or Windows, it will be part of the manual.

It seems (but i don't know) that examples using this system_i opcode do not work in CsoundQt.
Apparently they do work from the Terminal in CsoundQt.
Can you check this, please?
