### ISSUE TITLE
CsoundQt 0.9.8.1 opens csd files slowly

### ISSUE THREAD

**Issue by bjorkman52** [CsoundQt/CsoundQt#365]
I have noticed that CsoundQt 0.9.8.1 opens csd files significantly slower than did some previous versions CsoundQt. (My apologies if this topic has been previously covered. I could not find it anywhere.)

In an effort to document this phenomenon, I have tested four csd files of differing sizes on four different versions of CsoundQt on two different computers. The results are below. I have tried to supply as much detail as I thought would be needed, but please tell me if you need more. I would note that I got substantially similar results on the two computers.

--------------------
Computer: Mac mini (2018)
Processor: 3 GHz 6-Core Intel Core i5
Memory: 32 GB 2667 MHz DDR4
macOS version: Monterey 12.0.1
Csound version: 6.16.2

Csd sample file size: 0.3 MB
CsoundQt 0.9.5 opened the file in 0:02
CsoundQt 0.9.6 opened the file in 0:02
CsoundQt 0.9.7 opened the file in 0:02
CsoundQt 0.9.8.1 opened the file in 0:17

Csd sample file size: 0.7 MB
CsoundQt 0.9.5 opened the file in 0:04
CsoundQt 0.9.6 opened the file in 0:05
CsoundQt 0.9.7 opened the file in 0:05
CsoundQt 0.9.8.1 opened the file in 1:11

Csd sample file size: 1.8 MB
CsoundQt 0.9.5 opened the file in 0:15
CsoundQt 0.9.6 opened the file in 0:13
CsoundQt 0.9.7 opened the file in 0:17
CsoundQt 0.9.8.1 opened the file in 8:31

Csd sample file size: 3.9 MB
CsoundQt 0.9.5 opened the file in 1:04
CsoundQt 0.9.6 opened the file in 1:01
CsoundQt 0.9.7 opened the file in 1:08
CsoundQt 0.9.8.1 opened the file in 36:20

--------------------
Computer: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
Processor: 3.1 GHz Dual-Core Intel Core i5
Memory: 8 GB 2133 MHz LPDDR3
macOS version: Monterey 12.0.1
Csound version: 6.16.2

Csd sample file size: 0.3 MB
CsoundQt 0.9.5 opened the file in 0:02
CsoundQt 0.9.6 opened the file in 0:02
CsoundQt 0.9.7 opened the file in 0:02
CsoundQt 0.9.8.1 opened the file in 0:18

Csd sample file size: 0.7 MB
CsoundQt 0.9.5 opened the file in 0:05
CsoundQt 0.9.6 opened the file in 0:05
CsoundQt 0.9.7 opened the file in 0:05
CsoundQt 0.9.8.1 opened the file in 1:20

Csd sample file size: 1.8 MB
CsoundQt 0.9.5 opened the file in 0:19
CsoundQt 0.9.6 opened the file in 0:19
CsoundQt 0.9.7 opened the file in 0:19
CsoundQt 0.9.8.1 opened the file in 8:49

Csd sample file size: 3.9 MB
CsoundQt 0.9.5 opened the file in 1:18
CsoundQt 0.9.6 opened the file in 1:26
CsoundQt 0.9.7 opened the file in 1:23
CsoundQt 0.9.8.1 opened the file in 40:40

--------------------
Am I doing something wrong to cause this slower file opening on CsoundQt 0.9.8.1? 

Much appreciate any assistance with this.

Richard Bjorkman
Boston, Massachusetts, USA

**Comment by tarmoj** [comment]
Hi,

Thanks  a lot for such thorough report and testing!

This is very big difference indeed and I cannot guess right now what can be
the reason, I am not on Mac myself.
It has never been reported before I wonder if this hase something to do
with MacOS 12?
Would you also try also the release candidate of  v 1.0.0:
https://tarmo.uuu.ee/varia/failid/cs/CsoundQt/CsoundQt-1.0.0-rc2.dmg

Although I suspect it will behave like 0.9.8.1 as it is built on the same
platform (although newer Qt version)

Thanks!
tarmo


Kontakt bjorkman52 ***@***.***>) kirjutas kuupäeval N, 18.
november 2021 kell 23:34:

**Comment by bjorkman52** [comment]
Thanks, Tarmo, for the fast response and for all your work on this project.

It has occurred to me also that the speed difference may be somehow connected with the new macOS 12. I recently upgraded both of my computers to macOS 12 and at the same time upgraded my versions of Csound and CsoundQt to the latest versions. At first, I thought that CsoundQt 0.9.8.1 simply was not opening large files, but then I discovered that it would indeed open them albeit slowly.

Let me test CsoundQt 1.0.0-rc2 and see what I find.

Thank you so much.

Richard Bjorkman
Boston, Massachusetts, USA

**Comment by bjorkman52** [comment]
Hi, Tarmo,

I did some testing with CsoundQt 1.0.0-rc2, and I am sorry to say that I am not seeing an improvement.

This time, I tested using only one computer—I felt that testing on a second computer was basically unnecessary, since my initial testing revealed that the two computers produce substantially similar results. Anyway, here are my complete results as tested on my Mac mini, with the newly added results for CsoundQt 1.0.0-rc2 in bold.

--------------------

Computer: Mac mini (2018)
Processor: 3 GHz 6-Core Intel Core i5
Memory: 32 GB 2667 MHz DDR4
macOS version: Monterey 12.0.1
Csound version: 6.16.2

Csd sample file size: 0.3 MB
CsoundQt 0.9.5 opened the file in 0:02
CsoundQt 0.9.6 opened the file in 0:02
CsoundQt 0.9.7 opened the file in 0:02
CsoundQt 0.9.8.1 opened the file in 0:17
**CsoundQt 1.0.0-rc2 opened the file in 0:17**

Csd sample file size: 0.7 MB
CsoundQt 0.9.5 opened the file in 0:04
CsoundQt 0.9.6 opened the file in 0:05
CsoundQt 0.9.7 opened the file in 0:05
CsoundQt 0.9.8.1 opened the file in 1:11
**CsoundQt 1.0.0-rc2 opened the file in 1:14**

Csd sample file size: 1.8 MB
CsoundQt 0.9.5 opened the file in 0:15
CsoundQt 0.9.6 opened the file in 0:13
CsoundQt 0.9.7 opened the file in 0:17
CsoundQt 0.9.8.1 opened the file in 8:31
**CsoundQt 1.0.0-rc2 opened the file in 8:34**

Csd sample file size: 3.9 MB
CsoundQt 0.9.5 opened the file in 1:04
CsoundQt 0.9.6 opened the file in 1:01
CsoundQt 0.9.7 opened the file in 1:08
CsoundQt 0.9.8.1 opened the file in 36:20
**CsoundQt 1.0.0-rc2 opened the file in 38:13**

--------------------

I am sorry that I do not have access to a Mac computer running an older version of macOS. It would be interesting to examine the hypothesis that the new macOS 12 Monterey is somehow causing the slow performance.

Thanks again for your work on this. Please let me know if there is more that I can do.

Richard Bjorkman
Boston, Massachusetts, USA

**Comment by tarmoj** [comment]
Thanks!

Could you please send me your testing csd and the sample file to my email
***@***.*** ?

Tarmo

R, 19. november 2021 01:41 bjorkman52 ***@***.***> kirjutas:

**Comment by bjorkman52** [comment]
HI, Tarmo,

Unfortunately your email address reached me as ***@***.***. Is there some way you send it so that I will get it?

Thanks.

Richard Bjorkman
Boston, Massachusetts, USA

**Comment by tarmoj** [comment]
I think you can attach or copy the text) of csd here and if it is a
"standard" sample from Csound manual like fox.wav, you don't need to  send
it. Otherwise please upload it somewhere and send the link.
I think I can do similar test today on one Mac with some other sample, too.

tarmo

R, 19. november 2021 04:34 bjorkman52 ***@***.***> kirjutas:

**Comment by bjorkman52** [comment]
Hi, Tarmo,

I have created and tested four new files that I specifically designed for testing purposes. Below are my results.

--------------------------------

Computer: Mac mini (2018)
Processor: 3 GHz 6-Core Intel Core i5
Memory: 32 GB 2667 MHz DDR4
macOS version: Monterey 12.0.1
Csound version: 6.16.2

test01.csd
File size: 0.5 MB
CsoundQt 0.9.5 opened the file in 0:03
CsoundQt 0.9.6 opened the file in 0:03
CsoundQt 0.9.7 opened the file in 0:03
CsoundQt 0.9.8.1 opened the file in 0:37

test02.csd
File size: 1.0 MB
CsoundQt 0.9.5 opened the file in 0:07
CsoundQt 0.9.6 opened the file in 0:07
CsoundQt 0.9.7 opened the file in 0:07
CsoundQt 0.9.8.1 opened the file in 2:34

test03.csd
File size: 2.0 MB
CsoundQt 0.9.5 opened the file in 0:19
CsoundQt 0.9.6 opened the file in 0:17
CsoundQt 0.9.7 opened the file in 0:18
CsoundQt 0.9.8.1 opened the file in 9:06

test04.csd
File size: 4.0 MB
CsoundQt 0.9.5 opened the file in 1:11
CsoundQt 0.9.6 opened the file in 1:07
CsoundQt 0.9.7 opened the file in 1:10
CsoundQt 0.9.8.1 opened the file in 37:08

--------------------------

I have uploaded (I think) the four test csd files. Unfortunately, I had to change the filename extensions to txt because the system would not accept csd files. At your end, could you change the extensions back to txt?

I hope my efforts are of some help. I appreciate your work on this.

Richard Bjorkman
Boston, Massachusetts, USA

[test01.txt](https://github.com/CsoundQt/CsoundQt/files/7571956/test01.txt)
[test02.txt](https://github.com/CsoundQt/CsoundQt/files/7571957/test02.txt)
[test03.txt](https://github.com/CsoundQt/CsoundQt/files/7571958/test03.txt)
[test04.txt](https://github.com/CsoundQt/CsoundQt/files/7571962/test04.txt)

**Comment by bjorkman52** [comment]
I just noticed that the last sentence of my previous message is in error. It should read "At your end, could you change the extensions back to **csd**?" 

These are csd files. I had to change the filename extension to txt so that the GitHub system would accept them for upload. If you change the extension back to csd, you will have the csd files I used for my most recent testing.

My apologies for the error.

Richard Bjorkman
Boston, Massachusetts, USA

**Comment by tarmoj** [comment]
Hi!

No problem at all. I am afraid I will not be on a Mac with Csound in closer
days to try it out. If you have any friend with older MacOS, can they give
a try? When you say "CsoundQt 0.9.8.1 opens csd files significantly
slower", I guess the time you measure is from the moment you press Run and
the sound comes out?

I suspect it is some kind of permission problem in the plist file of the
Application that probably is different in older versions, present in
v09.8.1 but MacOS 12 handles it differently. There is  no way it is Csound
that takes so much time, I believe it is the system that waits for some
kind of permission (perhaps to access the files or sound card) and times
out at some point. I have no idea...

One more test  - can you set the audio interface is Configure->Run->RT
audio module to "null", whatch the messages in the console and try to guess
if the lag on loading goes away.

Best!
tarmo

Kontakt bjorkman52 ***@***.***>) kirjutas kuupäeval T, 23.
november 2021 kell 08:51:

**Comment by gesellkammer** [comment]
Thanks for bringing this up, @bjorkman52 . The delay has to do with syntax highlighting. It is a bug in csoundqt and we need to take a closer look at the highlighting code to solve this. To confirm this you can disable syntax highlighting (by setting the color theme to none), then it loads fast. This has nothing to do with the OS, by the way, it can be repeated on all platforms. I guess we didn't load such long .csd to test the code, so we can use the provided .csd for testing

Best regards,
Eduardo

**Comment by bjorkman52** [comment]
Tarmo and Eduardo, thanks for your reply. 

<<When you say "CsoundQt 0.9.8.1 opens csd files significantly
slower", I guess the time you measure is from the moment you press Run and
the sound comes out?>>

I should have been more clear. The time interval I measured is from the instant I tell CsoundQT to open a file (using file > open or something equivalent thereto) until the instant the file actually appears on the screen. Once the file is visible on the screen, it begins playing very quickly after I press Run.

<<The delay has to do with syntax highlighting. It is a bug in csoundqt and we need to take a closer look at the highlighting code to solve this. To confirm this you can disable syntax highlighting (by setting the color theme to none), then it loads fast.>>

I believe you are 100% correct, Eduardo. I just repeated my tests with color theme set to "none." The speed difference is huge:


-------------------

Computer: Mac mini (2018)
Processor: 3 GHz 6-Core Intel Core i5
Memory: 32 GB 2667 MHz DDR4
macOS version: Monterey 12.0.1
Csound version: 6.16.2

test01.csd
File size: 0.5 MB
CsoundQt 0.9.8.1 opened the file in 0:37 with color theme = "classic"
CsoundQt 0.9.8.1 opened the file in 0:02 with color theme = "none"

test02.csd
File size: 1.0 MB
CsoundQt 0.9.8.1 opened the file in 2:34 with color theme = "classic"
CsoundQt 0.9.8.1 opened the file in 0:03 with color theme = "none"

test03.csd
File size: 2.0 MB
CsoundQt 0.9.8.1 opened the file in 9:06 with color theme = "classic"
CsoundQt 0.9.8.1 opened the file in 0:05 with color theme = "none"

test04.csd
File size: 4.0 MB
CsoundQt 0.9.8.1 opened the file in 37:08 with color theme = "classic"
CsoundQt 0.9.8.1 opened the file in 00:09 with color theme = "none"

----------------------------------------------------------------

I think you have identified the problem. Many thanks to both of you, both for this and for your ongoing work on CsoundQt. Please let me know if I can be of further help.

Richard Bjorkman
Boston, Massachusetts, USA

**Comment by gesellkammer** [comment]
@bjorkman52, if you can build from source, check the branch "highlight-fix" and see if that helps. There are more improvements to do, but regarding highlighting this fix solves most of the problems

**Comment by bjorkman52** [comment]
@gesellkammer, I am sorry to say that building from source code is beyond my limited abilities at this point. I am very glad and grateful that you have been able to address the issue, and I wish I could be of more help.

**Comment by gesellkammer** [comment]
@tarmoj, I just pushed many fixes regarding this in the branch "highlight-fix". Could you try this? If it's ok for you I would merge it into the "develop" branch. Most importantly the highlighting code is section aware, meaning that it knows if you are inside the orchestra, score, options, etc. This makes highlighting much more specific and efficient. There is still an ongoing process of updating the code to use `QRegularExpression` instead of `QRegExp` (which is deprecated).

**Comment by tarmoj** [comment]
Thanks a lot for this, Edoardo!
Yes, I will test it on Linux and will do a build for Mac, in a week I hope.
Please remind, if there will be silence on my side.

tarmo

Kontakt Eduardo Moguillansky ***@***.***>) kirjutas
kuupäeval K, 1. detsember 2021 kell 12:21:
