### ISSUE TITLE
Monterey Comnpatibility

### ISSUE THREAD

**Issue by Francesco1301** [CsoundQt/CsoundQt#366]
Unfortunately...my Mac just upgraded to the new Monterey Os.

I'm having some sudden crashes.

I hope my report will prompt the troubleshooter to solve this problem to let people use csound also in Monterey.

Thanks guys.

Cordially : )

F.

**Comment by joachimheintz** [comment]
I have Monterey on a Studio Computer, and there is no problem with 
CsoundQt 0.9.8.1.
Most recommended is a fresh install of Csound, and trying out the best 
fitting RT Audio Module (Configuration > Run).
