### ISSUE TITLE
1.1.0 does not denote a pre-release

### ISSUE THREAD

**Issue by dvzrv** [CsoundQt/CsoundQt#367]
Hi! Please stick to [semver](https://semver.org) when creating tags for releases.
The tag 1.1.0 does not denote a pre-release, which is why I have updated the package on Arch Linux to that version.
Only afterwards I was made aware of the "pre-release" sign on the [1.1.0 release page](https://github.com/CsoundQt/CsoundQt/releases/tag/v1.1.0).

Adding the pre-release sign on github might seem convenient, but it is not correct if you add it to a tag such as 1.1.0 unless you clearly state in a document such as your README.md that e.g. "all odd minor versions are pre-releases" (and it is nothing I would endorse, because it is far more complicated to understand).
It would have been correct if the tag had been e.g. `1.1.0-rc1`.

Downstreams use automated tooling such as [nvchecker](https://github.com/lilydjwg/nvchecker) to probe upstream git repositories (such as yours) for new releases.
As package maintainers often maintain hundreds of packages, they rely on conventions such as semver, which allows them to easily identify whether upstream has released a new version that is deemed stable. They usually do not have the time to visit a custom upstream website which defines "pre-release" in a custom feature (which allows to disregard version conventions).

Do not get me wrong: The pre-release sign is useful for visitors of your github project. However, it is only useful *if* it actually applied to the right thing! :)

**Comment by gesellkammer** [comment]
Thanks! The release was updated

**Comment by dvzrv** [comment]
Eh, sorry, but that brings us straight to https://github.com/CsoundQt/CsoundQt/issues/331 and just broke the reproducibility of the package on Arch Linux. Please do not remove/move tags either! :cry:

**Comment by tarmoj** [comment]
Hi David,

Yes, there has been a mess in the versions.
In fact 1.0.0 has never been released but I guess we cannot go back now
anyway.
What do you suggest, what would be best for your build system, what should
be the next release version?
Can we continue with v1.1.0-rc2 etc and release v1.1.0 when it will be
ready or should it be v1.1.1-rc1 and release v1.1.1?

Thanks!
tarmo

Kontakt David Runge ***@***.***>) kirjutas kuupäeval L, 22.
jaanuar 2022 kell 13:00:
