### ISSUE TITLE
Copy/Paste not working after playing a csd file

### ISSUE THREAD

**Issue by dnaccarato22** [CsoundQt/CsoundQt#368]
The only changes I have made to my Csoundqt Properties are dark theme and some font size increases. After I startup the application and run a file, the copy/paste feature (by mouse and shortcuts) stop working.

**Comment by tarmoj** [comment]
Hi,

It has hardly to do with the CsoundQt. It is a known problem on Windows
that the fltk plugins interfere with the clipboard even if you don't use
any fltk related Csound code.
Try to delete or move away widgets.dll and virtual.dll from Csound plugins
folder (I guess, it was in Program Files/Csoundx64/plugins - sorry, cannot
check right now) and restart CsoundQt.

tarmo

Kontakt dnaccarato22 ***@***.***>) kirjutas kuupäeval K, 26.
jaanuar 2022 kell 18:33:
