### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#369]
1. in the graph widget, there is a red line in front of dark background.  this is hardly visible, in particular with a data projector.  can we replace the red by a lighter color?  (it used to be yellow or white, i think.)
2. i personally don't like that the syntax highlighting for kVar_1 or kVar_2 is (in current develop) always only suggesting "kVar_".  i preferred the old solution (to display all).

**Comment by gesellkammer** [comment]
As of the this commit 53dea9b8cab39d3573baed44dc793b5ba1d54786 both problems have been fixed
