### ISSUE TITLE
SpectrumAnalyzer Example

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#370]
the display in the widget is very impressive but i cannot bring it to play the peak.
line 46: 	kpeak chnget "peak"
kpeak is always zero, and i cannot see how the graph widget can return the peak value (i don't see it in the properties)

**Comment by gesellkammer** [comment]
When you press the mouse button it should play the nearest peak (it should also display the freq. of the peak and the corresponding note name). The widget sets the current peak freq. only when the mouse is down, in the channel set via the @getPeak directive. This is documented in the example for the graph widget. 

```csound

outvalue Swidgetchannel, "@getPeak <peakchannel>"

```
where `peakchannel` is the name of the channel where csoundqt places the current value.

**Comment by joachimheintz** [comment]
brilliant --- i will add a label to make this more clear.
