### ISSUE TITLE
macOS: funny behaviour with widgets

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#371]
Version 1.1.0-rc2
Monterey 12.0.1

When moving the sliders with the trackpad, they jump around. Also moving focus from the widgets panel to code area causes all the sliders to jump to the same value.

**Comment by gesellkammer** [comment]
Can you add your csd?

**Comment by boonier** [comment]
https://www.dropbox.com/s/p2o50ugoohl73aj/FM%20studies%207%20chords%20until%20STRPD.csd?dl=0

I've stripped out most of the instruments and stuff, but the UI is intact and exhibiting the issues I describe (for me)

**Comment by gesellkammer** [comment]
I can't reproduce this in linux. Maybe someone with a mac can jump in. On the meantime, try replacing the sliders with controllers and see if that solves the issue.

**Comment by boonier** [comment]
Can confirm it behaves the same with 0.9.8.1, so may this is an issue with Monterey?

Changing to controller widgets seems to solve the jumpy issue.

**Comment by gesellkammer** [comment]
This seems to be the problem:

https://stackoverflow.com/questions/69890284/qslider-in-qt-misbehaves-in-new-macos-monterey-v12-0-1-any-workaround

**Comment by boonier** [comment]
Spot on. Looks like there's a fix in a newer Qt lib too

**Comment by tarmoj** [comment]
Porting the code to Qt6 is planned but this quite some work... definitely
not a quick fix. Anyway - good to know!
Thanks!
Tarmo

N, 24. veebruar 2022 23:54 Si Mills ***@***.***> kirjutas:

**Comment by boonier** [comment]
You're welcome :) is extending the Qslider a quick and dirty option? (otherwise porting Sliders to the Controller widget would be) 

cheers

**Comment by tarmoj** [comment]
Fixed  in v1.1.2
