### ISSUE TITLE
Console does not appear to respect font-color setting

### ISSUE THREAD

**Issue by jwong00** [CsoundQt/CsoundQt#372]
I've tried to set the font color to a light color  with a dark background color, but it does not work. I've also restarted the CsoundQT while trying different combinations, and it doesn't seem to change.

Addendum: Version 1.1.0-rc2

![CsoundQt-d-html-cs6_dfo3pKFJE7](https://user-images.githubusercontent.com/8384248/157329303-183d6716-da7d-4f28-be80-04581b36d4f7.png)

**Comment by gesellkammer** [comment]
Do you mean the console font color?

**Comment by jwong00** [comment]
Yes, I did mean the console font color. Sorry for the confusion. 

I also just noticed that it actually does, but only for new console output. Any text in the console that is already there won't be changed when the user changes the font color. Newly generated console output will follow the new setting.
