### ISSUE TITLE
Problem when writing files with fout Opcode and "soundin" console message

### ISSUE THREAD

**Issue by raphyduke** [CsoundQt/CsoundQt#376]
Hello, I've recently encountered a problem when writing multiple files using the fout opcode.
Whereas I got the different audio files with their respective names, now I've just one file of all the sounds under the denomination "soundin.0 etc".
I've checked if the I/O were misset but apparently not.
I've redownloaded the latest versions of CSound and CsoundQT but the same mishap occurs.
Would you know if something could be tempted to restore the process to its desired state?

Thank you.

**Comment by joachimheintz** [comment]
please send us a minimal example so that we can run it and see whether 
it is the same.
thanks -
	joachim

**Comment by raphyduke** [comment]
I realized a parameter was omitted in the score.

Raphaël
