### ISSUE TITLE
inspector does not show all instruments

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#378]
some instruments are not shown in the inspector list, at least if many instruments are present.
for instance in [this](https://joachimheintz.de/globales/Arcade_Csound/Arcade_Csound.csd) file:
- line 496 instr PlaybackRec is not shown
- line 1952 instr Midi is not shown
- line 2363 instr Del_1A not, and same for the following
i cannot see any rule in it, but perhaps someone can have a look?
this is with most recent CsoundQt development version, on debian 11.

**Comment by gesellkammer** [comment]
This is a bug with parsing multiline comments (/* */). If  you remove those comments  you should see all instruments appear. We need to investigate the parsing code.

**Comment by gesellkammer** [comment]
This should be now fixed, see 1c23d4c616d073cb16a99e54deecbc7d31a5657a

**Comment by joachimheintz** [comment]
this was fast =)

yes i can confrim it works now.  thanks!!

	joachim
