### ISSUE TITLE
Commands Export

### ISSUE THREAD

**Issue by SonikArchitects** [CsoundQt/CsoundQt#379]
Would like to request a custom key commands export. Upon a hard crash all custom commands are wipped.
Is there a hidden file / .json this already lives in? Would be very helpful to have a save/load custom key commands.

Best,
_BT

**Comment by SonikArchitects** [comment]
If I crash Csound my key commands are gone - is there a new build?
Thanks so much for the quick response!

Best,
_BT

**Comment by gesellkammer** [comment]
No, you need to build from source

**Comment by SonikArchitects** [comment]
Thanks for the help - struggling to do this from build/make file but I'll figure it out! 
Thank you,
_BT

**Comment by gogins** [comment]
BT, are you on an Apple computer with an M1 processor? If so you will have
to factor that in. I am using the homebrew build (brew install csound) and
it installs a universal binary. Last time I checked the official Csound
build was not a universal binary, it was built for Intel architecture only.
That meant it ran on my PowerMac, but it would not load plugins or other
dependencies that were compiled for ARM architecture. The homebrew build
works fine with that.

I am going to try to build the current version using the homebrew recipe on
my Mac, I'll keep you posted on how that goes.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by SonikArchitects** [comment]
Hey Michael - I am on an M1. Tried and tried to build for this machine, sounds like this is what I wasn't able to do it. Thanks so much for the heads up. If you have any luck running on an M1 please lmk. I'm working with Csound daily and it's a nightmare my key commands being chucked out every time it crashes. 

Super appreciate all the interactivity from you guys!
Best,
_BT

**Comment by tarmoj** [comment]
Hi!

I made a new build (intel) but should work also on M1. Please try:
https://github.com/CsoundQt/CsoundQt/releases/download/v1.1.0-rc2/CsoundQt-1.1.0-rc3-MacOS.dmg

tarmo

**Comment by SonikArchitects** [comment]
Thank you SO much @tarmoj - I am dling now!
Best,
_BT
