### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by SonikArchitects** [CsoundQt/CsoundQt#380]
Would be amazing to have a preset "dark mode" behavior similar to other modern OSX apps.
You can kind of hack around this but can't get at all UI elements so preference would be a native dark mode.

Best!
_BT

**Comment by tarmoj** [comment]
Hi!

There hase been work on the dark mode: https://github.com/CsoundQt/CsoundQt/releases/tag/0.9.8-rc3

But at this point, with the work of Eduardo I think it is now reasonably supported -  see the attachment. The problem hard to solve is the widget panel with user defined colors on the light theme context -  if system theme is dark,  the line edits, checkboxes etc take the system theme but some other components that have user defined colors (like text color) may contradict them and the widget panel looks bad or unreadable.

tarmo
![Screenshot 2022-07-15 at 14 07 50](https://user-images.githubusercontent.com/7684691/179214637-ec791720-7544-467c-a637-ffefab233482.png)

**Comment by SonikArchitects** [comment]
This looks amazing to me! I will be very excited to see this folded into an M1 build!
Best,
_BT
