### ISSUE TITLE
Fails to load externals csound plugins

### ISSUE THREAD

**Issue by PasqualeMainolfi** [CsoundQt/CsoundQt#381]
I have this problem with csoundqt (v. 1.1.0) and csound-plugins (on MacBook Pro M1 Apple Silicon M1 Pro)…
if I run a script in qt, this is the output:

``` console
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libimage.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libjacko.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libmp3out.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libpathtools.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libfaustcsound.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libfluidOpcodes.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libelse.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libbeosc.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libwiimote.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libstkops.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libpy.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libhdf5ops.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libp5g.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/librisset.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libklib.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libjackTransport.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libsndmeta.dylib' (-1)
WARNING: could not open library '/Users/pm/Library/csound/6.0/plugins64/libpoly.dylib' (-1)
UnifiedCSD:  /Users/pm/CloudStation/Drive/ComputerMusicCoding/CSoundEducational/Csound_Graphic/ImmagineSonografica/test.csd
rtaudio: PortAudio module enabled ...
using blocking interface
error: syntax error, unexpected STRING_TOKEN  (token """) from file /Users/pm/CloudStation/Drive/ComputerMusicCoding/CSoundEducational/Csound_Graphic/ImmagineSonografica/test.csd (1), line 16:
 >>>  <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
````

but if i run the script in term everything seems to be going well... this is the output

```console
UnifiedCSD:  /Users/pm/CloudStation/Drive/ComputerMusicCoding/CSoundEducational/Csound_Graphic/ImmagineSonografica/test.csd
rtaudio: PortAudio module enabled ...
using callback interface
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
--Csound version 6.18 (double samples) Oct 20 2022
[commit: f0bea4d87b49da2be7e9f1fc77826a7327cbc391]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 44100.0, kr = 44100.000, ksmps = 1
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19.7.0-devel, revision 147dd722548358763a8b649b3e4b41dfffbcfbb6
   0: dac0 (Altoparlanti MacBook Pro [Core Audio, 0 in, 2 out])
PortAudio: selected output device 'Altoparlanti MacBook Pro'
writing 2048 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:
instr 1:  iw = 265.000  ih = 191.000
B  0.000 ..  1.000 T  1.000 TT  1.000 M:  0.00000  0.00000
Score finished in csoundPerform().
inactive allocs returned to free space
end of score.		   overall amps:  0.00000  0.00000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 1.080s, CPU: 0.025s
closing device
44 2048 sample blks of 64-bit floats written to dac
```
solutions???

**Comment by gesellkammer** [comment]
How did you install csound 6.18? How did you install the external plugins? Is your csound version running natively (arm) or is it x86-64? I have very limited experience with macos and less so with its dual architecture transition but I would guess that you might have multiple installations of csound, or using the csound lib provided by csoundqt, which might be arm (and thus fails to load the external plugins which are compiled for x86-64) while the csound binary you are calling at the terminal is x86-64.

**Comment by PasqualeMainolfi** [comment]
Natively on arm (only one version of csound is installed). 
Same problem when I run the script in Cabbage.

**Comment by gesellkammer** [comment]
You did not answer all the questions

**Comment by PasqualeMainolfi** [comment]
You're right. Csound 6.18 from .dmg while external plugins were build manually.

**Comment by gesellkammer** [comment]
If you see external opcodes listed in the terminal (csound -z1) then your
csound binary  shares the same arch as the plugins, while the csound lib
used in csoundqt does not. So, if you want to get any further help please
provide the information requested: how did you I stall csoundqt, for which
architecture, how did you install csound, for which arch., etc.

Pasquale Mainolfi ***@***.***> schrieb am Sa., 29. Okt. 2022,
15:17:

**Comment by tarmoj** [comment]
Hi!

Unless you did not build CsoundQt yourself, at this point it is only
available in Intel x86-64 architecture and linked agains Intel x86 Csound
library. That explains the mismatch. Unfortunately at this point (but I
hope to do a M1 build of CsoundQt at some point) you need to stick to the
x86-64 build of Csound and plugins to use it within CsoundQt.

Other than the plugins - does CsoundQt works for you otherwise?

Thank for the report!
tarmo

Kontakt Eduardo Moguillansky ***@***.***>) kirjutas
kuupäeval L, 29. oktoober 2022 kell 16:34:

**Comment by PasqualeMainolfi** [comment]
I got it. 
I can tell you little (seems to work) because i still testing. I will write to you in case I notice something wrong.

Thanks to you and Eduardo

**Comment by boonier** [comment]
I have a question relating to this (i hope) and installing different versions of Csound. 

I just installed 6.18.0 via homebrew (which installs the binary to `opt/homebrew`), which is not the usual path that CsoundQT expects (`/usr/local/bin/csound`)

Is that location hardcoded into CsoundQT? If I change the path in the Prefs > Environment to the homebrew location, that seems to only affect which Csound binary to use in Run in Terminal, right?

Can I just setup a new $PATH in my zsh config that points to the homebrew location that CsoundQT will pick up?
