### ISSUE TITLE
CsoundQt-d-html-cs6 won't start

### ISSUE THREAD

**Issue by Jomme5** [CsoundQt/CsoundQt#384]
CsoundQt-d-html-cs6 won't start 
Windows 10
Only splash screen for half a second then nothing.

**Comment by gesellkammer** [comment]
Please start csoundqt from the teminal and post any debugging messages appearing there

**Comment by Jomme5** [comment]
Nothing: 

.\CsoundQt+Csound>CsoundQt-d-html-cs6.exe
.\CsoundQt+Csound>

**Comment by tarmoj** [comment]
Hi!

Do you have Csound installed? Which version of Csound and CsoundQt? Note -
if you are using CsoundQt+Csound package, it might conflict with you your
previous or existing Csound installation, in that case I suggest to
download CsoundQt without Csound:
https://github.com/CsoundQt/CsoundQt/releases/tag/v1.1.1
(under assets)

Greetings,
tarmo

Kontakt Jomme5 ***@***.***>) kirjutas kuupäeval K, 15. märts
2023 kell 22:15:
