### ISSUE TITLE
help is not working 

### ISSUE THREAD

**Issue by geiffel23** [CsoundQt/CsoundQt#385]
Help is not working properly at all. 
I can't have definitions, and even when searching them. 
<img width="887" alt="Capture d’écran 2023-05-21 à 15 49 12" src="https://github.com/CsoundQt/CsoundQt/assets/134213192/615c41ac-ccf8-489c-958b-4ef58d94f80a">

**Comment by gesellkammer** [comment]
Thanks for the report.

Could you please provide more information about the context of your problem: os, version of csoundqt, how did you install it, has this started happening now, etc.
