### ISSUE TITLE
csqt built with pythonqt support crashes when opening configuration panel

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#387]
i have built csoundqt on a new debian 12 computer following [this](https://github.com/CsoundQt/CsoundQt/wiki/Building-CsoundQt-with-Debian-12) description.

the version without pythonqt works fine.

the version with pythonqt support crashes immediately when i click on the "Configuration" button.
when i start CsoundQt from a terminal, i see this error message:

csoundqt/bin/CsoundQt-d-py-html-cs6: symbol lookup error: csoundqt/bin/CsoundQt-d-py-html-cs6: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version Qt_5

any idea what could be the reason?

**Comment by tarmoj** [comment]
Hi!

Can it be that it does not find the pythonqt libraries or finds wrong ones?
Does
ldd CsoumdQt-executable
give any hints?

 Are both CsoundQt and PythonQt built with the same Qt verion? Not sure if
it would make any difference but it could.

Tarmo


P, 16. juuli 2023 17:54 joachimheintz ***@***.***> kirjutas:

**Comment by joachimheintz** [comment]
yes both are built with qtcreator and the same qt version (5.15.2).

to be clear: the version with pythonqt works in general.  i can run python code, and also csound code.  only when i want to open the configuration, it crashes.  other panels (like widgets) work.

**Comment by tarmoj** [comment]
Hi!

I am back home, rebuilt CsoundQt with PythonQt and cannot recreate the
problem -  Config dialog opens correctly.
It is strange -  ConfigDialog does not use any of the PyhotnQt
functionalities so the problem might be elsewhere.
Can you run CsoundQt in QtCreator in debug mode, it should point to the
line where causes the crash when it happens?

Or can you make another build without PythonQt to see if the behaviour
repeats?
Or maybe you can tell more exactly what settings (pulse/jack/portaudio or
something else) you use so I can perhaps repeat the error? The crash might
come from CsoundEngine as ConfigDialog uses it to determine possible audio
devices.

tarmo

Kontakt joachimheintz ***@***.***>) kirjutas kuupäeval P,
16. juuli 2023 kell 21:17:

**Comment by joachimheintz** [comment]
thanks for looking into it, tarmo.

yes, as i said, i did another build without pythonqt on the same system, 
and there was no issue.  this was surprising for me, too, because the 
configure panel has per se nothing to do with pythonqt.

i guess you are not on debian 12?  i am in holidays now and don't have 
this computer here.  i may look again into it when i am back.

i have one question about the installation process: is it really 
necessary to do `sudo make install` for both, csoundqt and pythonqt?  i 
think i did it only for pythonqt because csoundqt worked without it, and 
i am the only user on this computer.

cheers -
	joachim
