### ISSUE TITLE
csoundqt does not load libelse.dylib although it is included 

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#388]
we have csoundqt 1.1.1 on macosx 13.4 (mac studio with M1 processor).
we have Csound version 6.18 (double samples) Nov 24 2022

csoundqt does not load these libs:
WARNING: could not open library '/Users/fmsbw/Library/csound/6.0/plugins64/libpathtools.dylib' (-1)
WARNING: could not open library '/Users/fmsbw/Library/csound/6.0/plugins64/libelse.dylib' (-1)
WARNING: could not open library '/Users/fmsbw/Library/csound/6.0/plugins64/libbeosc.dylib' (-1)
WARNING: could not open library '/Users/fmsbw/Library/csound/6.0/plugins64/librisset.dylib' (-1)
WARNING: could not open library '/Users/fmsbw/Library/csound/6.0/plugins64/libklib.dylib' (-1)
WARNING: could not open library '/Users/fmsbw/Library/csound/6.0/plugins64/libsndmeta.dylib' (-1)
WARNING: could not open library '/Users/fmsbw/Library/csound/6.0/plugins64/libpoly.dylib' (-1)

when we use csound from terminal, it works.

any idea what could be the reason and how we can solve it?

**Comment by joachimheintz** [comment]
ok --- finally found the reason.  perhaps useful for any similar case to explain.
first reason was that although the computer is arm64, i had to download the plugins for intel because csoundqt is still running under rosetta.
once i downloaded these dylibs, i had to allow each of them to be loaded in the system preferences > security.

**Comment by tarmoj** [comment]
Thanks, Joachim!
Tarmo

R, 27. oktoober 2023 11:04 joachimheintz ***@***.***>
kirjutas:
