### ISSUE TITLE
Just no sound

### ISSUE THREAD

**Issue by thornclock** [CsoundQt/CsoundQt#389]
Hi, I am taking Dr. B's Csound class at Berklee College of Music.
I am desperate to solve this issue so that I can work on my midterm assignment.

<img width="1675" alt="Screenshot 2023-10-24 at 2 29 02 AM" src="https://github.com/CsoundQt/CsoundQt/assets/148846136/bc2b3042-a469-4a1e-baff-88d1c8b14b1f">

So when I play audio test file, there is no sound. However, if I click those 2 channels to, I guess, "unmute" the outputs, I hear the sound. Only on audio test file though.
<img width="1677" alt="Screenshot 2023-10-24 at 2 29 50 AM" src="https://github.com/CsoundQt/CsoundQt/assets/148846136/543fb770-415f-4816-993d-9301fae8a8ad">

When I play other csd files, no sound is coming out of my headphones or Mac speakers.

<img width="884" alt="Screenshot 2023-10-24 at 2 31 14 AM" src="https://github.com/CsoundQt/CsoundQt/assets/148846136/486be186-efa6-44e7-b95e-62b2b9ae3aa0">

It seems like configuration is correctly set. I don't see any error messages.

I tried deleting QT and reinstalling it, and it doesn't solve the issue. I didn't update my Mac to Sonoma, which is the newest version, so I don't think it's the issue of that. And since I can hear sound coming out of audio test file, I'm sure it's something else other than configuration. What should I do? I just hear no sound all of sudden. It was working fine just last week...

**Comment by tarmoj** [comment]
Hi!

The line:
Wiriting 2048 bytes sample blocks to dac0
can give perhaps a clue - on your list dac0 stands for  headphones and dac1
internal speakers. Can you try with headphones or select other output (from
Configure -> Run)?

Also have a look at "overall amps" line in console when the csd is stopped
- if it 0, then there is something in your Csound code and nothing is sent
out, if it is a reasonable number, it goes somewhere, just try to figure
out where :)

Tarmo

Kontakt thornclock ***@***.***>) kirjutas kuupäeval T, 24.
oktoober 2023 kell 09:35:

**Comment by thornclock** [comment]
It works all of sudden... Haha.. Thank you for replying this quickly!!
