### ISSUE TITLE
Source uses `csPerfThread.hpp`, but Csound does not install that header

### ISSUE THREAD

**Issue by barracuda156** [CsoundQt/CsoundQt#392]
The source invokes `csPerfThread.hpp`: https://github.com/CsoundQt/CsoundQt/blob/7834132f23dfb7b502977c7d4f8109ae935ead52/src/csoundengine.h#L32

However it does not exist in Csound headers: https://github.com/csound/csound/tree/master/include
Instead, it is in `interfaces` folder, and those headers are apparently used internally and not being installed: https://github.com/csound/csound/blob/master/interfaces/CMakeLists.txt

**Comment by tarmoj** [comment]
True, it is a problem of the recent Csound installer. You need to download csPerfthread.hpp manually at this point, like
`wget https://raw.githubusercontent.com/csound/csound/master/interfaces/csPerfThread.hpp `
And copy it to you csound include dir.
I will recreate a ticket by Csound.

**Comment by barracuda156** [comment]
I will close this one, since I have fixed the issue for Macports (once PR merged), and the problem is on `csound` side, not here.
