### ISSUE TITLE
CsoundQt1.1.1 - MIDI Learn does not work when one selects Csound MIDI Module

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#398]
When one chooses the Csound MIDI Module - and portMIDI from the dropDown, you can play MIDI examples, BUT... you can not MIDI learn to any of the examples (However, if you choose Internal MIDI and select the same Controller Keyboard, MIDI learn does work as espected.

**Comment by tarmoj** [comment]
This is expected behavior.  You can choose the Csound MIDI module if you just need  MIDI to interact directly with you Csound code. For CsoundQt, to have any control over MIDI (including MIDI learn), the only way is to use the internal MIDI.
