### ISSUE TITLE
Installation instructions are not correct

### ISSUE THREAD

**Issue by gogins** [CsoundQt/CsoundQt#401]
The instructions on the CsoundQt  [Installation page](https://csoundqt.github.io/pages/install.html) instruct one to copy the contents of the "bin" directory, which does not exist in the downloaded archive. Please correct the installation instructions.

**Comment by joachimheintz** [comment]
thanks for the report, mike.
i guess this is for the windows instructions?
could you suggest a correct instruction?

**Comment by gogins** [comment]
I don't currently use or have Windows. However, I think you should simply replace "the bin folder" with "the CsoundQt folder".
