### ISSUE TITLE
Edit: Configuration causes crash

### ISSUE THREAD

**Issue by unihedron** [CsoundQt/CsoundQt#405]
When selecting Edit -> Configuration  causes CsoundQt to crash.

A snippet of the terminal window shows:

...
rtaudio: JACK module enabled
*** stack smashing detected ***: terminated
backtrace() returned 37 addresses
...

**Comment by tarmoj** [comment]
Hi!

Please tell us more - your operating system, CsoundQt version, Csound
version. Do you use normally jack? Can you try with or without jack
running? Can you try resetting the preferences from Help menu? Did it work
before?

Greetings
Tarmo

K, 26. juuni 2024 03:41 Anthony Tekatch ***@***.***> kirjutas:

**Comment by unihedron** [comment]
Hi K,

I am running Arch Linux.

The CsoundQT version is:  1.1.1 (1:1.1.1-2 from the Arch Linux repository), and I also tried the latest git download.

I normally use Jack.

I have stopped Jack and the CSoundQt crashes in the same way, but it was not producing sound this time before I made it crash. I'll try getting CSoundQt running without jack.

I tried resetting the preferences from the help menu and that did not help.

Thank you,
Anthony

**Comment by unihedron** [comment]
Just to add, in case it is not jack that is causing the problem, I have attached my entire terminal session (including the crash):

[session.txt](https://github.com/user-attachments/files/15992634/session.txt)

**Comment by gesellkammer** [comment]
It seems that csound is crashing when trying to use jack as a backend. Can you give more details of your system? Can you run csound from the command line with jack as backend?

What is the result of this:

```shell
csound --version
sound -+rtaudio=jack -odac --devices --get-system-sr
```

**Comment by unihedron** [comment]
I have pipewire running which I thought was supposed to look like jack. And, CsoundQt works normally (outputs sound), but crashes when pressing Edit:Configuration.

Here are the result for those commands you suggested:

> csound --version
--Csound version 6.18 (double samples) Apr  7 2024
[commit: none]
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.000s, CPU: 0.000s

 csound -+rtaudio=jack -odac --devices --get-system-sr
rtaudio: JACK module enabled
*** stack smashing detected ***: terminated

csound command: Aborted
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.257s, CPU: 0.005s

**Comment by unihedron** [comment]
csound seems to work if I set -+rtaudio=alsa, here is the result:

  >\> csound -+rtaudio=alsa -odac --devices --get-system-sr
10 audio input devices
 0: adc:hw:0,0 (ALC889 Analog : ALC889 Analog : playback 1 : capture 1)
 1: adc:hw:0,1 (ALC889 Digital : ALC889 Digital : playback 1)
 2: adc:hw:0,2 (ALC889 Alt Analog : ALC889 Alt Analog : capture 2)
 3: adc:hw:1,3 (HDMI 0 : HDMI 0 : playback 1)
 4: adc:hw:1,7 (HDMI 1 : HDMI 1 : playback 1)
 5: adc:hw:1,8 (HDMI 2 : HDMI 2 : playback 1)
 6: adc:hw:1,9 (HDMI 3 : HDMI 3 : playback 1)
 7: adc:hw:1,10 (HDMI 4 : HDMI 4 : playback 1)
 8: adc:hw:1,11 (HDMI 5 : HDMI 5 : playback 1)
 9: adc:hw:3,0 (USB Audio : USB Audio : capture 1)
10 audio output devices
 0: dac:hw:0,0 (ALC889 Analog : ALC889 Analog : playback 1 : capture 1)
 1: dac:hw:0,1 (ALC889 Digital : ALC889 Digital : playback 1)
 2: dac:hw:0,2 (ALC889 Alt Analog : ALC889 Alt Analog : capture 2)
 3: dac:hw:1,3 (HDMI 0 : HDMI 0 : playback 1)
 4: dac:hw:1,7 (HDMI 1 : HDMI 1 : playback 1)
 5: dac:hw:1,8 (HDMI 2 : HDMI 2 : playback 1)
 6: dac:hw:1,9 (HDMI 3 : HDMI 3 : playback 1)
 7: dac:hw:1,10 (HDMI 4 : HDMI 4 : playback 1)
 8: dac:hw:1,11 (HDMI 5 : HDMI 5 : playback 1)
 9: dac:hw:3,0 (USB Audio : USB Audio : capture 1)
ALSA output: total buffer size: 1024, period size: 256
writing 256 sample blks of 64-bit floats to dac
system sr: 44100.000000
0 256 sample blks of 64-bit floats written to dac
end of score.		   overall amps:      0.0
0 errors in performance
Elapsed time at end of performance: real: 0.023s, CPU: 0.009s

But, I could not find a way to pass those arguments to CsoundQt, so it still crashes with the "stack smash" warning when I click on the Configuration button.

**Comment by gesellkammer** [comment]
This is not a problem of csoundqt but of csound itself. Please open an
issue there or write to the mailing list.
Csoundqt queries the system via csound to check if jack is available in the
system (pipewire is fully supported) but csound crashes there and brings
csoundqt down with it.

Anthony Tekatch ***@***.***> schrieb am Do., 27. Juni 2024,
03:32:

**Comment by gesellkammer** [comment]
Be aware that csound works flawlessly with jack and pipewire for many, many people, so this is probably a problem on your system.

**Comment by tarmoj** [comment]
Hi Anthony!

Seems the problem is in your system/installation. There are two ways you
can try get out from it:

1) sort of a hack:
open the CsoundQt configuration file
$HOME/.config/csound/qutecsound.conf
and look for line containing
Run\rtAudioModule=

it is probably
Run\rtAudioModule=jack

change it to alsa
and following lines to:
Run\rtInputDevice=adc
Run\rtOutputDevice=dac


Or just delete the file and let CsoundQt recreate it. Jack should not be
the default, I am quite sure.

2) fix your jack/pipewire installation. Do other jack programs work fine?
If no, do you have pipewire jack layer  installed properly? You need
something like

pipewire-libjack

And installing that should remove original jack, this way the jack-aware
programs think they are using jack but it is directed to pipewire. Here is
a guide for openSuse, I guess Arch is similar:
https://en.opensuse.org/openSUSE:Pipewire

If other jack programs work, Csound package probably conflicts with some
libraries in your system, then it maybe better to rebuild Csound, it is not
that hard, follow instructions from   Csound's web site
https://github.com/csound/csound/blob/develop/BUILD.md

Hope it helps!

tarmo


Kontakt Eduardo Moguillansky ***@***.***>) kirjutas
kuupäeval N, 27. juuni 2024 kell 08:40:

**Comment by unihedron** [comment]
Thank you Tarmo,
1) Editing the CsoundQt configuration file did not help.
2) I will look into the pipewire installation and csound recompiling.

Thank you gesellkammer,
 I will ask the csound people for clues on the crashing.

FWIW, I tracked down the line where processing stops:
file: configlists.cpp
section: bool ConfigLists::isJackRunning() {
line: CSOUND *cs = csoundCreate(nullptr);

**Comment by gesellkammer** [comment]
As we told you, this is not a crash in csoundqt, but in csound itself. The fact that csound standalone crashes in the exact same way confirms it. But since csound runs without errors in systems similar to yours indicates that the fault is in your system.

**Comment by unihedron** [comment]
Yup, I know. I will try to find the problem now.

**Comment by unihedron** [comment]
Problem solved here:
https://github.com/csound/csound/issues/1903

**Comment by tarmoj** [comment]
Great job, Anthony!
Thank you very much!
Tarmo


E, 1. juuli 2024 12:57 Anthony Tekatch ***@***.***> kirjutas:
