### ISSUE TITLE
csoundqt creates k channels, conflicting with a str channel set later on

### ISSUE THREAD

**Issue by gesellkammer** [CsoundQt/CsoundQt#406]
This is probably some new behaviour, since there are examples which are now failing. The issue is the following: if there is a widget with channel named "foo" and some code which uses outvalue with a string (outvalue "foo", "mystring"), then csound complains that this channel already exists and has a different type. So I am assuming that csoundqt, when setting up the widgets, creates channels of control type. This probably makes the use of "chn_k" not needed for some cases but is really not the solution since this forces all widgets using outvalue to be of control type.

**Comment by tarmoj** [comment]
Hi!

Thanks! I discovered I had not pushed my latest commit about the work with chn_k business. It is a half fix, now you need to declare the channels only when you use chnget (a widget reads from Csound). This is just a half solution and should not be so. I got stuck with the work in January and so it stayed...
I will get back to CsoundQt in the end of July/beginning of August to have another look. I believe it is best to revert this experiment and go back to the chn_k declarations as it was before.

tarmo

**Comment by gesellkammer** [comment]
Can you revert the changes to the previous behaviour until we find a better solution in general?

**Comment by tarmoj** [comment]
Hi!

I am away from the computer for a week and then I will do the revert. If it
disturbs your work, please feel free to turn csoundengine.cpp back to the
state it was before the chn_k work meanwhile.

Tarmo

N, 11. juuli 2024 11:11 Eduardo Moguillansky ***@***.***>
kirjutas:

**Comment by tarmoj** [comment]
Hi!

I reverted the widgets<->channels connection (CsoundEnginge::setupChannels)  as it was and kept the experiments in the branch `channels`  for work on it in the future.
Now all channels must be declared with chn_k (chn_S) to be used via chnget/chnset with widgets. As it was.

tarmo
