### ISSUE TITLE
config button  crashes everything

### ISSUE THREAD

**Issue by FranzRaven** [CsoundQt/CsoundQt#408]
Hello, I am using the csqt AppImage on Void Linux, when I press the config button it crashes immediately, what I can do is run the appimg as root then open the configuration menu and take the changes.
I tried to compile the project as indicated on the page with qtcreator and it compiles well although the problem with the sinister config button persists.
The rest seems to work fine, but without any configuration.

The cli messages at the time of crashes do not show any problem.

**Comment by FranzRaven** [comment]
v1.1.3 have fixed the problem, with csound 6.18 and csound 7  :)

**Comment by FranzRaven** [comment]
thanx, folks

**Comment by tarmoj** [comment]
Glad to hear!

Thanks for the feedback!

tarmo

Kontakt FranzRaven ***@***.***>) kirjutas kuupäeval K, 23.
oktoober 2024 kell 21:32:
