### ISSUE TITLE
[Bug] ftable display update [sf#77]

### ISSUE THREAD

**Issue by mantaraya36** [CsoundQt/CsoundQt#77]
**Reported by joachimheintz on 2010-10-17 09:22 UTC**
a function table display is not updated when the table content has changed

**Comment by mantaraya36** [comment]
**Updated by mantaraya36 on 2013-11-14 00:57 UTC**
- **status**: open --> closed-rejected
- **Group**:  --> v1.0 (example)

**Comment by mantaraya36** [comment]
**Commented by mantaraya36 on 2013-11-14 00:57 UTC**
There is no way for CsoundQt to know when an f-table has changed, as Csound won't report it. This would be a change to be done in Csound itself, as CsoundQt will respond to requests for redraw and for update.

**Comment by gesellkammer** [comment]
Can this problem in some way be resolved? Maybe allowing to send a trigger to the upcode via a channel, indicating to redraw the widget? It would be nice to be able to display a table as it is modified

**Comment by tarmoj** [comment]
I had a look to the source code and seems that the table should be updatated when the table or table index channel values are changed but it does not. I will have a closer look at some point.

**Comment by gesellkammer** [comment]
to have some orientation, could you point to the code which is responsible for this?

**Comment by tarmoj** [comment]
Hi,

it is in the file qutegraph.cpp

https://github.com/CsoundQt/CsoundQt/blob/develop/src/qutegraph.cpp

look for variable bool needsUpdate, function
void QuteGraph::refreshWidget()

I have not stepped it through to see if everything works as expected.

tarmo

**Comment by gesellkammer** [comment]
fixed

**Comment by gesellkammer** [comment]
The graph widget, as existing today, can't show updates in a table, at least not in the way it is conceived today. A new widget "Table Plot" does exactly this in a cleaner and more efficient way
