### ISSUE TITLE
[Bug] syntax highlighting for udo's [sf#78]

### ISSUE THREAD

**Issue by mantaraya36** [CsoundQt/CsoundQt#78]
**Reported by joachimheintz on 2010-10-17 09:28 UTC**
there are two problems for the syntax highlighting of user defined opcodes:
1) they are not highlighted at all
2) if the name starts with a "S", they are highlighted as if they were strings.
it would be great to have them either highlighted as opcodes, or in an own colour.
thanks!

**Comment by gesellkammer** [comment]
Done.
